<?php

namespace Database\Seeders;

use App\Modules\Inventory\Models\Product;
use App\Modules\Tenancy\Models\Tenant;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $tenants = Tenant::all();

        foreach ($tenants as $tenant) {
            $this->createProductsForTenant($tenant);
        }

        $this->command->info('Products created successfully for all tenants!');
    }

    private function createProductsForTenant(Tenant $tenant): void
    {
        $products = [
            // Electronics
            [
                'sku' => strtoupper($tenant->subdomain).'-LAPTOP-001',
                'barcode' => '1234567890001',
                'name' => 'Dell Latitude 15" Laptop',
                'description' => 'Professional business laptop with Intel i7 processor, 16GB RAM, 512GB SSD',
                'category' => 'Electronics',
                'unit_of_measure' => 'piece',
                'cost_price' => 800.00,
                'selling_price' => 1299.99,
                'reorder_level' => 5,
                'reorder_quantity' => 10,
                'is_active' => true,
                'track_inventory' => true,
            ],
            [
                'sku' => strtoupper($tenant->subdomain).'-MONITOR-001',
                'barcode' => '1234567890002',
                'name' => 'Samsung 27" LED Monitor',
                'description' => '27-inch Full HD monitor with HDMI and DisplayPort',
                'category' => 'Electronics',
                'unit_of_measure' => 'piece',
                'cost_price' => 180.00,
                'selling_price' => 299.99,
                'reorder_level' => 10,
                'reorder_quantity' => 20,
                'is_active' => true,
                'track_inventory' => true,
            ],
            [
                'sku' => strtoupper($tenant->subdomain).'-MOUSE-001',
                'barcode' => '1234567890003',
                'name' => 'Logitech Wireless Mouse',
                'description' => 'Ergonomic wireless mouse with USB receiver',
                'category' => 'Electronics',
                'unit_of_measure' => 'piece',
                'cost_price' => 15.00,
                'selling_price' => 29.99,
                'reorder_level' => 50,
                'reorder_quantity' => 100,
                'is_active' => true,
                'track_inventory' => true,
            ],
            [
                'sku' => strtoupper($tenant->subdomain).'-KEYBOARD-001',
                'barcode' => '1234567890004',
                'name' => 'Mechanical Keyboard RGB',
                'description' => 'Gaming mechanical keyboard with RGB backlighting',
                'category' => 'Electronics',
                'unit_of_measure' => 'piece',
                'cost_price' => 60.00,
                'selling_price' => 119.99,
                'reorder_level' => 20,
                'reorder_quantity' => 30,
                'is_active' => true,
                'track_inventory' => true,
            ],
            [
                'sku' => strtoupper($tenant->subdomain).'-PRINTER-001',
                'barcode' => '1234567890005',
                'name' => 'HP LaserJet Pro Printer',
                'description' => 'Black and white laser printer with wireless connectivity',
                'category' => 'Electronics',
                'unit_of_measure' => 'piece',
                'cost_price' => 200.00,
                'selling_price' => 349.99,
                'reorder_level' => 8,
                'reorder_quantity' => 15,
                'is_active' => true,
                'track_inventory' => true,
            ],
            // Office Supplies
            [
                'sku' => strtoupper($tenant->subdomain).'-PAPER-001',
                'barcode' => '1234567890101',
                'name' => 'A4 Copy Paper (500 sheets)',
                'description' => 'Premium white copy paper, 80gsm, 500 sheets per ream',
                'category' => 'Office Supplies',
                'unit_of_measure' => 'ream',
                'cost_price' => 4.50,
                'selling_price' => 8.99,
                'reorder_level' => 100,
                'reorder_quantity' => 200,
                'is_active' => true,
                'track_inventory' => true,
            ],
            [
                'sku' => strtoupper($tenant->subdomain).'-PEN-001',
                'barcode' => '1234567890102',
                'name' => 'Ballpoint Pen Blue (Pack of 12)',
                'description' => 'Smooth writing ballpoint pens, blue ink',
                'category' => 'Office Supplies',
                'unit_of_measure' => 'pack',
                'cost_price' => 3.00,
                'selling_price' => 6.99,
                'reorder_level' => 200,
                'reorder_quantity' => 500,
                'is_active' => true,
                'track_inventory' => true,
            ],
            [
                'sku' => strtoupper($tenant->subdomain).'-NOTEBOOK-001',
                'barcode' => '1234567890103',
                'name' => 'Spiral Notebook A5',
                'description' => 'College ruled spiral notebook, 100 sheets',
                'category' => 'Office Supplies',
                'unit_of_measure' => 'piece',
                'cost_price' => 2.00,
                'selling_price' => 4.99,
                'reorder_level' => 150,
                'reorder_quantity' => 300,
                'is_active' => true,
                'track_inventory' => true,
            ],
            [
                'sku' => strtoupper($tenant->subdomain).'-STAPLER-001',
                'barcode' => '1234567890104',
                'name' => 'Desktop Stapler',
                'description' => 'Heavy-duty desktop stapler, 25 sheet capacity',
                'category' => 'Office Supplies',
                'unit_of_measure' => 'piece',
                'cost_price' => 8.00,
                'selling_price' => 15.99,
                'reorder_level' => 30,
                'reorder_quantity' => 50,
                'is_active' => true,
                'track_inventory' => true,
            ],
            [
                'sku' => strtoupper($tenant->subdomain).'-FOLDER-001',
                'barcode' => '1234567890105',
                'name' => 'Manila Folder (Pack of 100)',
                'description' => 'Letter size manila file folders',
                'category' => 'Office Supplies',
                'unit_of_measure' => 'pack',
                'cost_price' => 12.00,
                'selling_price' => 22.99,
                'reorder_level' => 40,
                'reorder_quantity' => 80,
                'is_active' => true,
                'track_inventory' => true,
            ],
            // Furniture
            [
                'sku' => strtoupper($tenant->subdomain).'-DESK-001',
                'barcode' => '1234567890201',
                'name' => 'Executive Office Desk',
                'description' => 'L-shaped executive desk with drawers, walnut finish',
                'category' => 'Furniture',
                'unit_of_measure' => 'piece',
                'cost_price' => 350.00,
                'selling_price' => 699.99,
                'reorder_level' => 3,
                'reorder_quantity' => 5,
                'is_active' => true,
                'track_inventory' => true,
            ],
            [
                'sku' => strtoupper($tenant->subdomain).'-CHAIR-001',
                'barcode' => '1234567890202',
                'name' => 'Ergonomic Office Chair',
                'description' => 'High-back ergonomic chair with lumbar support',
                'category' => 'Furniture',
                'unit_of_measure' => 'piece',
                'cost_price' => 250.00,
                'selling_price' => 499.99,
                'reorder_level' => 10,
                'reorder_quantity' => 15,
                'is_active' => true,
                'track_inventory' => true,
            ],
            [
                'sku' => strtoupper($tenant->subdomain).'-CABINET-001',
                'barcode' => '1234567890203',
                'name' => 'Filing Cabinet 4-Drawer',
                'description' => 'Vertical filing cabinet, letter size, locking',
                'category' => 'Furniture',
                'unit_of_measure' => 'piece',
                'cost_price' => 180.00,
                'selling_price' => 349.99,
                'reorder_level' => 5,
                'reorder_quantity' => 10,
                'is_active' => true,
                'track_inventory' => true,
            ],
            // Services
            [
                'sku' => strtoupper($tenant->subdomain).'-SRV-INSTALL',
                'barcode' => null,
                'name' => 'Installation Service',
                'description' => 'Professional installation and setup service',
                'category' => 'Services',
                'unit_of_measure' => 'hour',
                'cost_price' => 35.00,
                'selling_price' => 75.00,
                'reorder_level' => 0,
                'reorder_quantity' => 0,
                'is_active' => true,
                'track_inventory' => false,
            ],
            [
                'sku' => strtoupper($tenant->subdomain).'-SRV-MAINT',
                'barcode' => null,
                'name' => 'Maintenance Service',
                'description' => 'Annual maintenance and support service',
                'category' => 'Services',
                'unit_of_measure' => 'year',
                'cost_price' => 100.00,
                'selling_price' => 249.99,
                'reorder_level' => 0,
                'reorder_quantity' => 0,
                'is_active' => true,
                'track_inventory' => false,
            ],
            // Additional electronics
            [
                'sku' => strtoupper($tenant->subdomain).'-TABLET-001',
                'barcode' => '1234567890006',
                'name' => 'iPad Pro 11"',
                'description' => 'Apple iPad Pro with M1 chip, 256GB storage',
                'category' => 'Electronics',
                'unit_of_measure' => 'piece',
                'cost_price' => 700.00,
                'selling_price' => 999.99,
                'reorder_level' => 5,
                'reorder_quantity' => 10,
                'is_active' => true,
                'track_inventory' => true,
            ],
            [
                'sku' => strtoupper($tenant->subdomain).'-WEBCAM-001',
                'barcode' => '1234567890007',
                'name' => 'HD Webcam 1080p',
                'description' => 'Full HD webcam with built-in microphone',
                'category' => 'Electronics',
                'unit_of_measure' => 'piece',
                'cost_price' => 45.00,
                'selling_price' => 89.99,
                'reorder_level' => 25,
                'reorder_quantity' => 50,
                'is_active' => true,
                'track_inventory' => true,
            ],
            [
                'sku' => strtoupper($tenant->subdomain).'-HEADSET-001',
                'barcode' => '1234567890008',
                'name' => 'Wireless Headset with Mic',
                'description' => 'Noise-cancelling wireless headset for calls and meetings',
                'category' => 'Electronics',
                'unit_of_measure' => 'piece',
                'cost_price' => 80.00,
                'selling_price' => 149.99,
                'reorder_level' => 20,
                'reorder_quantity' => 40,
                'is_active' => true,
                'track_inventory' => true,
            ],
            [
                'sku' => strtoupper($tenant->subdomain).'-CABLE-001',
                'barcode' => '1234567890009',
                'name' => 'USB-C Cable 2m',
                'description' => 'High-speed USB-C charging and data cable',
                'category' => 'Electronics',
                'unit_of_measure' => 'piece',
                'cost_price' => 8.00,
                'selling_price' => 16.99,
                'reorder_level' => 100,
                'reorder_quantity' => 200,
                'is_active' => true,
                'track_inventory' => true,
            ],
            [
                'sku' => strtoupper($tenant->subdomain).'-HUB-001',
                'barcode' => '1234567890010',
                'name' => 'USB Hub 7-Port',
                'description' => 'Powered USB 3.0 hub with 7 ports',
                'category' => 'Electronics',
                'unit_of_measure' => 'piece',
                'cost_price' => 25.00,
                'selling_price' => 49.99,
                'reorder_level' => 30,
                'reorder_quantity' => 50,
                'is_active' => true,
                'track_inventory' => true,
            ],
        ];

        foreach ($products as $productData) {
            Product::firstOrCreate(
                [
                    'tenant_id' => $tenant->id,
                    'sku' => $productData['sku'],
                ],
                array_merge($productData, ['tenant_id' => $tenant->id])
            );
        }
    }
}
