export const purchasePermissions = {
    ordersView: 'purchase.orders.view',
    ordersCreate: 'purchase.orders.create',
    ordersUpdate: 'purchase.orders.update',
    ordersSubmit: 'purchase.orders.submit',
    ordersApprove: 'purchase.orders.approve',
    ordersCancel: 'purchase.orders.cancel',
    ordersClose: 'purchase.orders.close',
    ordersDelete: 'purchase.orders.delete',
    goodsReceiptsView: 'purchase.goods_receipts.view',
    goodsReceiptsCreate: 'purchase.goods_receipts.create',
    goodsReceiptsUpdate: 'purchase.goods_receipts.update',
    goodsReceiptsPost: 'purchase.goods_receipts.post',
    goodsReceiptsReverse: 'purchase.goods_receipts.reverse',
    goodsReceiptsCancel: 'purchase.goods_receipts.cancel',
    supplierInvoicesView: 'purchase.supplier_invoices.view',
    supplierInvoicesCreate: 'purchase.supplier_invoices.create',
    supplierInvoicesUpdate: 'purchase.supplier_invoices.update',
    supplierInvoicesPost: 'purchase.supplier_invoices.post',
    supplierInvoicesCancel: 'purchase.supplier_invoices.cancel',
    returnsView: 'purchase.returns.view',
    returnsCreate: 'purchase.returns.create',
    returnsCreateManual: 'purchase.returns.create_manual',
    returnsUpdate: 'purchase.returns.update',
    returnsApprove: 'purchase.returns.approve',
    returnsPost: 'purchase.returns.post',
    returnsReverse: 'purchase.returns.reverse',
    returnsCancel: 'purchase.returns.cancel',
    debitNotesView: 'purchase.debit_notes.view',
    debitNotesCreate: 'purchase.debit_notes.create',
    debitNotesUpdate: 'purchase.debit_notes.update',
    debitNotesApprove: 'purchase.debit_notes.approve',
    debitNotesPost: 'purchase.debit_notes.post',
    debitNotesAllocate: 'purchase.debit_notes.allocate',
    debitNotesReverse: 'purchase.debit_notes.reverse',
    debitNotesCancel: 'purchase.debit_notes.cancel',
    paymentsView: 'purchase.payments.view',
    paymentsExecute: 'purchase.payments.execute',
    fastPurchasesView: 'purchase.fast_purchases.view',
    fastPurchasesExecute: 'purchase.fast_purchases.execute',
} as const;

export function hasPurchasePermission(permissions: string[], permission: string): boolean {
    return permissions.includes(permission);
}
