export const moduleConfig = [
    'dashboard',
    'purchase',
    'sales',
    'vehicle-service',
    'vehicle-rental',
    'finance',
    'inventory',
    'payment',
    'document',
    'item',
    'uom',
    'pricing',
    'supplier',
    'customer',
    'hr',
    'voucher',
    'settings',
] as const;
