export const moduleConfig = [
    'dashboard',
    'purchase',
    'vehicle-service',
    'finance',
    'inventory',
    'payment',
    'item',
    'uom',
    'supplier',
    'customer',
    'hr',
    'vehicle',
    'tenant',
    'configuration',
    'settings',
] as const;
