<?php

use App\Providers\AppServiceProvider;

return [
    AppServiceProvider::class,
    Modules\Core\Infrastructure\Providers\CoreServiceProvider::class,
    Modules\Configuration\Infrastructure\Providers\ConfigurationServiceProvider::class,
    Modules\Auth\Infrastructure\Providers\AuthServiceProvider::class,
    Modules\User\Infrastructure\Providers\UserServiceProvider::class,
    Modules\Tenant\Infrastructure\Providers\TenantServiceProvider::class,
    Modules\Sequence\Infrastructure\Providers\SequenceServiceProvider::class,
    Modules\SystemUser\Infrastructure\Providers\SystemUserServiceProvider::class,
    Modules\OrganizationUnit\Infrastructure\Providers\OrganizationUnitServiceProvider::class,
    Modules\Finance\Infrastructure\Providers\FinanceServiceProvider::class,
    Modules\Vehicle\Infrastructure\Providers\VehicleServiceProvider::class,
    Modules\HR\Infrastructure\Providers\HrServiceProvider::class,
    Modules\Item\Infrastructure\Providers\ItemServiceProvider::class,
    Modules\Inventory\Infrastructure\Providers\InventoryServiceProvider::class,
    Modules\UOM\Infrastructure\Providers\UomServiceProvider::class,
    Modules\Audit\Infrastructure\Providers\AuditServiceProvider::class,
    Modules\Customer\Infrastructure\Providers\CustomerServiceProvider::class,
    Modules\Document\Infrastructure\Providers\DocumentServiceProvider::class,
    Modules\Extension\Infrastructure\Providers\ExtensionServiceProvider::class,
    Modules\Invoice\Infrastructure\Providers\InvoiceServiceProvider::class,
    Modules\Payment\Infrastructure\Providers\PaymentServiceProvider::class,
    Modules\Pricing\Infrastructure\Providers\PricingServiceProvider::class,
    Modules\Purchase\Infrastructure\Providers\PurchaseServiceProvider::class,
    Modules\Sales\Infrastructure\Providers\SalesServiceProvider::class,
    Modules\Supplier\Infrastructure\Providers\SupplierServiceProvider::class,
    Modules\VehicleRental\Infrastructure\Providers\VehicleRentalServiceProvider::class,
    Modules\VehicleService\Infrastructure\Providers\VehicleServiceServiceProvider::class,
    Modules\Voucher\Infrastructure\Providers\VoucherServiceProvider::class,
    Modules\Warehouse\Infrastructure\Providers\WarehouseServiceProvider::class,
];
