export const salesPermissions = {
    quotationsView: 'sales.quotations.view',
    quotationsCreate: 'sales.quotations.create',
    quotationsUpdate: 'sales.quotations.update',
    fastSalesView: 'sales.fast_sales.view',
    fastSalesExecute: 'sales.fast_sales.execute',
    ordersView: 'sales.orders.view',
    ordersCreate: 'sales.orders.create',
    ordersUpdate: 'sales.orders.update',
    allocationsView: 'sales.allocations.view',
    allocationsCreate: 'sales.allocations.create',
    deliveriesView: 'sales.deliveries.view',
    deliveriesCreate: 'sales.deliveries.create',
    customerInvoicesCreate: 'sales.customer_invoices.create',
    receiptsExecute: 'sales.receipts.execute',
    returnsView: 'sales.returns.view',
    returnsCreate: 'sales.returns.create',
    creditNotesView: 'sales.credit_notes.view',
    creditNotesCreate: 'sales.credit_notes.create',
} as const;
