<?php

namespace Modules\Document\Infrastructure\Persistence\Eloquent\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;
use Modules\Document\Infrastructure\Persistence\Eloquent\Seeders\Support\DocumentSeedCatalog;

class DocumentModuleSeeder extends Seeder
{
    public function run(): void
    {
        $this->call([
            DocumentTenantSeeder::class,
            DocumentTypesSeeder::class,
            ItemTypesSeeder::class,
            DocumentDefinitionsSeeder::class,
            ItemDefinitionsSeeder::class,
            DocumentWorkflowsSeeder::class,
            WorkflowStepsSeeder::class,
            WorkflowTransitionsSeeder::class,
            DocumentSequencesSeeder::class,
        ]);

        $this->seedTemplatesAndSampleRecord();
    }

    private function seedTemplatesAndSampleRecord(): void
    {
        if (! Schema::hasTable('document_templates') || ! Schema::hasTable('documents')) {
            return;
        }

        DB::transaction(function (): void {
            $tenantId = (int) DB::table('tenants')->where('code', DocumentSeedCatalog::defaultTenantCode())->value('id');
            if ($tenantId < 1) {
                return;
            }

            $organizationUnitId = DB::table('organization_units')->where('tenant_id', $tenantId)->orderBy('id')->value('id');
            $documentTypes = DB::table('document_types')->where('tenant_id', $tenantId)->pluck('id', 'code');
            $now = now();

            foreach ($documentTypes as $code => $documentTypeId) {
                DB::table('document_templates')->updateOrInsert(
                    ['tenant_id' => $tenantId, 'template_code' => 'TPL-' . strtoupper((string) $code)],
                    [
                        'organization_unit_id' => $organizationUnitId,
                        'document_type_id' => $documentTypeId,
                        'template_name' => ucwords(str_replace('_', ' ', (string) $code)) . ' Template',
                        'layout_type' => 'html',
                        'header_content' => '<header><strong>{{document_number}}</strong></header>',
                        'body_content' => '<h1>{{document_title}}</h1><section>{{document_body}}</section>',
                        'footer_content' => '<footer>Generated by Document module</footer>',
                        'is_active' => true,
                        'updated_at' => $now,
                        'created_at' => $now,
                    ],
                );
            }

            $genericTypeId = (int) ($documentTypes['GENERIC'] ?? 0);
            if ($genericTypeId < 1) {
                return;
            }

            DB::table('documents')->updateOrInsert(
                ['tenant_id' => $tenantId, 'document_number' => 'DOC-SAMPLE-00001'],
                [
                    'organization_unit_id' => $organizationUnitId,
                    'document_type_id' => $genericTypeId,
                    'document_definition_id' => DB::table('document_definitions')
                        ->where('tenant_id', $tenantId)
                        ->where('document_type_id', $genericTypeId)
                        ->value('id'),
                    'status' => 'draft',
                    'version' => 1,
                    'source_module' => 'core',
                    'source_type' => 'sample',
                    'source_id' => null,
                    'source_reference' => 'SAMPLE',
                    'title' => 'Sample Core Document',
                    'document_date' => now()->toDateString(),
                    'due_date' => null,
                    'effective_date' => null,
                    'expiry_date' => null,
                    'subtotal' => 0,
                    'discount_total' => 0,
                    'tax_total' => 0,
                    'grand_total' => 0,
                    'notes' => 'Sample document record for real Document UI testing.',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
            );
        }, 3);
    }
}
