<?php

declare(strict_types=1);

use Modules\VehicleRental\Application\Repositories\VehicleRentalLesseeAgreementCreditNoteRepositoryInterface;
use Modules\VehicleRental\Application\Repositories\VehicleRentalLesseeAgreementDebitNoteRepositoryInterface;
use Modules\VehicleRental\Application\Repositories\VehicleRentalLesseeAgreementRepositoryInterface;
use Modules\VehicleRental\Application\Repositories\VehicleRentalLesseeRunningChartRepositoryInterface;
use Modules\VehicleRental\Application\Repositories\VehicleRentalLessorAgreementCreditNoteRepositoryInterface;
use Modules\VehicleRental\Application\Repositories\VehicleRentalLessorAgreementDebitNoteRepositoryInterface;
use Modules\VehicleRental\Application\Repositories\VehicleRentalLessorAgreementRepositoryInterface;
use Modules\VehicleRental\Application\Repositories\VehicleRentalLessorRunningChartRepositoryInterface;

return [
    'precision' => [
        'scale' => 4,
    ],

    'agreement_statuses' => ['draft', 'active', 'completed', 'cancelled'],
    'agreement_types' => ['daily', 'weekly', 'monthly', 'per_km', 'custom'],

    'calculated_columns' => [
        'row_version',
        'km_travelled',
        'debit_note_total',
        'credit_note_total',
    ],

    'decimal_columns' => [
        'daily_rate',
        'weekly_rate',
        'monthly_rate',
        'rate_per_km',
        'excess_km_rate',
        'maximum_number_of_km',
        'driver_salary',
        'working_hours_per_weekday',
        'working_hours_per_saturday',
        'working_hours_per_sunday',
        'normal_ot_rate_per_hour',
        'double_ot_rate_per_hour',
        'driver_night_out_allowance',
        'driver_outstation_allowance',
        'start_km',
        'end_km',
        'km_travelled',
        'hours_used',
        'driver_hours_normal',
        'driver_hours_ot',
        'driver_hours_double_ot',
        'other_charges',
        'garage_mileage',
        'debit_note_total',
        'credit_note_total',
        'amount',
    ],

    'immutable' => [
        'lessor_agreements' => [
            'status_column' => 'status',
            'statuses' => ['completed', 'cancelled'],
        ],
        'lessee_agreements' => [
            'status_column' => 'status',
            'statuses' => ['completed', 'cancelled'],
        ],
    ],

    'resources' => [
        'lessor_agreements' => [
            'repository' => VehicleRentalLessorAgreementRepositoryInterface::class,
            'label' => 'Vehicle rental lessor agreement',
            'rules' => [
                'row_version' => ['nullable', 'integer', 'min:1'],
                'organization_unit_id' => ['nullable', 'integer', 'exists:organization_units,id'],
                'agreement_number' => ['required', 'string', 'max:255'],
                'lessor_id' => ['required', 'integer', 'exists:suppliers,id'],
                'vehicle_id' => ['required', 'integer', 'exists:vehicles,id'],
                'agreement_type' => ['required', 'string', 'max:255'],
                'agreement_date' => ['required', 'date'],
                'start_date' => ['required', 'date'],
                'end_date' => ['nullable', 'date', 'after_or_equal:start_date'],
                'daily_rate' => ['nullable', 'numeric', 'min:0'],
                'weekly_rate' => ['nullable', 'numeric', 'min:0'],
                'monthly_rate' => ['nullable', 'numeric', 'min:0'],
                'rate_per_km' => ['nullable', 'numeric', 'min:0'],
                'excess_km_rate' => ['nullable', 'numeric', 'min:0'],
                'maximum_number_of_km' => ['nullable', 'numeric', 'min:0'],
                'start_odometer' => ['nullable', 'integer', 'min:0'],
                'end_odometer' => ['nullable', 'integer', 'min:0'],
                'driver_included' => ['nullable', 'boolean'],
                'driver_salary' => ['nullable', 'numeric', 'min:0'],
                'working_hours_per_weekday' => ['nullable', 'numeric', 'min:0'],
                'working_hours_per_saturday' => ['nullable', 'numeric', 'min:0'],
                'working_hours_per_sunday' => ['nullable', 'numeric', 'min:0'],
                'normal_ot_rate_per_hour' => ['nullable', 'numeric', 'min:0'],
                'double_ot_rate_per_hour' => ['nullable', 'numeric', 'min:0'],
                'driver_night_out_allowance' => ['nullable', 'numeric', 'min:0'],
                'driver_outstation_allowance' => ['nullable', 'numeric', 'min:0'],
                'status' => ['nullable', 'string', 'max:255'],
                'notes' => ['nullable', 'string'],
                'rental_income_account_id' => ['nullable', 'integer', 'exists:accounts,id'],
                'rental_expense_account_id' => ['nullable', 'integer', 'exists:accounts,id'],
                'excess_km_income_account_id' => ['nullable', 'integer', 'exists:accounts,id'],
                'driver_expense_account_id' => ['nullable', 'integer', 'exists:accounts,id'],
                'created_by' => ['nullable', 'integer'],
                'updated_by' => ['nullable', 'integer'],
                'metadata' => ['nullable', 'array'],
            ],
        ],
        'lessee_agreements' => [
            'repository' => VehicleRentalLesseeAgreementRepositoryInterface::class,
            'label' => 'Vehicle rental lessee agreement',
            'rules' => [
                'row_version' => ['nullable', 'integer', 'min:1'],
                'organization_unit_id' => ['nullable', 'integer', 'exists:organization_units,id'],
                'agreement_number' => ['required', 'string', 'max:255'],
                'lessee_id' => ['required', 'integer', 'exists:customers,id'],
                'vehicle_id' => ['required', 'integer', 'exists:vehicles,id'],
                'agreement_type' => ['required', 'string', 'max:255'],
                'agreement_date' => ['required', 'date'],
                'start_date' => ['required', 'date'],
                'end_date' => ['nullable', 'date', 'after_or_equal:start_date'],
                'daily_rate' => ['nullable', 'numeric', 'min:0'],
                'weekly_rate' => ['nullable', 'numeric', 'min:0'],
                'monthly_rate' => ['nullable', 'numeric', 'min:0'],
                'rate_per_km' => ['nullable', 'numeric', 'min:0'],
                'excess_km_rate' => ['nullable', 'numeric', 'min:0'],
                'maximum_number_of_km' => ['nullable', 'numeric', 'min:0'],
                'start_odometer' => ['nullable', 'integer', 'min:0'],
                'end_odometer' => ['nullable', 'integer', 'min:0'],
                'driver_included' => ['nullable', 'boolean'],
                'driver_salary' => ['nullable', 'numeric', 'min:0'],
                'working_hours_per_weekday' => ['nullable', 'numeric', 'min:0'],
                'working_hours_per_saturday' => ['nullable', 'numeric', 'min:0'],
                'working_hours_per_sunday' => ['nullable', 'numeric', 'min:0'],
                'normal_ot_rate_per_hour' => ['nullable', 'numeric', 'min:0'],
                'double_ot_rate_per_hour' => ['nullable', 'numeric', 'min:0'],
                'driver_night_out_allowance' => ['nullable', 'numeric', 'min:0'],
                'driver_outstation_allowance' => ['nullable', 'numeric', 'min:0'],
                'status' => ['nullable', 'string', 'max:255'],
                'notes' => ['nullable', 'string'],
                'rental_income_account_id' => ['nullable', 'integer', 'exists:accounts,id'],
                'rental_expense_account_id' => ['nullable', 'integer', 'exists:accounts,id'],
                'excess_km_income_account_id' => ['nullable', 'integer', 'exists:accounts,id'],
                'driver_expense_account_id' => ['nullable', 'integer', 'exists:accounts,id'],
                'created_by' => ['nullable', 'integer'],
                'updated_by' => ['nullable', 'integer'],
                'metadata' => ['nullable', 'array'],
            ],
        ],
        'lessor_running_charts' => [
            'repository' => VehicleRentalLessorRunningChartRepositoryInterface::class,
            'label' => 'Vehicle rental lessor running chart',
            'rules' => [
                'row_version' => ['nullable', 'integer', 'min:1'],
                'organization_unit_id' => ['nullable', 'integer', 'exists:organization_units,id'],
                'lessor_agreement_id' => ['required', 'integer', 'exists:vehicle_rental_lessor_agreements,id'],
                'lessee_agreement_id' => ['nullable', 'integer', 'exists:vehicle_rental_lessee_agreements,id'],
                'driver_id' => ['nullable', 'integer', 'exists:employees,id'],
                'log_date' => ['required', 'date'],
                'start_km' => ['nullable', 'numeric', 'min:0'],
                'end_km' => ['nullable', 'numeric', 'min:0'],
                'start_time' => ['nullable', 'date_format:H:i:s'],
                'end_time' => ['nullable', 'date_format:H:i:s'],
                'hours_used' => ['nullable', 'numeric', 'min:0'],
                'driver_hours_normal' => ['nullable', 'numeric', 'min:0'],
                'driver_hours_ot' => ['nullable', 'numeric', 'min:0'],
                'driver_hours_double_ot' => ['nullable', 'numeric', 'min:0'],
                'night_outs' => ['nullable', 'integer', 'min:0'],
                'other_charges' => ['nullable', 'numeric', 'min:0'],
                'garage_mileage' => ['nullable', 'numeric', 'min:0'],
                'particulars' => ['nullable', 'string'],
                'notes' => ['nullable', 'string'],
                'created_by' => ['nullable', 'integer'],
                'metadata' => ['nullable', 'array'],
            ],
        ],
        'lessee_running_charts' => [
            'repository' => VehicleRentalLesseeRunningChartRepositoryInterface::class,
            'label' => 'Vehicle rental lessee running chart',
            'rules' => [
                'row_version' => ['nullable', 'integer', 'min:1'],
                'organization_unit_id' => ['nullable', 'integer', 'exists:organization_units,id'],
                'lessee_agreement_id' => ['required', 'integer', 'exists:vehicle_rental_lessee_agreements,id'],
                'lessor_agreement_id' => ['nullable', 'integer', 'exists:vehicle_rental_lessor_agreements,id'],
                'driver_id' => ['nullable', 'integer', 'exists:employees,id'],
                'log_date' => ['required', 'date'],
                'start_km' => ['nullable', 'numeric', 'min:0'],
                'end_km' => ['nullable', 'numeric', 'min:0'],
                'start_time' => ['nullable', 'date_format:H:i:s'],
                'end_time' => ['nullable', 'date_format:H:i:s'],
                'hours_used' => ['nullable', 'numeric', 'min:0'],
                'driver_hours_normal' => ['nullable', 'numeric', 'min:0'],
                'driver_hours_ot' => ['nullable', 'numeric', 'min:0'],
                'driver_hours_double_ot' => ['nullable', 'numeric', 'min:0'],
                'night_outs' => ['nullable', 'integer', 'min:0'],
                'other_charges' => ['nullable', 'numeric', 'min:0'],
                'garage_mileage' => ['nullable', 'numeric', 'min:0'],
                'particulars' => ['nullable', 'string'],
                'notes' => ['nullable', 'string'],
                'created_by' => ['nullable', 'integer'],
                'metadata' => ['nullable', 'array'],
            ],
        ],
        'lessor_credit_notes' => [
            'repository' => VehicleRentalLessorAgreementCreditNoteRepositoryInterface::class,
            'label' => 'Vehicle rental lessor credit note',
            'rules' => [
                'row_version' => ['nullable', 'integer', 'min:1'],
                'organization_unit_id' => ['nullable', 'integer', 'exists:organization_units,id'],
                'lessor_agreement_id' => ['required', 'integer', 'exists:vehicle_rental_lessor_agreements,id'],
                'name' => ['required', 'string', 'max:255'],
                'reference' => ['nullable', 'string', 'max:255'],
                'description' => ['nullable', 'string'],
                'account_id' => ['nullable', 'integer', 'exists:accounts,id'],
                'amount' => ['required', 'numeric', 'min:0'],
                'entry_date' => ['required', 'date'],
                'created_by' => ['nullable', 'integer'],
                'metadata' => ['nullable', 'array'],
            ],
        ],
        'lessor_debit_notes' => [
            'repository' => VehicleRentalLessorAgreementDebitNoteRepositoryInterface::class,
            'label' => 'Vehicle rental lessor debit note',
            'rules' => [
                'row_version' => ['nullable', 'integer', 'min:1'],
                'organization_unit_id' => ['nullable', 'integer', 'exists:organization_units,id'],
                'lessor_agreement_id' => ['required', 'integer', 'exists:vehicle_rental_lessor_agreements,id'],
                'name' => ['required', 'string', 'max:255'],
                'reference' => ['nullable', 'string', 'max:255'],
                'description' => ['nullable', 'string'],
                'account_id' => ['nullable', 'integer', 'exists:accounts,id'],
                'amount' => ['required', 'numeric', 'min:0'],
                'entry_date' => ['required', 'date'],
                'created_by' => ['nullable', 'integer'],
                'metadata' => ['nullable', 'array'],
            ],
        ],
        'lessee_credit_notes' => [
            'repository' => VehicleRentalLesseeAgreementCreditNoteRepositoryInterface::class,
            'label' => 'Vehicle rental lessee credit note',
            'rules' => [
                'row_version' => ['nullable', 'integer', 'min:1'],
                'organization_unit_id' => ['nullable', 'integer', 'exists:organization_units,id'],
                'lessee_agreement_id' => ['required', 'integer', 'exists:vehicle_rental_lessee_agreements,id'],
                'name' => ['required', 'string', 'max:255'],
                'reference' => ['nullable', 'string', 'max:255'],
                'description' => ['nullable', 'string'],
                'account_id' => ['nullable', 'integer', 'exists:accounts,id'],
                'amount' => ['required', 'numeric', 'min:0'],
                'entry_date' => ['required', 'date'],
                'created_by' => ['nullable', 'integer'],
                'metadata' => ['nullable', 'array'],
            ],
        ],
        'lessee_debit_notes' => [
            'repository' => VehicleRentalLesseeAgreementDebitNoteRepositoryInterface::class,
            'label' => 'Vehicle rental lessee debit note',
            'rules' => [
                'row_version' => ['nullable', 'integer', 'min:1'],
                'organization_unit_id' => ['nullable', 'integer', 'exists:organization_units,id'],
                'lessee_agreement_id' => ['required', 'integer', 'exists:vehicle_rental_lessee_agreements,id'],
                'name' => ['required', 'string', 'max:255'],
                'reference' => ['nullable', 'string', 'max:255'],
                'description' => ['nullable', 'string'],
                'account_id' => ['nullable', 'integer', 'exists:accounts,id'],
                'amount' => ['required', 'numeric', 'min:0'],
                'entry_date' => ['required', 'date'],
                'created_by' => ['nullable', 'integer'],
                'metadata' => ['nullable', 'array'],
            ],
        ],
    ],
];
