<?php

declare(strict_types=1);

use Modules\Finance\Application\Repositories\AccountRepositoryInterface;
use Modules\Finance\Application\Repositories\ApTransactionRepositoryInterface;
use Modules\Finance\Application\Repositories\ArTransactionRepositoryInterface;
use Modules\Finance\Application\Repositories\BankAccountRepositoryInterface;
use Modules\Finance\Application\Repositories\BankCategoryRuleRepositoryInterface;
use Modules\Finance\Application\Repositories\BankReconciliationRepositoryInterface;
use Modules\Finance\Application\Repositories\BankTransactionRepositoryInterface;
use Modules\Finance\Application\Repositories\BudgetLineRepositoryInterface;
use Modules\Finance\Application\Repositories\BudgetRepositoryInterface;
use Modules\Finance\Application\Repositories\CostCenterRepositoryInterface;
use Modules\Finance\Application\Repositories\FiscalPeriodRepositoryInterface;
use Modules\Finance\Application\Repositories\FiscalYearRepositoryInterface;
use Modules\Finance\Application\Repositories\JournalEntryLineRepositoryInterface;
use Modules\Finance\Application\Repositories\JournalEntryRepositoryInterface;
use Modules\Finance\Application\Repositories\PaymentTermRepositoryInterface;
use Modules\Finance\Application\Repositories\TaxGroupRepositoryInterface;
use Modules\Finance\Application\Repositories\TaxRateRepositoryInterface;
use Modules\Finance\Application\Repositories\TaxRuleRepositoryInterface;

return [
    'precision' => [
        'scale' => 4,
    ],

    'statuses' => [
        'fiscal' => ['OPEN', 'CLOSED', 'LOCKED'],
        'journal_entry' => ['DRAFT', 'POSTED', 'REVERSED'],
        'budget' => ['DRAFT', 'SUBMITTED', 'APPROVED', 'CLOSED'],
        'bank_transaction' => ['IMPORTED', 'CATEGORIZED', 'MATCHED', 'RECONCILED', 'EXCLUDED'],
        'bank_reconciliation' => ['DRAFT', 'IN_PROGRESS', 'COMPLETED', 'APPROVED'],
    ],

    'types' => [
        'account' => ['ASSET', 'LIABILITY', 'EQUITY', 'INCOME', 'EXPENSE'],
        'normal_balance' => ['DEBIT', 'CREDIT'],
        'period' => ['MONTH', 'QUARTER', 'YEAR'],
        'journal_entry' => ['MANUAL', 'AUTO', 'SYSTEM', 'OPENING', 'CLOSING', 'ADJUSTMENT'],
        'tax_rate' => ['PERCENTAGE', 'FIXED'],
        'bank_transaction' => ['DEBIT', 'CREDIT'],
    ],

    'immutable' => [
        'journal_entries' => [
            'status_column' => 'status',
            'statuses' => ['POSTED', 'REVERSED'],
        ],
        'journal_entry_lines' => [
            'after_create' => true,
        ],
    ],

    'resources' => [
        'accounts' => [
            'repository' => AccountRepositoryInterface::class,
            'recalculate' => null,
            'rules' => [
                'parent_id' => ['nullable', 'integer', 'exists:accounts,id'],
                'organization_unit_id' => ['nullable', 'integer', 'exists:organization_units,id'],
                'code' => ['required', 'string', 'max:255'],
                'name' => ['required', 'string', 'max:255'],
                'type' => ['required', 'string'],
                'normal_balance' => ['required', 'string'],
                'is_control_account' => ['nullable', 'boolean'],
                'is_bank_account' => ['nullable', 'boolean'],
                'is_cash_account' => ['nullable', 'boolean'],
                'is_system' => ['nullable', 'boolean'],
                'currency_id' => ['nullable', 'integer', 'exists:currencies,id'],
                'description' => ['nullable', 'string'],
                'is_active' => ['nullable', 'boolean'],
                'allows_manual_posting' => ['nullable', 'boolean'],
                'path' => ['nullable', 'string', 'max:255'],
                'depth' => ['nullable', 'integer', 'min:0'],
                'metadata' => ['nullable', 'array'],
            ],
        ],
        'fiscal_years' => [
            'repository' => FiscalYearRepositoryInterface::class,
            'rules' => [
                'organization_unit_id' => ['nullable', 'integer', 'exists:organization_units,id'],
                'name' => ['required', 'string', 'max:255'],
                'start_date' => ['required', 'date'],
                'end_date' => ['required', 'date', 'after_or_equal:start_date'],
                'status' => ['nullable', 'string'],
                'is_current' => ['nullable', 'boolean'],
                'created_by' => ['nullable', 'integer'],
                'metadata' => ['nullable', 'array'],
            ],
        ],
        'fiscal_periods' => [
            'repository' => FiscalPeriodRepositoryInterface::class,
            'rules' => [
                'organization_unit_id' => ['nullable', 'integer', 'exists:organization_units,id'],
                'fiscal_year_id' => ['required', 'integer', 'exists:fiscal_years,id'],
                'period_number' => ['required', 'integer', 'min:1'],
                'name' => ['required', 'string', 'max:255'],
                'start_date' => ['required', 'date'],
                'end_date' => ['required', 'date', 'after_or_equal:start_date'],
                'status' => ['nullable', 'string'],
                'period_type' => ['nullable', 'string'],
                'created_by' => ['nullable', 'integer'],
                'metadata' => ['nullable', 'array'],
            ],
        ],
        'payment_terms' => [
            'repository' => PaymentTermRepositoryInterface::class,
            'rules' => [
                'organization_unit_id' => ['nullable', 'integer', 'exists:organization_units,id'],
                'name' => ['required', 'string', 'max:255'],
                'description' => ['nullable', 'string'],
                'due_days' => ['nullable', 'integer', 'min:0'],
                'discount_days' => ['nullable', 'integer', 'min:0'],
                'discount_rate' => ['nullable', 'numeric', 'min:0'],
                'payment_type' => ['nullable', 'string', 'max:255'],
                'is_default' => ['nullable', 'boolean'],
                'is_active' => ['nullable', 'boolean'],
                'created_by' => ['nullable', 'integer'],
                'metadata' => ['nullable', 'array'],
            ],
        ],
        'tax_groups' => [
            'repository' => TaxGroupRepositoryInterface::class,
            'rules' => [
                'organization_unit_id' => ['nullable', 'integer', 'exists:organization_units,id'],
                'name' => ['required', 'string', 'max:255'],
                'description' => ['nullable', 'string'],
                'is_active' => ['nullable', 'boolean'],
                'created_by' => ['nullable', 'integer'],
                'metadata' => ['nullable', 'array'],
            ],
        ],
        'tax_rates' => [
            'repository' => TaxRateRepositoryInterface::class,
            'rules' => [
                'organization_unit_id' => ['nullable', 'integer', 'exists:organization_units,id'],
                'tax_group_id' => ['required', 'integer', 'exists:tax_groups,id'],
                'name' => ['required', 'string', 'max:255'],
                'type' => ['nullable', 'string'],
                'rate' => ['required', 'numeric'],
                'account_id' => ['nullable', 'integer', 'exists:accounts,id'],
                'is_compound' => ['nullable', 'boolean'],
                'is_active' => ['nullable', 'boolean'],
                'valid_from' => ['nullable', 'date'],
                'valid_to' => ['nullable', 'date', 'after_or_equal:valid_from'],
                'created_by' => ['nullable', 'integer'],
                'metadata' => ['nullable', 'array'],
            ],
        ],
        'tax_rules' => [
            'repository' => TaxRuleRepositoryInterface::class,
            'rules' => [
                'organization_unit_id' => ['nullable', 'integer', 'exists:organization_units,id'],
                'tax_group_id' => ['required', 'integer', 'exists:tax_groups,id'],
                'item_category_id' => ['nullable', 'integer', 'exists:item_categories,id'],
                'party_type' => ['nullable', 'string', 'max:255'],
                'region' => ['nullable', 'string', 'max:255'],
                'priority' => ['nullable', 'integer', 'min:0'],
                'is_active' => ['nullable', 'boolean'],
                'metadata' => ['nullable', 'array'],
            ],
        ],
        'cost_centers' => [
            'repository' => CostCenterRepositoryInterface::class,
            'rules' => [
                'organization_unit_id' => ['nullable', 'integer', 'exists:organization_units,id'],
                'parent_id' => ['nullable', 'integer', 'exists:cost_centers,id'],
                'code' => ['required', 'string', 'max:255'],
                'name' => ['required', 'string', 'max:255'],
                'description' => ['nullable', 'string'],
                'is_active' => ['nullable', 'boolean'],
                'path' => ['nullable', 'string', 'max:255'],
                'depth' => ['nullable', 'integer', 'min:0'],
                'created_by' => ['nullable', 'integer'],
                'metadata' => ['nullable', 'array'],
            ],
        ],
        'journal_entries' => [
            'repository' => JournalEntryRepositoryInterface::class,
            'rules' => [
                'organization_unit_id' => ['nullable', 'integer', 'exists:organization_units,id'],
                'fiscal_period_id' => ['nullable', 'integer', 'exists:fiscal_periods,id'],
                'entry_number' => ['required', 'string', 'max:255'],
                'entry_type' => ['nullable', 'string'],
                'reference_type' => ['nullable', 'string', 'max:255'],
                'reference_id' => ['nullable', 'integer'],
                'description' => ['nullable', 'string'],
                'entry_date' => ['required', 'date'],
                'posting_date' => ['nullable', 'date'],
                'status' => ['nullable', 'string'],
                'created_by' => ['nullable', 'integer'],
                'metadata' => ['nullable', 'array'],
            ],
        ],
        'journal_entry_lines' => [
            'repository' => JournalEntryLineRepositoryInterface::class,
            'recalculate' => 'journal_line_base_amounts',
            'rules' => [
                'organization_unit_id' => ['nullable', 'integer', 'exists:organization_units,id'],
                'journal_entry_id' => ['required', 'integer', 'exists:journal_entries,id'],
                'account_id' => ['required', 'integer', 'exists:accounts,id'],
                'description' => ['nullable', 'string'],
                'debit_amount' => ['nullable', 'numeric', 'min:0'],
                'credit_amount' => ['nullable', 'numeric', 'min:0'],
                'currency_id' => ['nullable', 'integer', 'exists:currencies,id'],
                'exchange_rate' => ['nullable', 'numeric', 'min:0'],
                'base_debit_amount' => ['nullable', 'numeric', 'min:0'],
                'base_credit_amount' => ['nullable', 'numeric', 'min:0'],
                'cost_center_id' => ['nullable', 'integer', 'exists:cost_centers,id'],
                'tax_rate_id' => ['nullable', 'integer', 'exists:tax_rates,id'],
                'tax_amount' => ['nullable', 'numeric', 'min:0'],
                'line_number' => ['nullable', 'integer', 'min:1'],
                'metadata' => ['nullable', 'array'],
            ],
        ],
        'budgets' => [
            'repository' => BudgetRepositoryInterface::class,
            'rules' => [
                'organization_unit_id' => ['nullable', 'integer', 'exists:organization_units,id'],
                'name' => ['required', 'string', 'max:255'],
                'fiscal_year_id' => ['required', 'integer', 'exists:fiscal_years,id'],
                'budget_type' => ['nullable', 'string', 'max:255'],
                'start_date' => ['required', 'date'],
                'end_date' => ['required', 'date', 'after_or_equal:start_date'],
                'status' => ['nullable', 'string'],
                'notes' => ['nullable', 'string'],
                'created_by' => ['nullable', 'integer'],
                'approved_by' => ['nullable', 'integer'],
                'approved_at' => ['nullable', 'date'],
                'metadata' => ['nullable', 'array'],
            ],
        ],
        'budget_lines' => [
            'repository' => BudgetLineRepositoryInterface::class,
            'recalculate' => 'budget_line_total',
            'rules' => [
                'organization_unit_id' => ['nullable', 'integer', 'exists:organization_units,id'],
                'budget_id' => ['required', 'integer', 'exists:budgets,id'],
                'account_id' => ['required', 'integer', 'exists:accounts,id'],
                'cost_center_id' => ['nullable', 'integer', 'exists:cost_centers,id'],
                'period_1_amount' => ['nullable', 'numeric'],
                'period_2_amount' => ['nullable', 'numeric'],
                'period_3_amount' => ['nullable', 'numeric'],
                'period_4_amount' => ['nullable', 'numeric'],
                'period_5_amount' => ['nullable', 'numeric'],
                'period_6_amount' => ['nullable', 'numeric'],
                'period_7_amount' => ['nullable', 'numeric'],
                'period_8_amount' => ['nullable', 'numeric'],
                'period_9_amount' => ['nullable', 'numeric'],
                'period_10_amount' => ['nullable', 'numeric'],
                'period_11_amount' => ['nullable', 'numeric'],
                'period_12_amount' => ['nullable', 'numeric'],
                'notes' => ['nullable', 'string'],
                'metadata' => ['nullable', 'array'],
            ],
        ],
        'ap_transactions' => [
            'repository' => ApTransactionRepositoryInterface::class,
            'rules' => [
                'organization_unit_id' => ['nullable', 'integer', 'exists:organization_units,id'],
                'party_type' => ['nullable', 'string', 'max:255'],
                'party_id' => ['nullable', 'integer'],
                'account_id' => ['required', 'integer', 'exists:accounts,id'],
                'transaction_type' => ['required', 'string', 'max:255'],
                'reference_type' => ['nullable', 'string', 'max:255'],
                'reference_id' => ['nullable', 'integer'],
                'debit_amount' => ['nullable', 'numeric', 'min:0'],
                'credit_amount' => ['nullable', 'numeric', 'min:0'],
                'balance_after' => ['nullable', 'numeric'],
                'transaction_date' => ['required', 'date'],
                'due_date' => ['nullable', 'date'],
                'currency_id' => ['nullable', 'integer', 'exists:currencies,id'],
                'exchange_rate' => ['nullable', 'numeric', 'min:0'],
                'is_reconciled' => ['nullable', 'boolean'],
                'metadata' => ['nullable', 'array'],
            ],
        ],
        'ar_transactions' => [
            'repository' => ArTransactionRepositoryInterface::class,
            'rules' => [
                'organization_unit_id' => ['nullable', 'integer', 'exists:organization_units,id'],
                'party_type' => ['nullable', 'string', 'max:255'],
                'party_id' => ['nullable', 'integer'],
                'account_id' => ['required', 'integer', 'exists:accounts,id'],
                'transaction_type' => ['required', 'string', 'max:255'],
                'reference_type' => ['nullable', 'string', 'max:255'],
                'reference_id' => ['nullable', 'integer'],
                'debit_amount' => ['nullable', 'numeric', 'min:0'],
                'credit_amount' => ['nullable', 'numeric', 'min:0'],
                'balance_after' => ['nullable', 'numeric'],
                'transaction_date' => ['required', 'date'],
                'due_date' => ['nullable', 'date'],
                'currency_id' => ['nullable', 'integer', 'exists:currencies,id'],
                'exchange_rate' => ['nullable', 'numeric', 'min:0'],
                'is_reconciled' => ['nullable', 'boolean'],
                'metadata' => ['nullable', 'array'],
            ],
        ],
        'bank_accounts' => [
            'repository' => BankAccountRepositoryInterface::class,
            'rules' => [
                'organization_unit_id' => ['nullable', 'integer', 'exists:organization_units,id'],
                'name' => ['required', 'string', 'max:255'],
                'bank_name' => ['required', 'string', 'max:255'],
                'account_number' => ['required', 'string', 'max:255'],
                'routing_number' => ['nullable', 'string', 'max:255'],
                'iban' => ['nullable', 'string', 'max:255'],
                'swift_bic' => ['nullable', 'string', 'max:255'],
                'currency_id' => ['nullable', 'integer', 'exists:currencies,id'],
                'account_id' => ['required', 'integer', 'exists:accounts,id'],
                'opening_balance' => ['nullable', 'numeric'],
                'current_balance' => ['nullable', 'numeric'],
                'last_reconciled_at' => ['nullable', 'date'],
                'last_reconciled_balance' => ['nullable', 'numeric'],
                'feed_provider' => ['nullable', 'string', 'max:255'],
                'feed_credentials_enc' => ['nullable', 'string'],
                'is_active' => ['nullable', 'boolean'],
                'created_by' => ['nullable', 'integer'],
                'metadata' => ['nullable', 'array'],
            ],
        ],
        'bank_category_rules' => [
            'repository' => BankCategoryRuleRepositoryInterface::class,
            'rules' => [
                'organization_unit_id' => ['nullable', 'integer', 'exists:organization_units,id'],
                'bank_account_id' => ['nullable', 'integer', 'exists:bank_accounts,id'],
                'name' => ['required', 'string', 'max:255'],
                'priority' => ['nullable', 'integer', 'min:0'],
                'match_type' => ['nullable', 'string', 'max:255'],
                'match_value' => ['required', 'string', 'max:255'],
                'conditions' => ['nullable', 'array'],
                'account_id' => ['required', 'integer', 'exists:accounts,id'],
                'description_template' => ['nullable', 'string', 'max:255'],
                'is_active' => ['nullable', 'boolean'],
                'created_by' => ['nullable', 'integer'],
                'metadata' => ['nullable', 'array'],
            ],
        ],
        'bank_transactions' => [
            'repository' => BankTransactionRepositoryInterface::class,
            'rules' => [
                'organization_unit_id' => ['nullable', 'integer', 'exists:organization_units,id'],
                'bank_account_id' => ['required', 'integer', 'exists:bank_accounts,id'],
                'external_id' => ['nullable', 'string', 'max:255'],
                'transaction_date' => ['required', 'date'],
                'value_date' => ['nullable', 'date'],
                'description' => ['required', 'string', 'max:255'],
                'amount' => ['required', 'numeric'],
                'type' => ['nullable', 'string'],
                'balance' => ['nullable', 'numeric'],
                'status' => ['nullable', 'string'],
                'matched_journal_entry_id' => ['nullable', 'integer', 'exists:journal_entries,id'],
                'category_rule_id' => ['nullable', 'integer', 'exists:bank_category_rules,id'],
                'created_by' => ['nullable', 'integer'],
                'metadata' => ['nullable', 'array'],
            ],
        ],
        'bank_reconciliations' => [
            'repository' => BankReconciliationRepositoryInterface::class,
            'recalculate' => 'bank_reconciliation_difference',
            'rules' => [
                'organization_unit_id' => ['nullable', 'integer', 'exists:organization_units,id'],
                'bank_account_id' => ['required', 'integer', 'exists:bank_accounts,id'],
                'period_start' => ['required', 'date'],
                'period_end' => ['required', 'date', 'after_or_equal:period_start'],
                'opening_balance' => ['required', 'numeric'],
                'closing_balance' => ['required', 'numeric'],
                'statement_balance' => ['required', 'numeric'],
                'status' => ['nullable', 'string'],
                'completed_by' => ['nullable', 'integer', 'exists:users,id'],
                'completed_at' => ['nullable', 'date'],
                'approved_by' => ['nullable', 'integer', 'exists:users,id'],
                'approved_at' => ['nullable', 'date'],
                'notes' => ['nullable', 'string'],
                'created_by' => ['nullable', 'integer'],
                'metadata' => ['nullable', 'array'],
            ],
        ],
    ],
];
