export const routePaths = {
    customer: '/customers',
    dashboard: '/dashboard',
    document: '/documents',
    finance: '/finance/accounts',
    hr: '/hr/employees',
    inventory: '/inventory/stock-levels',
    item: '/items',
    payment: '/payments',
    pricing: '/pricing',
    purchase: '/purchase/orders',
    sales: '/sales/orders',
    settings: '/settings',
    supplier: '/suppliers',
    uom: '/uom',
    vehicleRental: '/vehicle-rental/agreements',
    vehicleService: '/vehicle-service/job-cards',
    vehicleServiceCreate: '/vehicle-service/job-cards/create',
    vehicleServiceCrew: '/vehicle-service/job-cards/create/crew-members',
    voucher: '/vouchers',
};
