export const routePaths = {
    customer: '/customers',
    dashboard: '/dashboard',
    finance: '/finance/accounts',
    hr: '/hr/employees',
    inventory: '/inventory/stock-levels',
    item: '/items',
    payment: '/payments',
    purchase: '/purchase/orders',
    settings: '/settings',
    supplier: '/suppliers',
    tenant: '/tenant',
    uom: '/uom',
    vehicle: '/vehicles',
    vehicleService: '/vehicle-service/job-cards',
    vehicleServiceCreate: '/vehicle-service/job-cards/create',
    vehicleServiceCrew: '/vehicle-service/job-cards/create/crew-members',
};
