export type MoneyValue = string | number;

export type PurchaseOrderStatus = 'draft' | 'confirmed' | 'partially_received' | 'received' | 'cancelled';
export type PurchaseInvoiceStatus = 'not_invoiced' | 'partially_invoiced' | 'closed';
export type GrnStatus = 'draft' | 'confirmed';
export type PurchaseReturnStatus = 'draft' | 'approved' | 'closed' | 'cancelled';
export type DiscountType = 'percentage' | 'fixed';

export type PurchaseOrderLineRecord = {
    id: number;
    tenant_id: number;
    organization_unit_id: number | null;
    purchase_order_id: number;
    item_id: number;
    variant_id: number | null;
    description: string | null;
    uom_id: number;
    ordered_qty: MoneyValue;
    received_qty: MoneyValue;
    rejected_qty: MoneyValue;
    invoiced_qty: MoneyValue;
    unit_price: MoneyValue;
    discount_type: DiscountType | null;
    discount_value: MoneyValue;
    discount_amount: MoneyValue;
    gross_amount: MoneyValue;
    line_total: MoneyValue;
    tax_group_id: number | null;
    tax_amount: MoneyValue;
    line_total_with_tax: MoneyValue;
    account_id: number | null;
    created_at: string;
    updated_at: string;
};

export type PurchaseOrderRecord = {
    id: number;
    tenant_id: number;
    row_version: number;
    organization_unit_id: number | null;
    supplier_id: number;
    warehouse_id: number;
    po_number: string;
    status: PurchaseOrderStatus;
    invoice_status: PurchaseInvoiceStatus;
    currency_id: number | null;
    exchange_rate: MoneyValue;
    order_date: string;
    expected_date: string | null;
    price_list_id: number | null;
    subtotal: MoneyValue;
    line_tax_total: MoneyValue;
    line_discount_total: MoneyValue;
    header_discount_type: DiscountType | null;
    header_discount_value: MoneyValue | null;
    header_discount_amount: MoneyValue;
    header_tax_group_id: number | null;
    header_tax_amount: MoneyValue;
    discount_total: MoneyValue;
    tax_total: MoneyValue;
    debit_note_total: MoneyValue;
    credit_note_total: MoneyValue;
    grand_total: MoneyValue;
    paid_amount: MoneyValue;
    balance: MoneyValue;
    notes: string | null;
    metadata: Record<string, unknown> | null;
    created_by: number | null;
    lines?: PurchaseOrderLineRecord[];
    purchase_order_lines?: PurchaseOrderLineRecord[];
    created_at: string;
    updated_at: string;
};

export type GrnLineRecord = {
    id: number;
    tenant_id: number;
    organization_unit_id: number | null;
    grn_header_id: number;
    purchase_order_line_id: number | null;
    item_id: number;
    variant_id: number | null;
    batch_id: number | null;
    serial_id: number | null;
    warehouse_id: number | null;
    location_id: number | null;
    description: string | null;
    uom_id: number;
    expected_qty: MoneyValue;
    received_qty: MoneyValue;
    rejected_qty: MoneyValue;
    invoiced_qty: MoneyValue;
    unit_price: MoneyValue;
    discount_type: DiscountType | null;
    discount_value: MoneyValue;
    discount_amount: MoneyValue;
    gross_amount: MoneyValue;
    line_total: MoneyValue;
    tax_group_id: number | null;
    tax_amount: MoneyValue;
    line_total_with_tax: MoneyValue;
    account_id: number | null;
};

export type GrnRecord = {
    id: number;
    tenant_id: number;
    row_version: number;
    organization_unit_id: number | null;
    supplier_id: number;
    warehouse_id: number;
    purchase_order_id: number | null;
    grn_number: string;
    status: GrnStatus;
    invoice_status: PurchaseInvoiceStatus;
    currency_id: number | null;
    exchange_rate: MoneyValue;
    received_date: string;
    price_list_id: number | null;
    subtotal: MoneyValue;
    discount_total: MoneyValue;
    tax_total: MoneyValue;
    grand_total: MoneyValue;
    notes: string | null;
    metadata: Record<string, unknown> | null;
    created_by: number | null;
    lines?: GrnLineRecord[];
    grn_lines?: GrnLineRecord[];
    created_at: string;
    updated_at: string;
};

export type PurchaseInvoiceRecord = {
    id: number;
    tenant_id: number;
    row_version: number;
    direction: 'inbound' | 'outbound';
    invoice_type: string;
    invoice_number: string;
    status: 'draft' | 'approved' | 'partially_paid' | 'paid' | 'disputed' | 'cancelled';
    party_type: string | null;
    party_id: number | null;
    invoice_date: string;
    due_date: string;
    currency_id: number | null;
    exchange_rate: MoneyValue;
    subtotal: MoneyValue;
    discount_total: MoneyValue;
    tax_total: MoneyValue;
    grand_total: MoneyValue;
    paid_amount: MoneyValue;
    balance: MoneyValue;
    journal_entry_id: number | null;
    created_at: string;
    updated_at: string;
};

export type PurchaseReturnLineRecord = {
    id: number;
    purchase_return_id: number;
    original_grn_line_id: number | null;
    original_purchase_order_line_id: number | null;
    item_id: number;
    variant_id: number | null;
    return_qty: MoneyValue;
    unit_price: MoneyValue;
    restocking_fee: MoneyValue;
    condition: string | null;
    disposition: string | null;
    line_total_with_tax: MoneyValue;
};

export type PurchaseReturnRecord = {
    id: number;
    tenant_id: number;
    row_version: number;
    organization_unit_id: number | null;
    supplier_id: number;
    original_purchase_order_id: number | null;
    original_grn_id: number | null;
    original_invoice_id: number | null;
    return_number: string;
    status: PurchaseReturnStatus;
    currency_id: number | null;
    exchange_rate: MoneyValue;
    return_date: string;
    return_reason: string | null;
    subtotal: MoneyValue;
    discount_total: MoneyValue;
    tax_total: MoneyValue;
    grand_total: MoneyValue;
    notes: string | null;
    metadata: Record<string, unknown> | null;
    lines?: PurchaseReturnLineRecord[];
    created_at: string;
    updated_at: string;
};

export type PurchaseOrderListFilters = {
    tenant_id?: number;
    supplier_id?: number;
    warehouse_id?: number;
    status?: string;
    order_date_from?: string;
    order_date_to?: string;
    per_page?: number;
    page?: number;
    sort?: string;
};

export type GrnListFilters = {
    tenant_id?: number;
    supplier_id?: number;
    warehouse_id?: number;
    purchase_order_id?: number;
    status?: string;
    per_page?: number;
    page?: number;
    sort?: string;
};

export type PurchaseInvoiceListFilters = {
    tenant_id?: number;
    direction?: 'inbound';
    party_id?: number;
    status?: string;
    invoice_number?: string;
    per_page?: number;
    page?: number;
    sort?: string;
};

export type PurchaseReturnListFilters = {
    tenant_id?: number;
    supplier_id?: number;
    status?: string;
    return_number?: string;
    per_page?: number;
    page?: number;
    sort?: string;
};

export type PurchaseOrderLinePayload = {
    id?: number;
    item_id: number;
    variant_id?: number | null;
    description?: string | null;
    uom_id: number;
    ordered_qty: number;
    received_qty?: number;
    rejected_qty?: number;
    invoiced_qty?: number;
    unit_price: number;
    discount_type?: DiscountType | null;
    discount_value?: number;
    discount_amount?: number;
    gross_amount?: number;
    line_total?: number;
    tax_group_id?: number | null;
    tax_amount?: number;
    line_total_with_tax?: number;
    account_id?: number | null;
};

export type PurchaseOrderPayload = {
    tenant_id: number;
    organization_unit_id?: number | null;
    supplier_id: number;
    warehouse_id: number;
    currency_id?: number | null;
    exchange_rate?: number | null;
    po_number?: string;
    order_date: string;
    expected_date?: string | null;
    price_list_id?: number | null;
    header_discount_type?: DiscountType | null;
    header_discount_value?: number | null;
    header_discount_amount?: number;
    header_tax_group_id?: number | null;
    header_tax_amount?: number;
    subtotal?: number;
    line_tax_total?: number;
    line_discount_total?: number;
    discount_total?: number;
    tax_total?: number;
    grand_total?: number;
    paid_amount?: number;
    balance?: number;
    notes?: string | null;
    metadata?: Record<string, unknown> | null;
    created_by?: number | null;
    lines?: PurchaseOrderLinePayload[];
};

export type GrnLinePayload = {
    id?: number;
    purchase_order_line_id?: number | null;
    item_id: number;
    variant_id?: number | null;
    batch_id?: number | null;
    serial_id?: number | null;
    warehouse_id?: number | null;
    location_id?: number | null;
    description?: string | null;
    uom_id: number;
    expected_qty?: number;
    received_qty: number;
    rejected_qty?: number;
    invoiced_qty?: number;
    unit_price: number;
    discount_type?: DiscountType | null;
    discount_value?: number;
    discount_amount?: number;
    gross_amount?: number;
    line_total?: number;
    tax_group_id?: number | null;
    tax_amount?: number;
    line_total_with_tax?: number;
    account_id?: number | null;
};

export type GrnPayload = {
    tenant_id: number;
    organization_unit_id?: number | null;
    supplier_id: number;
    warehouse_id: number;
    purchase_order_id?: number | null;
    grn_number?: string;
    status?: GrnStatus;
    currency_id?: number | null;
    exchange_rate?: number | null;
    received_date: string;
    price_list_id?: number | null;
    notes?: string | null;
    created_by?: number | null;
    lines?: GrnLinePayload[];
};

export type PurchaseReturnPayload = {
    tenant_id: number;
    organization_unit_id?: number | null;
    supplier_id: number;
    original_purchase_order_id?: number | null;
    original_grn_id?: number | null;
    original_invoice_id?: number | null;
    return_number?: string;
    currency_id?: number | null;
    exchange_rate?: number | null;
    return_date: string;
    return_reason?: string | null;
    notes?: string | null;
    created_by?: number | null;
    lines?: Array<{
        original_grn_line_id?: number | null;
        original_purchase_order_line_id?: number | null;
        item_id: number;
        variant_id?: number | null;
        warehouse_id?: number | null;
        location_id?: number | null;
        description?: string | null;
        uom_id: number;
        return_qty: number;
        unit_price: number;
        restocking_fee?: number;
        condition?: string | null;
        disposition?: string | null;
    }>;
};

export type PurchaseInvoicePayload = Record<string, unknown>;
export type PurchasePaymentPayload = Record<string, unknown>;
