import { useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { ModuleHeader } from '../../../layouts/components/ModuleHeader';
import { StatusBadge } from '../../../shared/components/business/StatusBadge';
import { DataTable } from '../../../shared/components/data/DataTable';
import { FormSection } from '../../../shared/components/forms/FormSection';
import { Button } from '../../../shared/components/ui/Button';
import { Card } from '../../../shared/components/ui/Card';
import { Input } from '../../../shared/components/ui/Input';
import { Select } from '../../../shared/components/ui/Select';
import { Tabs } from '../../../shared/components/ui/Tabs';
import { Textarea } from '../../../shared/components/ui/Textarea';
import { cn } from '../../../shared/utils/cn';
import { customers, jobLines, jobTypes, labourAssignments, serviceItems, servicePreview, supervisors, vehicles } from '../mock/vehicleServiceMock';
import type { JobLine, JobLineCategory } from '../types/vehicleService.types';

const tabs = [
    { label: 'Intake & Header', value: 'intake' },
    { label: 'Job Lines', value: 'lines' },
    { label: 'Labour & Assignment', value: 'labour' },
];

const lineGroups: Array<{ category: JobLineCategory; description: string; label: string }> = [
    { category: 'service', description: 'Service catalog selections that guide billing and labour.', label: 'Service Items' },
    { category: 'stock', description: 'Stock-affecting spare parts. Backend will preview availability and issue effects.', label: 'Spare Parts / Stock Items' },
    { category: 'non_inventory', description: 'Charges without stock ledger impact.', label: 'Non-Inventory Items' },
    { category: 'customer_supplied', description: 'Customer-owned items recorded for traceability only.', label: 'Customer-Supplied Items' },
    { category: 'external_service', description: 'Provider work that may create payables downstream.', label: 'External Services' },
    { category: 'combo', description: 'Bundles expanded by backend into allowed service, stock, and labour components.', label: 'Combo Items / Expanded Components' },
];

function options(list: Array<{ id: string; label: string }>) {
    return list.map((item) => ({ label: item.label, value: item.id }));
}

function Label({ children }: { children: string }) {
    return <label className="text-xs font-bold uppercase tracking-wide text-slate-500">{children}</label>;
}

function IntakeTab() {
    return (
        <div className="grid gap-5 xl:grid-cols-[1fr_320px]">
            <FormSection description="Capture the operational facts only. Backend will validate tenant, customer, vehicle, sequence, and workflow eligibility." title="Customer and vehicle intake">
                <div className="grid gap-4 md:grid-cols-2">
                    <div className="space-y-2">
                        <Label>Customer</Label>
                        <div className="flex gap-2">
                            <Select options={options(customers)} placeholder="Select customer" />
                            <Button variant="secondary">+</Button>
                        </div>
                    </div>
                    <div className="space-y-2">
                        <Label>Vehicle</Label>
                        <div className="flex gap-2">
                            <Select options={options(vehicles)} placeholder="Select vehicle" />
                            <Button variant="secondary">+</Button>
                        </div>
                    </div>
                    <div className="space-y-2">
                        <Label>Service advisor / supervisor</Label>
                        <Select options={options(supervisors)} />
                    </div>
                    <div className="space-y-2">
                        <Label>Job type</Label>
                        <Select options={options(jobTypes)} placeholder="Select job type" />
                    </div>
                    <div className="space-y-2">
                        <Label>Opened date</Label>
                        <Input type="date" />
                    </div>
                    <div className="space-y-2">
                        <Label>Expected completion</Label>
                        <Input type="datetime-local" />
                    </div>
                    <div className="space-y-2">
                        <Label>Odometer / mileage</Label>
                        <Input placeholder="Customer-entered reading" />
                    </div>
                    <div className="space-y-2">
                        <Label>Backend sequence preview</Label>
                        <Input readOnly value="Generated by backend after save" />
                    </div>
                    <div className="space-y-2 md:col-span-2">
                        <Label>Complaint / diagnosis / intake notes</Label>
                        <Textarea placeholder="Describe reported issue, visible condition, diagnosis notes, and customer instructions." />
                    </div>
                </div>
            </FormSection>

            <Card className="space-y-4 p-5">
                <div>
                    <p className="text-sm font-bold text-slate-950">Mock backend previews</p>
                    <p className="mt-1 text-sm text-slate-500">These values are display placeholders. Real values come from backend preview endpoints.</p>
                </div>
                <div className="space-y-3">
                    {servicePreview.map((item) => (
                        <div className="rounded-lg border border-slate-200 bg-slate-50 p-3" key={item.label}>
                            <p className="text-xs font-bold uppercase tracking-wide text-slate-400">{item.label}</p>
                            <p className="mt-1 text-sm font-semibold text-slate-800">{item.value}</p>
                        </div>
                    ))}
                </div>
            </Card>
        </div>
    );
}

function LineGroup({ group, rows }: { group: (typeof lineGroups)[number]; rows: JobLine[] }) {
    return (
        <Card className="p-5">
            <div className="mb-4 flex flex-col gap-3 md:flex-row md:items-start md:justify-between">
                <div>
                    <h2 className="text-base font-bold text-slate-950">{group.label}</h2>
                    <p className="mt-1 text-sm text-slate-500">{group.description}</p>
                </div>
                {group.category === 'customer_supplied' ? <StatusBadge status="No stock impact" /> : null}
            </div>
            <DataTable
                columns={[
                    { header: 'Description', key: 'description' },
                    { header: 'Qty', key: 'quantity', className: 'w-24' },
                    { header: 'Unit', key: 'unit', className: 'w-28' },
                    { header: 'Stock effect', key: 'stockImpact' },
                ]}
                getRowKey={(row) => row.id}
                rows={rows}
            />
        </Card>
    );
}

function LinesTab() {
    const grouped = useMemo(
        () =>
            lineGroups.map((group) => ({
                ...group,
                rows: jobLines.filter((line) => line.category === group.category),
            })),
        [],
    );

    return (
        <div className="space-y-5">
            <FormSection description="Add requested work and materials. Backend preview endpoints will resolve pricing, UOM conversion, stock availability, tax, discount, and invoice effects." title="Add job line">
                <div className="grid gap-4 md:grid-cols-[1.2fr_1fr_140px_120px]">
                    <Select options={options(serviceItems)} placeholder="Select service, item, provider work, or combo" />
                    <Input placeholder="User notes or customer reference" />
                    <Input placeholder="Quantity" />
                    <Button variant="blue">Add Line</Button>
                </div>
            </FormSection>
            {grouped.map((group) => (
                <LineGroup group={group} key={group.category} rows={group.rows} />
            ))}
        </div>
    );
}

function LabourTab() {
    return (
        <div className="grid gap-5 xl:grid-cols-[1fr_340px]">
            <Card className="p-5">
                <div className="mb-4">
                    <h2 className="text-base font-bold text-slate-950">Assigned labour</h2>
                    <p className="mt-1 text-sm text-slate-500">Technician share and incentive values are backend preview placeholders.</p>
                </div>
                <DataTable
                    columns={[
                        { header: 'Labour item', key: 'labourItem' },
                        { header: 'Employee', key: 'employee' },
                        { header: 'Role', key: 'role' },
                        { header: 'Share / incentive', key: 'shareRule' },
                    ]}
                    getRowKey={(row) => row.id}
                    rows={labourAssignments}
                />
            </Card>
            <FormSection description="Backend validates labour item, employee eligibility, supervisor rules, split/share logic, and incentive preview." title="Assign technician">
                <div className="space-y-4">
                    <div className="space-y-2">
                        <Label>Labour item</Label>
                        <Select options={options(serviceItems)} placeholder="Select labour item" />
                    </div>
                    <div className="space-y-2">
                        <Label>Technician / employee</Label>
                        <Select options={options(supervisors)} placeholder="Select employee" />
                    </div>
                    <div className="space-y-2">
                        <Label>Role</Label>
                        <Select
                            options={[
                                { label: 'Supervisor', value: 'supervisor' },
                                { label: 'Technician', value: 'technician' },
                                { label: 'Assistant', value: 'assistant' },
                            ]}
                        />
                    </div>
                    <div className="space-y-2">
                        <Label>Supervisor review</Label>
                        <Textarea placeholder="Review notes, internal instructions, or reassignment reason." />
                    </div>
                    <Button className="w-full" variant="blue">Add Assignment</Button>
                </div>
            </FormSection>
        </div>
    );
}

export function JobCardEditorPage({ mode = 'create' }: { mode?: 'create' | 'edit' }) {
    const [activeTab, setActiveTab] = useState('intake');

    return (
        <div className="mx-auto max-w-7xl space-y-6">
            <ModuleHeader
                actions={
                    <>
                        <Link to="/vehicle-service/job-cards">
                            <Button variant="secondary">Discard</Button>
                        </Link>
                        <Button>Save Draft</Button>
                        <Button variant="blue">Submit to Backend Preview</Button>
                    </>
                }
                subtitle="Build the job card from operational inputs. Backend services will own sequence, workflow, stock, pricing, invoice, payment, and labour calculations."
                title={mode === 'edit' ? 'Edit Job Card' : 'New Job Card'}
            />

            <Card className="p-5">
                <Tabs active={activeTab} items={tabs} onChange={setActiveTab} trailing={<span className="text-xs font-semibold text-slate-400">Draft workspace</span>} />
            </Card>

            <div className={cn(activeTab === 'intake' ? 'block' : 'hidden')}>
                <IntakeTab />
            </div>
            <div className={cn(activeTab === 'lines' ? 'block' : 'hidden')}>
                <LinesTab />
            </div>
            <div className={cn(activeTab === 'labour' ? 'block' : 'hidden')}>
                <LabourTab />
            </div>
        </div>
    );
}
