<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('orders', function (Blueprint $table) {
            // UUID primary key — generated by the domain, not the database
            $table->uuid('id')->primary();

            // Core domain columns
            $table->string('customer_id')->index();
            $table->string('status', 50)->default('pending')->index();

            // Money stored as minor units to avoid floating-point errors
            $table->unsignedBigInteger('total_amount_cents')->default(0);
            $table->char('total_currency', 3)->default('USD');

            // Domain timestamp (separate from ORM timestamps)
            $table->timestamp('placed_at')->nullable();

            $table->timestamps();
            $table->softDeletes();
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('orders');
    }
};
