<?php

namespace App\Http\Controllers\Api\V1;

use App\Http\Controllers\Controller;
use App\Services\InvoiceSchemeService;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;

class InvoiceSchemeController extends Controller
{
    public function __construct(
        private readonly InvoiceSchemeService $schemeService
    ) {}

    /**
     * GET /api/v1/invoice-schemes
     */
    public function index(Request $request): JsonResponse
    {
        abort_unless($request->user()?->can('invoice_schemes.view'), 403);

        $tenantId = $request->user()->tenant_id;
        $perPage = min((int) $request->query('per_page', 15), 100);

        return response()->json($this->schemeService->paginate($tenantId, $perPage));
    }

    /**
     * POST /api/v1/invoice-schemes
     */
    public function store(Request $request): JsonResponse
    {
        abort_unless($request->user()?->can('invoice_schemes.create'), 403);

        $validated = $request->validate([
            'name' => ['required', 'string', 'max:150'],
            'scheme_type' => ['nullable', 'string', 'in:purchase,sell,purchase_n_sell,expense,stock_adjustment,stock_transfer'],
            'prefix' => ['nullable', 'string', 'max:20'],
            'suffix' => ['nullable', 'string', 'max:20'],
            'start_number' => ['nullable', 'integer', 'min:1'],
            'number_of_digits' => ['nullable', 'integer', 'min:1', 'max:10'],
            'is_default' => ['nullable', 'boolean'],
        ]);

        $validated['tenant_id'] = $request->user()->tenant_id;

        return response()->json(
            ['data' => $this->schemeService->create($validated)],
            201
        );
    }

    /**
     * PUT /api/v1/invoice-schemes/{id}
     */
    public function update(Request $request, string $id): JsonResponse
    {
        abort_unless($request->user()?->can('invoice_schemes.edit'), 403);

        $validated = $request->validate([
            'name' => ['sometimes', 'string', 'max:150'],
            'scheme_type' => ['sometimes', 'string', 'in:purchase,sell,purchase_n_sell,expense,stock_adjustment,stock_transfer'],
            'prefix' => ['nullable', 'string', 'max:20'],
            'suffix' => ['nullable', 'string', 'max:20'],
            'start_number' => ['sometimes', 'integer', 'min:1'],
            'number_of_digits' => ['sometimes', 'integer', 'min:1', 'max:10'],
            'is_default' => ['sometimes', 'boolean'],
        ]);

        return response()->json(
            ['data' => $this->schemeService->update($id, $validated)]
        );
    }

    /**
     * DELETE /api/v1/invoice-schemes/{id}
     */
    public function destroy(Request $request, string $id): JsonResponse
    {
        abort_unless($request->user()?->can('invoice_schemes.delete'), 403);

        $this->schemeService->delete($id);

        return response()->json(null, 204);
    }

    /**
     * PATCH /api/v1/invoice-schemes/{id}/set-default
     */
    public function setDefault(Request $request, string $id): JsonResponse
    {
        abort_unless($request->user()?->can('invoice_schemes.edit'), 403);

        $tenantId = $request->user()->tenant_id;

        return response()->json(
            ['data' => $this->schemeService->setDefault($tenantId, $id)]
        );
    }

    /**
     * GET /api/v1/invoice-schemes/{id}/next-number
     * Preview the next reference number that would be generated by this scheme.
     */
    public function nextNumber(Request $request, string $id): JsonResponse
    {
        abort_unless($request->user()?->can('invoice_schemes.view'), 403);

        $tenantId = $request->user()->tenant_id;

        return response()->json([
            'data' => ['reference_number' => $this->schemeService->nextNumber($tenantId, $id)],
        ]);
    }
}
