flowchart LR

P[PARTIES]

PR[PRODUCTS]
PV[VARIANTS]
U[UOMS]
PU[PRODUCT_UOMS]

LOC[LOCATIONS]
ITEM[INVENTORY_ITEMS]
LEDGER[INVENTORY_LEDGER]

TRX[TRANSACTIONS]
TRXL[TRANSACTION_LINES]

PAY[PAYMENTS]

ACC[ACCOUNTS]
JE[JOURNAL_ENTRIES]
JL[JOURNAL_LINES]

P --> TRX
TRX --> TRXL
TRXL --> ITEM

PR --> PV
PV --> ITEM
PV --> PU
PU --> U

LOC --> ITEM
ITEM --> LEDGER

TRXL -.-> LEDGER

TRX --> PAY

JE --> JL
ACC --> JL

TRX -.-> JE
LEDGER -.-> JE