flowchart LR

%% MASTER
P[PARTIES]
PR[PRODUCTS]
PV[PRODUCT_VARIANTS]
U[UOMS]
PU[PRODUCT_UOMS]

PR --> PV
PV --> PU
PU --> U

%% INVENTORY
LOC[LOCATIONS]
ITEM[INVENTORY_ITEMS]
LEDGER[INVENTORY_LEDGER]

PV --> ITEM
LOC --> ITEM
ITEM --> LEDGER

%% TRANSACTIONS (UNIFIED)
TRX[TRANSACTIONS]
TRXL[TRANSACTION_LINES]

P --> TRX
TRX --> TRXL
TRXL --> ITEM

%% ACCOUNTING
ACC[ACCOUNTS]
JE[JOURNAL_ENTRIES]
JEL[JOURNAL_LINES]

JE --> JEL
ACC --> JEL

%% LINKS
TRXL -.-> LEDGER
TRXL -.-> JEL
LEDGER -.-> JEL