<?php

declare(strict_types=1);

use Modules\Inventory\Application\Repositories\BatchRepositoryInterface;
use Modules\Inventory\Application\Repositories\CycleCountHeaderRepositoryInterface;
use Modules\Inventory\Application\Repositories\CycleCountLineRepositoryInterface;
use Modules\Inventory\Application\Repositories\InventoryCostLayerRepositoryInterface;
use Modules\Inventory\Application\Repositories\PickingTaskRepositoryInterface;
use Modules\Inventory\Application\Repositories\PutAwayTaskRepositoryInterface;
use Modules\Inventory\Application\Repositories\ReceiptInspectionRepositoryInterface;
use Modules\Inventory\Application\Repositories\SerialRepositoryInterface;
use Modules\Inventory\Application\Repositories\StockAdjustmentLineRepositoryInterface;
use Modules\Inventory\Application\Repositories\StockAdjustmentRepositoryInterface;
use Modules\Inventory\Application\Repositories\StockLevelRepositoryInterface;
use Modules\Inventory\Application\Repositories\StockMovementRepositoryInterface;
use Modules\Inventory\Application\Repositories\StockReservationRepositoryInterface;
use Modules\Inventory\Application\Repositories\StockTransferLineRepositoryInterface;
use Modules\Inventory\Application\Repositories\StockTransferRepositoryInterface;
use Modules\Inventory\Application\Repositories\TraceLogRepositoryInterface;
use Modules\Inventory\Application\Repositories\TransferOrderLineRepositoryInterface;
use Modules\Inventory\Application\Repositories\TransferOrderRepositoryInterface;
use Modules\Inventory\Application\Repositories\ValuationConfigRepositoryInterface;

return [
    'precision' => [
        'scale' => 4,
    ],

    'defaults' => [
        'condition' => 'good',
        'valuation_method' => 'weighted_average',
        'allow_negative_stock' => false,
    ],

    'directions' => ['IN', 'OUT'],

    'movement_types' => [
        'OPENING_STOCK',
        'PURCHASE_RECEIPT',
        'PURCHASE_RETURN',
        'SALES_ISSUE',
        'SALES_RETURN',
        'STOCK_TRANSFER_IN',
        'STOCK_TRANSFER_OUT',
        'ADJUSTMENT_IN',
        'ADJUSTMENT_OUT',
        'PRODUCTION_CONSUMPTION',
        'PRODUCTION_OUTPUT',
        'SCRAP',
        'DAMAGE',
        'COUNT_ADJUSTMENT',
    ],

    'statuses' => [
        'batch' => ['active', 'expired', 'blocked', 'consumed'],
        'serial' => ['AVAILABLE', 'SOLD', 'RETURNED', 'DAMAGED', 'SCRAPPED'],
        'document' => ['DRAFT', 'PENDING', 'COMPLETED', 'CANCELLED'],
        'cycle_count' => ['draft', 'pending', 'completed', 'cancelled'],
        'inspection' => ['PENDING', 'PASSED', 'FAILED'],
        'task' => ['PENDING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED'],
    ],

    'valuation_methods' => ['fifo', 'lifo', 'fefo', 'weighted_average', 'standard', 'specific'],

    'trace_actions' => ['scan', 'receive', 'transfer', 'pick', 'pack', 'ship', 'return', 'adjust', 'dispose', 'count'],

    'immutable' => [
        'stock_movements' => ['after_create' => true],
        'inventory_cost_layers' => ['after_create' => true],
        'trace_logs' => ['after_create' => true],
        'stock_reservations' => ['after_create' => true],
        'stock_transfers' => ['status_column' => 'status', 'statuses' => ['COMPLETED', 'CANCELLED']],
        'stock_adjustments' => ['status_column' => 'status', 'statuses' => ['COMPLETED', 'CANCELLED']],
        'transfer_orders' => ['status_column' => 'status', 'statuses' => ['COMPLETED', 'CANCELLED']],
    ],

    'resources' => [
        'batches' => [
            'repository' => BatchRepositoryInterface::class,
            'label' => 'Batch',
            'rules' => [
                'row_version' => ['nullable', 'integer', 'min:1'],
                'organization_unit_id' => ['nullable', 'integer', 'exists:organization_units,id'],
                'item_id' => ['required', 'integer', 'exists:items,id'],
                'variant_id' => ['nullable', 'integer', 'exists:item_variants,id'],
                'batch_number' => ['required', 'string', 'max:255'],
                'lot_number' => ['nullable', 'string', 'max:255'],
                'manufacture_date' => ['nullable', 'date'],
                'expiry_date' => ['nullable', 'date', 'after_or_equal:manufacture_date'],
                'received_date' => ['nullable', 'date'],
                'supplier_id' => ['nullable', 'integer', 'exists:suppliers,id'],
                'status' => ['nullable', 'string'],
                'notes' => ['nullable', 'string'],
                'unit_cost' => ['nullable', 'numeric', 'min:0'],
                'metadata' => ['nullable', 'array'],
            ],
        ],
        'serials' => [
            'repository' => SerialRepositoryInterface::class,
            'label' => 'Serial',
            'rules' => [
                'row_version' => ['nullable', 'integer', 'min:1'],
                'organization_unit_id' => ['nullable', 'integer', 'exists:organization_units,id'],
                'item_id' => ['required', 'integer', 'exists:items,id'],
                'variant_id' => ['nullable', 'integer', 'exists:item_variants,id'],
                'serial_number' => ['required', 'string', 'max:255'],
                'batch_id' => ['nullable', 'integer', 'exists:batches,id'],
                'status' => ['nullable', 'string'],
                'current_location_id' => ['nullable', 'integer', 'exists:warehouse_locations,id'],
                'current_owner_type' => ['nullable', 'string', 'max:255'],
                'current_owner_id' => ['nullable', 'integer'],
                'warranty_expiry' => ['nullable', 'date'],
                'notes' => ['nullable', 'string'],
                'manufacture_date' => ['nullable', 'date'],
                'unit_cost' => ['nullable', 'numeric', 'min:0'],
                'metadata' => ['nullable', 'array'],
            ],
        ],
        'valuation_configs' => [
            'repository' => ValuationConfigRepositoryInterface::class,
            'label' => 'Valuation config',
            'rules' => [
                'row_version' => ['nullable', 'integer', 'min:1'],
                'organization_unit_id' => ['nullable', 'integer', 'exists:organization_units,id'],
                'warehouse_id' => ['nullable', 'integer', 'exists:warehouses,id'],
                'item_id' => ['nullable', 'integer', 'exists:items,id'],
                'variant_id' => ['nullable', 'integer', 'exists:item_variants,id'],
                'location_id' => ['nullable', 'integer', 'exists:warehouse_locations,id'],
                'batch_id' => ['nullable', 'integer', 'exists:batches,id'],
                'serial_id' => ['nullable', 'integer', 'exists:serials,id'],
                'transaction_type' => ['nullable', 'string', 'max:255'],
                'valuation_method' => ['nullable', 'string'],
                'is_active' => ['nullable', 'boolean'],
                'metadata' => ['nullable', 'array'],
            ],
        ],
        'stock_levels' => [
            'repository' => StockLevelRepositoryInterface::class,
            'label' => 'Stock level',
            'rules' => [
                'row_version' => ['nullable', 'integer', 'min:1'],
                'organization_unit_id' => ['nullable', 'integer', 'exists:organization_units,id'],
                'item_id' => ['required', 'integer', 'exists:items,id'],
                'variant_id' => ['nullable', 'integer', 'exists:item_variants,id'],
                'warehouse_id' => ['required', 'integer', 'exists:warehouses,id'],
                'location_id' => ['nullable', 'integer', 'exists:warehouse_locations,id'],
                'batch_id' => ['nullable', 'integer', 'exists:batches,id'],
                'serial_id' => ['nullable', 'integer', 'exists:serials,id'],
                'uom_id' => ['required', 'integer', 'exists:unit_of_measures,id'],
                'quantity_on_hand' => ['nullable', 'numeric'],
                'quantity_reserved' => ['nullable', 'numeric', 'min:0'],
                'unit_cost' => ['nullable', 'numeric', 'min:0'],
                'last_movement_at' => ['nullable', 'date'],
                'condition' => ['nullable', 'string', 'max:255'],
                'metadata' => ['nullable', 'array'],
            ],
        ],
        'stock_movements' => [
            'repository' => StockMovementRepositoryInterface::class,
            'label' => 'Stock movement',
            'rules' => [
                'row_version' => ['nullable', 'integer', 'min:1'],
                'organization_unit_id' => ['nullable', 'integer', 'exists:organization_units,id'],
                'direction' => ['required', 'string'],
                'item_id' => ['required', 'integer', 'exists:items,id'],
                'variant_id' => ['nullable', 'integer', 'exists:item_variants,id'],
                'batch_id' => ['nullable', 'integer', 'exists:batches,id'],
                'serial_id' => ['nullable', 'integer', 'exists:serials,id'],
                'location_id' => ['nullable', 'integer', 'exists:warehouse_locations,id'],
                'warehouse_id' => ['nullable', 'integer', 'exists:warehouses,id'],
                'txn_type' => ['required', 'string'],
                'reference_type' => ['nullable', 'string', 'max:255'],
                'reference_id' => ['nullable', 'integer'],
                'uom_id' => ['required', 'integer', 'exists:unit_of_measures,id'],
                'quantity' => ['required', 'numeric', 'min:0'],
                'quantity_in' => ['nullable', 'numeric', 'min:0'],
                'quantity_out' => ['nullable', 'numeric', 'min:0'],
                'unit_cost' => ['nullable', 'numeric', 'min:0'],
                'total_cost' => ['nullable', 'numeric', 'min:0'],
                'balance_quantity' => ['nullable', 'numeric'],
                'balance_value' => ['nullable', 'numeric'],
                'performed_by' => ['nullable', 'integer', 'exists:users,id'],
                'performed_at' => ['nullable', 'date'],
                'notes' => ['nullable', 'string'],
                'metadata' => ['nullable', 'array'],
            ],
        ],
        'inventory_cost_layers' => [
            'repository' => InventoryCostLayerRepositoryInterface::class,
            'label' => 'Inventory cost layer',
            'rules' => [
                'row_version' => ['nullable', 'integer', 'min:1'],
                'organization_unit_id' => ['nullable', 'integer', 'exists:organization_units,id'],
                'item_id' => ['required', 'integer', 'exists:items,id'],
                'variant_id' => ['nullable', 'integer', 'exists:item_variants,id'],
                'batch_id' => ['nullable', 'integer', 'exists:batches,id'],
                'serial_id' => ['nullable', 'integer', 'exists:serials,id'],
                'warehouse_id' => ['nullable', 'integer', 'exists:warehouses,id'],
                'location_id' => ['nullable', 'integer', 'exists:warehouse_locations,id'],
                'valuation_method' => ['nullable', 'string'],
                'layer_date' => ['required', 'date'],
                'quantity_in' => ['required', 'numeric', 'min:0'],
                'quantity_remaining' => ['required', 'numeric', 'min:0'],
                'unit_cost' => ['required', 'numeric', 'min:0'],
                'reference_type' => ['nullable', 'string', 'max:255'],
                'reference_id' => ['nullable', 'integer'],
                'is_closed' => ['nullable', 'boolean'],
                'metadata' => ['nullable', 'array'],
            ],
        ],
        'stock_reservations' => [
            'repository' => StockReservationRepositoryInterface::class,
            'label' => 'Stock reservation',
            'rules' => [
                'row_version' => ['nullable', 'integer', 'min:1'],
                'organization_unit_id' => ['nullable', 'integer', 'exists:organization_units,id'],
                'item_id' => ['required', 'integer', 'exists:items,id'],
                'variant_id' => ['nullable', 'integer', 'exists:item_variants,id'],
                'batch_id' => ['nullable', 'integer', 'exists:batches,id'],
                'serial_id' => ['nullable', 'integer', 'exists:serials,id'],
                'location_id' => ['nullable', 'integer', 'exists:warehouse_locations,id'],
                'warehouse_id' => ['required', 'integer', 'exists:warehouses,id'],
                'quantity' => ['required', 'numeric', 'min:0'],
                'reserved_for_type' => ['nullable', 'string', 'max:255'],
                'reserved_for_id' => ['nullable', 'integer'],
                'expires_at' => ['nullable', 'date'],
                'unit_cost' => ['nullable', 'numeric', 'min:0'],
                'metadata' => ['nullable', 'array'],
            ],
        ],
        'stock_transfers' => [
            'repository' => StockTransferRepositoryInterface::class,
            'label' => 'Stock transfer',
            'rules' => [
                'row_version' => ['nullable', 'integer', 'min:1'],
                'organization_unit_id' => ['nullable', 'integer', 'exists:organization_units,id'],
                'reference_number' => ['required', 'string', 'max:255'],
                'from_warehouse_id' => ['required', 'integer', 'exists:warehouses,id'],
                'to_warehouse_id' => ['required', 'integer', 'exists:warehouses,id'],
                'from_location_id' => ['nullable', 'integer', 'exists:warehouse_locations,id'],
                'to_location_id' => ['nullable', 'integer', 'exists:warehouse_locations,id'],
                'status' => ['nullable', 'string'],
                'requested_by' => ['required', 'integer', 'exists:users,id'],
                'approved_by' => ['nullable', 'integer', 'exists:users,id'],
                'transferred_at' => ['nullable', 'date'],
                'notes' => ['nullable', 'string'],
                'metadata' => ['nullable', 'array'],
            ],
        ],
        'stock_transfer_lines' => [
            'repository' => StockTransferLineRepositoryInterface::class,
            'label' => 'Stock transfer line',
            'rules' => [
                'row_version' => ['nullable', 'integer', 'min:1'],
                'organization_unit_id' => ['nullable', 'integer', 'exists:organization_units,id'],
                'stock_transfer_id' => ['required', 'integer', 'exists:stock_transfers,id'],
                'item_id' => ['required', 'integer', 'exists:items,id'],
                'variant_id' => ['nullable', 'integer', 'exists:item_variants,id'],
                'batch_id' => ['nullable', 'integer', 'exists:batches,id'],
                'serial_id' => ['nullable', 'integer', 'exists:serials,id'],
                'location_id' => ['nullable', 'integer', 'exists:warehouse_locations,id'],
                'uom_id' => ['required', 'integer', 'exists:unit_of_measures,id'],
                'quantity' => ['required', 'numeric', 'min:0'],
                'unit_cost' => ['nullable', 'numeric', 'min:0'],
                'metadata' => ['nullable', 'array'],
            ],
        ],
        'stock_adjustments' => [
            'repository' => StockAdjustmentRepositoryInterface::class,
            'label' => 'Stock adjustment',
            'rules' => [
                'row_version' => ['nullable', 'integer', 'min:1'],
                'organization_unit_id' => ['nullable', 'integer', 'exists:organization_units,id'],
                'reference_number' => ['required', 'string', 'max:255'],
                'warehouse_id' => ['required', 'integer', 'exists:warehouses,id'],
                'location_id' => ['nullable', 'integer', 'exists:warehouse_locations,id'],
                'type' => ['nullable', 'string', 'max:255'],
                'status' => ['nullable', 'string'],
                'counted_by' => ['nullable', 'integer', 'exists:users,id'],
                'counted_at' => ['nullable', 'date'],
                'approved_by' => ['nullable', 'integer', 'exists:users,id'],
                'approved_at' => ['nullable', 'date'],
                'reason' => ['nullable', 'string'],
                'metadata' => ['nullable', 'array'],
            ],
        ],
        'stock_adjustment_lines' => [
            'repository' => StockAdjustmentLineRepositoryInterface::class,
            'label' => 'Stock adjustment line',
            'rules' => [
                'row_version' => ['nullable', 'integer', 'min:1'],
                'organization_unit_id' => ['nullable', 'integer', 'exists:organization_units,id'],
                'stock_adjustment_id' => ['required', 'integer', 'exists:stock_adjustments,id'],
                'item_id' => ['required', 'integer', 'exists:items,id'],
                'variant_id' => ['nullable', 'integer', 'exists:item_variants,id'],
                'batch_id' => ['nullable', 'integer', 'exists:batches,id'],
                'serial_id' => ['nullable', 'integer', 'exists:serials,id'],
                'location_id' => ['nullable', 'integer', 'exists:warehouse_locations,id'],
                'warehouse_id' => ['required', 'integer', 'exists:warehouses,id'],
                'system_qty' => ['required', 'numeric', 'min:0'],
                'counted_qty' => ['required', 'numeric', 'min:0'],
                'variance_qty' => ['nullable', 'numeric'],
                'unit_cost' => ['nullable', 'numeric', 'min:0'],
                'variance_value' => ['nullable', 'numeric'],
                'adjustment_movement_id' => ['nullable', 'integer', 'exists:stock_movements,id'],
                'metadata' => ['nullable', 'array'],
            ],
        ],
        'cycle_count_headers' => [
            'repository' => CycleCountHeaderRepositoryInterface::class,
            'label' => 'Cycle count header',
            'rules' => [
                'row_version' => ['nullable', 'integer', 'min:1'],
                'organization_unit_id' => ['nullable', 'integer', 'exists:organization_units,id'],
                'warehouse_id' => ['required', 'integer', 'exists:warehouses,id'],
                'location_id' => ['nullable', 'integer', 'exists:warehouse_locations,id'],
                'status' => ['nullable', 'string'],
                'counted_by_user_id' => ['nullable', 'integer', 'exists:users,id'],
                'counted_at' => ['nullable', 'date'],
                'approved_by_user_id' => ['nullable', 'integer', 'exists:users,id'],
                'approved_at' => ['nullable', 'date'],
                'metadata' => ['nullable', 'array'],
            ],
        ],
        'cycle_count_lines' => [
            'repository' => CycleCountLineRepositoryInterface::class,
            'label' => 'Cycle count line',
            'rules' => [
                'row_version' => ['nullable', 'integer', 'min:1'],
                'organization_unit_id' => ['nullable', 'integer', 'exists:organization_units,id'],
                'count_header_id' => ['required', 'integer', 'exists:cycle_count_headers,id'],
                'item_id' => ['required', 'integer', 'exists:items,id'],
                'variant_id' => ['nullable', 'integer', 'exists:item_variants,id'],
                'batch_id' => ['nullable', 'integer', 'exists:batches,id'],
                'serial_id' => ['nullable', 'integer', 'exists:serials,id'],
                'location_id' => ['nullable', 'integer', 'exists:warehouse_locations,id'],
                'system_qty' => ['required', 'numeric', 'min:0'],
                'counted_qty' => ['required', 'numeric', 'min:0'],
                'variance_qty' => ['nullable', 'numeric'],
                'unit_cost' => ['nullable', 'numeric', 'min:0'],
                'variance_value' => ['nullable', 'numeric'],
                'adjustment_movement_id' => ['nullable', 'integer', 'exists:stock_movements,id'],
                'metadata' => ['nullable', 'array'],
            ],
        ],
        'transfer_orders' => [
            'repository' => TransferOrderRepositoryInterface::class,
            'label' => 'Transfer order',
            'rules' => [
                'row_version' => ['nullable', 'integer', 'min:1'],
                'organization_unit_id' => ['nullable', 'integer', 'exists:organization_units,id'],
                'from_warehouse_id' => ['required', 'integer', 'exists:warehouses,id'],
                'to_warehouse_id' => ['required', 'integer', 'exists:warehouses,id'],
                'transfer_number' => ['required', 'string', 'max:255'],
                'status' => ['nullable', 'string'],
                'request_date' => ['required', 'date'],
                'expected_date' => ['nullable', 'date', 'after_or_equal:request_date'],
                'shipped_date' => ['nullable', 'date'],
                'received_date' => ['nullable', 'date'],
                'notes' => ['nullable', 'string'],
                'metadata' => ['nullable', 'array'],
            ],
        ],
        'transfer_order_lines' => [
            'repository' => TransferOrderLineRepositoryInterface::class,
            'label' => 'Transfer order line',
            'rules' => [
                'row_version' => ['nullable', 'integer', 'min:1'],
                'organization_unit_id' => ['nullable', 'integer', 'exists:organization_units,id'],
                'transfer_order_id' => ['required', 'integer', 'exists:transfer_orders,id'],
                'item_id' => ['required', 'integer', 'exists:items,id'],
                'variant_id' => ['nullable', 'integer', 'exists:item_variants,id'],
                'batch_id' => ['nullable', 'integer', 'exists:batches,id'],
                'serial_id' => ['nullable', 'integer', 'exists:serials,id'],
                'from_location_id' => ['nullable', 'integer', 'exists:warehouse_locations,id'],
                'to_location_id' => ['nullable', 'integer', 'exists:warehouse_locations,id'],
                'uom_id' => ['required', 'integer', 'exists:unit_of_measures,id'],
                'requested_qty' => ['required', 'numeric', 'min:0'],
                'shipped_qty' => ['nullable', 'numeric', 'min:0'],
                'received_qty' => ['nullable', 'numeric', 'min:0'],
                'unit_cost' => ['nullable', 'numeric', 'min:0'],
                'metadata' => ['nullable', 'array'],
            ],
        ],
        'trace_logs' => [
            'repository' => TraceLogRepositoryInterface::class,
            'label' => 'Trace log',
            'rules' => [
                'row_version' => ['nullable', 'integer', 'min:1'],
                'organization_unit_id' => ['nullable', 'integer', 'exists:organization_units,id'],
                'entity_type' => ['required', 'string', 'max:255'],
                'entity_id' => ['required', 'integer'],
                'identifier_id' => ['nullable', 'integer', 'exists:item_identifiers,id'],
                'action_type' => ['required', 'string'],
                'reference_type' => ['nullable', 'string', 'max:255'],
                'reference_id' => ['nullable', 'integer'],
                'source_warehouse_id' => ['nullable', 'integer', 'exists:warehouses,id'],
                'destination_warehouse_id' => ['nullable', 'integer', 'exists:warehouses,id'],
                'source_location_id' => ['nullable', 'integer', 'exists:warehouse_locations,id'],
                'destination_location_id' => ['nullable', 'integer', 'exists:warehouse_locations,id'],
                'quantity' => ['nullable', 'numeric', 'min:0'],
                'performed_by' => ['nullable', 'integer', 'exists:users,id'],
                'performed_at' => ['nullable', 'date'],
                'device_id' => ['nullable', 'string', 'max:255'],
                'metadata' => ['nullable', 'array'],
            ],
        ],
        'receipt_inspections' => [
            'repository' => ReceiptInspectionRepositoryInterface::class,
            'label' => 'Receipt inspection',
            'rules' => [
                'row_version' => ['nullable', 'integer', 'min:1'],
                'organization_unit_id' => ['nullable', 'integer', 'exists:organization_units,id'],
                'document_type' => ['required', 'string', 'max:255'],
                'document_id' => ['required', 'integer'],
                'inspected_by' => ['nullable', 'integer', 'exists:users,id'],
                'inspection_result' => ['nullable', 'string'],
                'notes' => ['nullable', 'string'],
                'inspected_at' => ['nullable', 'date'],
                'metadata' => ['nullable', 'array'],
            ],
        ],
        'put_away_tasks' => [
            'repository' => PutAwayTaskRepositoryInterface::class,
            'label' => 'Put away task',
            'rules' => [
                'row_version' => ['nullable', 'integer', 'min:1'],
                'organization_unit_id' => ['nullable', 'integer', 'exists:organization_units,id'],
                'receipt_inspection_id' => ['nullable', 'integer', 'exists:receipt_inspections,id'],
                'stock_movement_id' => ['required', 'integer', 'exists:stock_movements,id'],
                'target_warehouse_id' => ['required', 'integer', 'exists:warehouses,id'],
                'target_location_id' => ['nullable', 'integer', 'exists:warehouse_locations,id'],
                'quantity' => ['required', 'numeric', 'min:0'],
                'status' => ['nullable', 'string'],
                'assigned_user_id' => ['nullable', 'integer', 'exists:users,id'],
                'completed_at' => ['nullable', 'date'],
                'metadata' => ['nullable', 'array'],
            ],
        ],
        'picking_tasks' => [
            'repository' => PickingTaskRepositoryInterface::class,
            'label' => 'Picking task',
            'rules' => [
                'row_version' => ['nullable', 'integer', 'min:1'],
                'organization_unit_id' => ['nullable', 'integer', 'exists:organization_units,id'],
                'receipt_inspection_id' => ['nullable', 'integer', 'exists:receipt_inspections,id'],
                'stock_movement_id' => ['required', 'integer', 'exists:stock_movements,id'],
                'source_warehouse_id' => ['required', 'integer', 'exists:warehouses,id'],
                'source_location_id' => ['nullable', 'integer', 'exists:warehouse_locations,id'],
                'quantity' => ['required', 'numeric', 'min:0'],
                'status' => ['nullable', 'string'],
                'assigned_user_id' => ['nullable', 'integer', 'exists:users,id'],
                'completed_at' => ['nullable', 'date'],
                'metadata' => ['nullable', 'array'],
            ],
        ],
    ],
];
