<?php

declare(strict_types=1);

namespace Modules\Inventory\Domain\Constants;

final class InventoryErrorCode
{
    public const INVALID_VALUE = 'INVENTORY_INVALID_VALUE';
    public const NOT_FOUND = 'INVENTORY_NOT_FOUND';
    public const INVALID_STRATEGY = 'INVENTORY_INVALID_STRATEGY';
    public const INSUFFICIENT_STOCK = 'INVENTORY_INSUFFICIENT_STOCK';
    public const INVALID_DIRECTION = 'INVENTORY_INVALID_DIRECTION';
    public const ITEM_NOT_FOUND = 'INVENTORY_ITEM_NOT_FOUND';
    public const NON_STOCKABLE_ITEM = 'INVENTORY_NON_STOCKABLE_ITEM';
    public const UOM_CONVERSION_FAILED = 'INVENTORY_UOM_CONVERSION_FAILED';
    public const INVALID_BATCH = 'INVENTORY_INVALID_BATCH';
    public const INVALID_SERIAL = 'INVENTORY_INVALID_SERIAL';
    public const NEGATIVE_STOCK_NOT_ALLOWED = 'INVENTORY_NEGATIVE_STOCK_NOT_ALLOWED';
    public const RESERVATION_NOT_FOUND = 'INVENTORY_RESERVATION_NOT_FOUND';
    public const INVALID_RESERVATION_STATUS = 'INVENTORY_INVALID_RESERVATION_STATUS';
    public const INVALID_RESERVATION_QUANTITY = 'INVENTORY_INVALID_RESERVATION_QUANTITY';
}
