import type {
    GoodsReceivedNote,
    PurchaseAdvance,
    PurchaseAuditEntry,
    PurchaseCalculationPreview,
    PurchaseDashboardMetric,
    PurchaseFinancePostingPreview,
    PurchaseInventoryEffect,
    PurchaseInvoice,
    PurchaseOrder,
    PurchasePayment,
    PurchaseReturn,
    PurchaseSettings,
    SupplierRefund,
} from '../types/purchase.types';

export const purchaseDashboardMetrics: PurchaseDashboardMetric[] = [
    { label: 'Open POs', status: 'Backend Read Model', value: '18' },
    { label: 'GRNs Awaiting Invoice', status: 'Backend Read Model', value: '7' },
    { label: 'Invoices Awaiting Payment', status: 'Backend Read Model', value: '11' },
    { label: 'Returns In Progress', status: 'Backend Read Model', value: '3' },
];

export const purchaseOrders: PurchaseOrder[] = [
    {
        balance: 'Backend calculated',
        expectedDate: '2026-06-04',
        grandTotal: 'LKR 485,000.00',
        id: 'po-001',
        lines: [
            { backendConvertedQuantity: '12 PCS', discountAmount: 'Backend calculated', id: 'pol-001', item: 'Oil Filter Kit', lineTotal: 'Backend calculated', orderedQuantity: '1 BOX', receivedQuantity: '6 PCS', remainingQuantity: 'Backend calculated', taxAmount: 'Backend calculated', unitPrice: 'LKR 72,000.00', uom: 'BOX' },
            { backendConvertedQuantity: '40 L', discountAmount: 'Backend calculated', id: 'pol-002', item: 'Synthetic Engine Oil', lineTotal: 'Backend calculated', orderedQuantity: '40 L', receivedQuantity: '20 L', remainingQuantity: 'Backend calculated', taxAmount: 'Backend calculated', unitPrice: 'LKR 2,750.00', uom: 'L' },
        ],
        orderDate: '2026-05-24',
        poNumber: 'PO-2026-0001',
        status: 'partially_received',
        supplier: 'Auto Parts Lanka',
        updatedAt: '2026-05-29 09:20',
        workflow: 'Flexible: PO -> GRN -> Supplier Invoice -> Payment',
    },
    {
        balance: 'Backend calculated',
        expectedDate: '2026-06-08',
        grandTotal: 'LKR 138,500.00',
        id: 'po-002',
        lines: [
            { backendConvertedQuantity: '2 PCS', discountAmount: 'Backend calculated', id: 'pol-003', item: 'Workshop Lift Service', lineTotal: 'Backend calculated', orderedQuantity: '2 Service', receivedQuantity: '0', remainingQuantity: 'Backend calculated', taxAmount: 'Backend calculated', unitPrice: 'LKR 69,250.00', uom: 'Service' },
        ],
        orderDate: '2026-05-28',
        poNumber: 'PO-2026-0002',
        status: 'approved',
        supplier: 'Fleet Tools Pvt Ltd',
        updatedAt: '2026-05-29 14:10',
        workflow: 'PO -> Supplier Invoice allowed by setting',
    },
    {
        balance: 'Backend calculated',
        expectedDate: '2026-05-30',
        grandTotal: 'LKR 64,800.00',
        id: 'po-003',
        lines: [
            { backendConvertedQuantity: '24 PCS', discountAmount: 'Backend calculated', id: 'pol-004', item: 'Brake Pads', lineTotal: 'Backend calculated', orderedQuantity: '24 PCS', receivedQuantity: '24 PCS', remainingQuantity: 'Backend calculated', taxAmount: 'Backend calculated', unitPrice: 'LKR 2,700.00', uom: 'PCS' },
        ],
        orderDate: '2026-05-20',
        poNumber: 'PO-2026-0003',
        status: 'received',
        supplier: 'Global Spares Trading',
        updatedAt: '2026-05-28 16:40',
        workflow: 'Fully received, awaiting invoice match',
    },
];

export const grns: GoodsReceivedNote[] = [
    {
        grnDate: '2026-05-29',
        grnNumber: 'GRN-2026-0007',
        id: 'grn-001',
        inventoryStatus: 'Stock receive preview returned by backend',
        lines: [
            { acceptedQuantity: '6 PCS', backendBaseQuantity: 'Backend converted', id: 'grnl-001', item: 'Oil Filter Kit', orderedQuantity: '1 BOX', rejectedQuantity: '0', sourceLine: 'PO-2026-0001 / line 1', uom: 'PCS' },
            { acceptedQuantity: '20 L', backendBaseQuantity: 'Backend converted', id: 'grnl-002', item: 'Synthetic Engine Oil', orderedQuantity: '40 L', rejectedQuantity: '0', sourceLine: 'PO-2026-0001 / line 2', uom: 'L' },
        ],
        sourcePo: 'PO-2026-0001',
        status: 'posted',
        supplier: 'Auto Parts Lanka',
        updatedAt: '2026-05-29 15:00',
    },
    {
        grnDate: '2026-05-30',
        grnNumber: 'GRN-2026-0008',
        id: 'grn-002',
        inventoryStatus: 'Draft, no stock posting yet',
        lines: [
            { acceptedQuantity: '8 PCS', backendBaseQuantity: 'Backend converted', id: 'grnl-003', item: 'Wiper Blade Set', rejectedQuantity: '0', sourceLine: 'Direct GRN', uom: 'PCS' },
        ],
        status: 'draft',
        supplier: 'Rapid Auto Supplies',
        updatedAt: '2026-05-30 08:15',
    },
];

export const purchaseInvoices: PurchaseInvoice[] = [
    {
        balance: 'Backend calculated',
        documentStatus: 'Generated by Document module',
        dueDate: '2026-06-28',
        grandTotal: 'LKR 242,500.00',
        id: 'pinv-001',
        invoiceDate: '2026-05-29',
        invoiceNumber: 'PINV-2026-0042',
        lines: [
            { discountAmount: 'Backend calculated', id: 'pinvl-001', invoiceQuantity: '6 PCS', item: 'Oil Filter Kit', lineTotal: 'Backend calculated', sourceLine: 'GRN-2026-0007 / line 1', taxAmount: 'Backend calculated', unitPrice: 'Backend resolved', uom: 'PCS' },
            { discountAmount: 'Backend calculated', id: 'pinvl-002', invoiceQuantity: '20 L', item: 'Synthetic Engine Oil', lineTotal: 'Backend calculated', sourceLine: 'GRN-2026-0007 / line 2', taxAmount: 'Backend calculated', unitPrice: 'Backend resolved', uom: 'L' },
        ],
        paidAmount: 'Backend calculated',
        sourceReference: 'GRN-2026-0007',
        status: 'partially_paid',
        supplier: 'Auto Parts Lanka',
        updatedAt: '2026-05-30 10:10',
    },
    {
        balance: 'Backend calculated',
        documentStatus: 'Pending generation',
        dueDate: '2026-06-14',
        grandTotal: 'LKR 88,000.00',
        id: 'pinv-002',
        invoiceDate: '2026-05-30',
        invoiceNumber: 'PINV-2026-0043',
        lines: [
            { discountAmount: 'Backend calculated', id: 'pinvl-003', invoiceQuantity: '1 Service', item: 'Workshop Lift Service', lineTotal: 'Backend calculated', sourceLine: 'Direct invoice', taxAmount: 'Backend calculated', unitPrice: 'Backend resolved', uom: 'Service' },
        ],
        paidAmount: 'Backend calculated',
        status: 'draft',
        supplier: 'Fleet Tools Pvt Ltd',
        updatedAt: '2026-05-30 11:40',
    },
];

export const purchasePayments: PurchasePayment[] = [
    {
        allocations: [
            { allocatedAmount: 'Backend allocated', documentBalanceAfter: 'Backend calculated', id: 'pa-001', sourceDocument: 'PINV-2026-0042', status: 'active' },
        ],
        amount: 'LKR 100,000.00',
        id: 'pay-001',
        method: 'Bank Transfer',
        paymentDate: '2026-05-30',
        paymentNumber: 'SPAY-2026-0012',
        reference: 'BANK-TRF-8812',
        status: 'allocated',
        supplier: 'Auto Parts Lanka',
        unallocatedAmount: 'Backend calculated',
    },
];

export const purchaseAdvances: PurchaseAdvance[] = [
    { advanceNumber: 'SADV-2026-0003', amount: 'LKR 75,000.00', id: 'adv-001', remainingAmount: 'Backend calculated', status: 'posted', supplier: 'Global Spares Trading' },
];

export const purchaseReturns: PurchaseReturn[] = [
    {
        id: 'pret-001',
        lines: [
            { backendReturnableQuantity: 'Backend calculated', id: 'pretl-001', item: 'Brake Pads', returnQuantity: '2 PCS', sourceLine: 'GRN-2026-0006 / line 2', uom: 'PCS' },
        ],
        returnNumber: 'PRET-2026-0002',
        returnTotal: 'Backend calculated',
        sourceReference: 'PINV-2026-0039',
        status: 'posted',
        supplier: 'Global Spares Trading',
        updatedAt: '2026-05-29 17:30',
    },
];

export const supplierRefunds: SupplierRefund[] = [
    { amount: 'Backend calculated', id: 'sref-001', method: 'Credit note / bank', refundNumber: 'SREF-2026-0001', sourceReference: 'PRET-2026-0002', status: 'pending', supplier: 'Global Spares Trading' },
];

export const purchaseSettings: PurchaseSettings = {
    allowDirectInvoice: true,
    allowGrnWithoutPo: true,
    allowInvoiceWithoutGrn: true,
    allowOverReceipt: false,
    defaultPayableAccount: 'Accounts Payable - Trade',
    defaultPaymentTerm: 'Net 30',
    defaultTaxGroup: 'VAT Purchase',
    defaultWarehouse: 'Main Parts Store',
    grnSequence: 'GRN-{YYYY}-{####}',
    id: 'purchase-settings',
    invoiceDocumentDefinition: 'Supplier Invoice Standard',
    invoiceMatchingRule: 'Three-way match when PO and GRN exist',
    invoiceSequence: 'PINV-{YYYY}-{####}',
    poSequence: 'PO-{YYYY}-{####}',
    returnSequence: 'PRET-{YYYY}-{####}',
    stockReceiveTiming: 'On GRN post',
};

export const invoiceCalculationPreview: PurchaseCalculationPreview = {
    breakdown: [
        { label: 'Pricing', value: 'Resolved by Pricing module' },
        { label: 'Tax', value: 'Resolved by Finance tax rules' },
        { label: 'UOM', value: 'Converted by UOM module' },
    ],
    calculated: {
        discountTotal: 'Backend calculated',
        grandTotal: 'Backend calculated',
        subtotal: 'Backend calculated',
        taxTotal: 'Backend calculated',
        uomConversion: 'Backend converted quantities returned',
    },
    errors: [],
    input: {},
    warnings: ['Mock preview. Real backend remains authoritative.'],
};

export const inventoryEffects: PurchaseInventoryEffect[] = [
    { decision: 'Available to post', item: 'Oil Filter Kit', quantityEffect: 'Backend stock receipt effect', sourceReference: 'GRN-2026-0007', warehouse: 'Main Parts Store' },
    { decision: 'Return stock movement required', item: 'Brake Pads', quantityEffect: 'Backend stock return effect', sourceReference: 'PRET-2026-0002', warehouse: 'Main Parts Store' },
];

export const financePostingPreview: PurchaseFinancePostingPreview = {
    calculated: {
        apImpact: 'Backend AP impact',
        eligibility: 'Backend posting decision',
        journalImpact: 'Backend journal preview',
        taxImpact: 'Backend tax posting',
    },
    lines: [
        { account: 'Inventory / Expense', credit: 'Backend calculated', debit: 'Backend calculated', description: 'Supplier invoice line effect' },
        { account: 'Accounts Payable', credit: 'Backend calculated', debit: 'Backend calculated', description: 'Supplier payable effect' },
    ],
};

export const paymentAllocationPreview = {
    allocatedAmount: 'Backend calculated',
    documentBalanceAfter: 'Backend calculated',
    remainingUnallocated: 'Backend calculated',
    warnings: ['Allocation preview is backend-owned.'],
};

export const documentPreview = {
    documentNumber: 'Backend sequence preview',
    status: 'Rendered by Document module',
    template: 'Supplier Invoice Standard',
};

export const purchaseActivity: PurchaseAuditEntry[] = [
    { actor: 'Procurement Manager', description: 'PO approved and released to supplier.', id: 'act-001', time: '2026-05-29 09:20', type: 'workflow' },
    { actor: 'Store Keeper', description: 'GRN posted; inventory effect requested from Inventory module.', id: 'act-002', time: '2026-05-29 15:00', type: 'inventory' },
    { actor: 'Accounts Payable', description: 'Supplier invoice preview requested; totals returned by backend.', id: 'act-003', time: '2026-05-30 10:10', type: 'finance' },
];

export function getPurchaseOrderById(id: string) {
    return purchaseOrders.find((order) => order.id === id) ?? purchaseOrders[0];
}

export function getGrnById(id: string) {
    return grns.find((grn) => grn.id === id) ?? grns[0];
}

export function getPurchaseInvoiceById(id: string) {
    return purchaseInvoices.find((invoice) => invoice.id === id) ?? purchaseInvoices[0];
}

export function getPurchasePaymentById(id: string) {
    return purchasePayments.find((payment) => payment.id === id) ?? purchasePayments[0];
}

export function getPurchaseReturnById(id: string) {
    return purchaseReturns.find((record) => record.id === id) ?? purchaseReturns[0];
}
