export const endpoints = {
    auth: '/api/v1/auth',
    customers: '/api/v1/customers',
    customerCategories: '/api/v1/customer-categories',
    suppliers: '/api/v1/suppliers',
    supplierCategories: '/api/v1/supplier-categories',
    items: '/api/v1/items',
    itemCategories: '/api/v1/item-categories',
    itemBrands: '/api/v1/item-brands',
    inventory: '/api/v1/inventory',
    purchase: '/api/v1/purchase',
    invoices: '/api/v1/invoices',
    payments: '/api/v1/payments',
    finance: '/api/v1/finance',
    uoms: '/api/v1/uoms',
    uomConversions: '/api/v1/uom-conversions',
} as const;
