<?php

declare(strict_types=1);

namespace Tests\Feature\Customer;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use Modules\Customer\Services\CustomerAuthorizationService;
use Modules\User\Models\UserModel;
use Tests\Support\TenantUserFixture;
use Tests\TestCase;

final class CustomerCodeGenerationTest extends TestCase
{
    use RefreshDatabase;

    protected function setUp(): void
    {
        parent::setUp();
        $this->withoutMiddleware();
        $this->trustTenantScopedRequestContextFromPayload();
        $this->mock(CustomerAuthorizationService::class, fn ($mock) => $mock->shouldReceive('assert')->zeroOrMoreTimes());
    }

    public function test_generated_code_is_visible_to_the_client_and_can_be_kept_or_replaced(): void
    {
        $tenantId = $this->tenant();
        $this->authenticate($tenantId);

        $generatedCode = $this->tenantPostJson($tenantId, '/api/v1/customers/code-reservations', [
            'tenant_id' => $tenantId,
        ])->assertOk()->json('data.code');

        self::assertIsString($generatedCode);
        self::assertMatchesRegularExpression('/^CUS-\d{6}$/', $generatedCode);

        $this->tenantPostJson($tenantId, '/api/v1/customers', $this->payload($tenantId, [
            'code' => $generatedCode,
            'name' => 'Generated Code Customer',
        ]))->assertCreated()->assertJsonPath('data.code', $generatedCode);

        $this->tenantPostJson($tenantId, '/api/v1/customers', $this->payload($tenantId, [
            'code' => 'CUSTOM-EDITABLE',
            'name' => 'Custom Code Customer',
        ]))->assertCreated()->assertJsonPath('data.code', 'CUSTOM-EDITABLE');

        $autoGenerated = $this->tenantPostJson($tenantId, '/api/v1/customers', $this->payload($tenantId, [
            'name' => 'Server Generated Customer',
        ]))->assertCreated()->json('data.code');

        self::assertIsString($autoGenerated);
        self::assertMatchesRegularExpression('/^CUS-\d{6}$/', $autoGenerated);
        self::assertNotSame($generatedCode, $autoGenerated);
    }

    /**
     * @param  array<string, mixed>  $overrides
     * @return array<string, mixed>
     */
    private function payload(int $tenantId, array $overrides): array
    {
        return array_merge([
            'tenant_id' => $tenantId,
            'name' => 'Customer',
            'customer_type' => 'individual',
            'status' => 'active',
            'is_tax_exempt' => false,
            'marketing_consent' => false,
        ], $overrides);
    }

    private function tenant(): int
    {
        $suffix = Str::upper(Str::random(8));

        return (int) DB::table('tenants')->insertGetId([
            'uuid' => (string) Str::uuid(),
            'code' => 'TEN-CODE-'.$suffix,
            'name' => 'Customer Code Tenant '.$suffix,
            'slug' => 'customer-code-'.Str::lower($suffix),
            'status' => 'active',
            'status_changed_at' => now(),
            'created_at' => now(),
            'updated_at' => now(),
        ]);
    }

    private function authenticate(int $tenantId): void
    {
        $userId = (int) TenantUserFixture::create([
            'tenant_id' => $tenantId,
            'first_name' => 'Customer',
            'last_name' => 'Creator',
            'email' => 'customer-code-'.Str::lower(Str::random(8)).'@example.test',
            'password' => bcrypt('secret-password'),
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        $user = $this->withTenantExecutionContext(
            $tenantId,
            fn (): UserModel => UserModel::query()->findOrFail($userId),
        );

        $this->actingAs($user, (string) config('module-auth.protected_route_guard', 'auth-api'));
    }
}
