export interface ModuleDefinition {
    key: string;
    label: string;
    path: string;
    pagePath: string;
    group: 'Core' | 'Commercial' | 'Operations' | 'Finance' | 'Master Data' | 'System';
    description: string;
    previewPromise: string;
    actions: string[];
    accent: string;
}

export const moduleCatalog: ModuleDefinition[] = [
    {
        key: 'hr',
        label: 'HR',
        path: '/modules/hr',
        pagePath: '../modules/hr/pages/HrPage.tsx',
        group: 'Master Data',
        description: 'Employee lifecycle, structures, salary setup, and optional user linkage.',
        previewPromise: 'Employee data stays separate from user access and remains transactionally managed.',
        actions: ['Employees', 'Departments', 'Designations'],
        accent: 'from-sky-500 to-cyan-600',
    },
    {
        key: 'sales',
        label: 'Sales',
        path: '/modules/sales',
        pagePath: '../modules/sales/pages/SalesPage.tsx',
        group: 'Commercial',
        description: 'Quotations, orders, invoices, returns, and backend-calculated previews.',
        previewPromise: 'Totals, discounts, taxes, stock effects, and allocations are resolved on the server.',
        actions: ['Quotations', 'Orders', 'Invoices'],
        accent: 'from-emerald-500 to-teal-700',
    },
    {
        key: 'purchase',
        label: 'Purchase',
        path: '/modules/purchase',
        pagePath: '../modules/purchase/pages/PurchasePage.tsx',
        group: 'Commercial',
        description: 'Purchase orders, receipts, bills, and supplier-side invoice previews.',
        previewPromise: 'Pricing, payable allocation, and validation flow through backend services.',
        actions: ['Orders', 'Receipts', 'Bills'],
        accent: 'from-amber-500 to-orange-700',
    },
    {
        key: 'payment',
        label: 'Payment',
        path: '/modules/payment',
        pagePath: '../modules/payment/pages/PaymentPage.tsx',
        group: 'Finance',
        description: 'Payment collection, allocation, reversal, and settlement workflows.',
        previewPromise: 'Allocation previews and remaining balances are validated before mutation.',
        actions: ['Collections', 'Allocations', 'Refunds'],
        accent: 'from-indigo-500 to-violet-700',
    },
    {
        key: 'finance',
        label: 'Finance',
        path: '/modules/finance',
        pagePath: '../modules/finance/pages/FinancePage.tsx',
        group: 'Finance',
        description: 'Journal posting, tax preview, ledgers, and accounting control flows.',
        previewPromise: 'Posting readiness and tax calculations are computed by backend engines.',
        actions: ['Journals', 'Tax preview', 'Ledgers'],
        accent: 'from-slate-700 to-slate-900',
    },
    {
        key: 'inventory',
        label: 'Inventory',
        path: '/modules/inventory',
        pagePath: '../modules/inventory/pages/InventoryPage.tsx',
        group: 'Operations',
        description: 'Stock movements, availability, adjustments, and warehouse coordination.',
        previewPromise: 'Availability and quantity impact are calculated by inventory services.',
        actions: ['Stock', 'Movements', 'Adjustments'],
        accent: 'from-lime-500 to-emerald-700',
    },
    {
        key: 'warehouse',
        label: 'Warehouse',
        path: '/modules/warehouse',
        pagePath: '../modules/warehouse/pages/WarehousePage.tsx',
        group: 'Operations',
        description: 'Locations, bins, stock policy, and capacity controls.',
        previewPromise: 'Storage topology remains consistent with inventory and logistics flows.',
        actions: ['Locations', 'Bins', 'Capacity'],
        accent: 'from-cyan-500 to-sky-700',
    },
    {
        key: 'pricing',
        label: 'Pricing',
        path: '/modules/pricing',
        pagePath: '../modules/pricing/pages/PricingPage.tsx',
        group: 'Commercial',
        description: 'Price lists, discount policy, and customer-specific price resolution.',
        previewPromise: 'Resolved prices always come from backend pricing rules.',
        actions: ['Lists', 'Rules', 'Promotions'],
        accent: 'from-fuchsia-500 to-pink-700',
    },
    {
        key: 'uom',
        label: 'UOM',
        path: '/modules/uom',
        pagePath: '../modules/uom/pages/UomPage.tsx',
        group: 'Master Data',
        description: 'Units of measure, conversions, and canonical quantity normalization.',
        previewPromise: 'Conversions stay authoritative in the backend service layer.',
        actions: ['Units', 'Conversions', 'Mappings'],
        accent: 'from-teal-500 to-emerald-700',
    },
    {
        key: 'customer',
        label: 'Customer',
        path: '/modules/customer',
        pagePath: '../modules/customer/pages/CustomerPage.tsx',
        group: 'Master Data',
        description: 'Customer master data, contacts, credit policy, and lifecycle status.',
        previewPromise: 'Commercial workflows consume validated customer records.',
        actions: ['Accounts', 'Contacts', 'Credit'],
        accent: 'from-blue-500 to-sky-700',
    },
    {
        key: 'supplier',
        label: 'Supplier',
        path: '/modules/supplier',
        pagePath: '../modules/supplier/pages/SupplierPage.tsx',
        group: 'Master Data',
        description: 'Supplier profiles, banking, contacts, and procurement readiness.',
        previewPromise: 'Purchase flows resolve supplier data before creating commitments.',
        actions: ['Vendors', 'Contacts', 'Terms'],
        accent: 'from-stone-500 to-zinc-700',
    },
    {
        key: 'item',
        label: 'Item',
        path: '/modules/item',
        pagePath: '../modules/item/pages/ItemPage.tsx',
        group: 'Master Data',
        description: 'Products, service items, SKU identity, and item status governance.',
        previewPromise: 'Item master feeds pricing, stock, and document generation.',
        actions: ['SKUs', 'Categories', 'Attributes'],
        accent: 'from-violet-500 to-slate-700',
    },
    {
        key: 'document',
        label: 'Document',
        path: '/modules/document',
        pagePath: '../modules/document/pages/DocumentPage.tsx',
        group: 'System',
        description: 'Document numbering, attachments, and traceability scaffolding.',
        previewPromise: 'Document flows remain aligned with generated business events.',
        actions: ['Attachments', 'Series', 'Audits'],
        accent: 'from-zinc-600 to-slate-900',
    },
    {
        key: 'voucher',
        label: 'Voucher',
        path: '/modules/voucher',
        pagePath: '../modules/voucher/pages/VoucherPage.tsx',
        group: 'Finance',
        description: 'Voucher issuance, approval, and transactional reconciliation.',
        previewPromise: 'Voucher previews keep accounting state deterministic.',
        actions: ['Drafts', 'Approvals', 'Posting'],
        accent: 'from-rose-500 to-orange-700',
    },
    {
        key: 'tenant',
        label: 'Tenant',
        path: '/modules/tenant',
        pagePath: '../modules/tenant/pages/TenantPage.tsx',
        group: 'System',
        description: 'Tenant administration, lifecycle, and access boundaries.',
        previewPromise: 'Tenant context stays separate from operational business data.',
        actions: ['Tenants', 'Plans', 'Boundaries'],
        accent: 'from-slate-600 to-brand-700',
    },
    {
        key: 'organization-unit',
        label: 'Org Unit',
        path: '/modules/organization-unit',
        pagePath: '../modules/organization-unit/pages/OrganizationUnitPage.tsx',
        group: 'System',
        description: 'Organizations, branches, divisions, and structural access rules.',
        previewPromise: 'User access and workflow context inherit from the active unit.',
        actions: ['Branches', 'Divisions', 'Sites'],
        accent: 'from-emerald-500 to-slate-700',
    },
    {
        key: 'user',
        label: 'User',
        path: '/modules/user',
        pagePath: '../modules/user/pages/UserPage.tsx',
        group: 'System',
        description: 'Access identities, roles, permissions, and account lifecycle.',
        previewPromise: 'Users are intentionally separate from employees and business records.',
        actions: ['Accounts', 'Roles', 'Permissions'],
        accent: 'from-slate-500 to-gray-800',
    },
    {
        key: 'sequence',
        label: 'Sequence',
        path: '/modules/sequence',
        pagePath: '../modules/sequence/pages/SequencePage.tsx',
        group: 'System',
        description: 'Document numbering, sequence policies, and prefix control.',
        previewPromise: 'Generated identifiers stay consistent across modules.',
        actions: ['Prefixes', 'Counters', 'Policies'],
        accent: 'from-amber-500 to-slate-700',
    },
    {
        key: 'audit',
        label: 'Audit',
        path: '/modules/audit',
        pagePath: '../modules/audit/pages/AuditPage.tsx',
        group: 'System',
        description: 'System events, action traces, and compliance visibility.',
        previewPromise: 'Operational history remains visible without leaking business logic.',
        actions: ['Events', 'Logs', 'Traceability'],
        accent: 'from-slate-600 to-stone-900',
    },
    {
        key: 'configuration',
        label: 'Configuration',
        path: '/modules/configuration',
        pagePath: '../modules/configuration/pages/ConfigurationPage.tsx',
        group: 'System',
        description: 'Feature flags, environment settings, and module-level preferences.',
        previewPromise: 'Configuration stays declarative and environment-aware.',
        actions: ['Settings', 'Flags', 'Preferences'],
        accent: 'from-cyan-500 to-slate-700',
    },
    {
        key: 'extension',
        label: 'Extension',
        path: '/modules/extension',
        pagePath: '../modules/extension/pages/ExtensionPage.tsx',
        group: 'System',
        description: 'Extension points and add-on workflows for the modular monolith.',
        previewPromise: 'Future add-ons plug into the module shell without reworking the layout.',
        actions: ['Hooks', 'Extensions', 'Plugins'],
        accent: 'from-indigo-500 to-slate-800',
    },
    {
        key: 'vehicle',
        label: 'Vehicle',
        path: '/modules/vehicle',
        pagePath: '../modules/vehicle/pages/VehiclePage.tsx',
        group: 'Operations',
        description: 'Vehicle assets, registration, and operational identity management.',
        previewPromise: 'Transport records remain linked to operational workflows.',
        actions: ['Assets', 'Registration', 'Logs'],
        accent: 'from-sky-600 to-slate-800',
    },
    {
        key: 'vehicle-rental',
        label: 'Vehicle Rental',
        path: '/modules/vehicle-rental',
        pagePath: '../modules/vehicle-rental/pages/VehicleRentalPage.tsx',
        group: 'Operations',
        description: 'Rental agreements, availability, and contract timelines.',
        previewPromise: 'Rental lifecycle events stay managed by backend orchestration.',
        actions: ['Agreements', 'Availability', 'Returns'],
        accent: 'from-cyan-500 to-teal-700',
    },
    {
        key: 'vehicle-service',
        label: 'Vehicle Service',
        path: '/modules/vehicle-service',
        pagePath: '../modules/vehicle-service/pages/VehicleServicePage.tsx',
        group: 'Operations',
        description: 'Service orders, maintenance logs, and repair workflow visibility.',
        previewPromise: 'Service records remain consistent with workshop operations.',
        actions: ['Jobs', 'Inspections', 'Maintenance'],
        accent: 'from-orange-500 to-stone-800',
    },
];

export const moduleCatalogByKey = Object.fromEntries(moduleCatalog.map((module) => [module.key, module])) as Record<
    string,
    ModuleDefinition
>;
