<?php

declare(strict_types=1);

use Modules\Item\Application\Repositories\ComboItemRepositoryInterface;
use Modules\Item\Application\Repositories\ItemAttributeGroupRepositoryInterface;
use Modules\Item\Application\Repositories\ItemAttributeRepositoryInterface;
use Modules\Item\Application\Repositories\ItemAttributeValueRepositoryInterface;
use Modules\Item\Application\Repositories\ItemBrandRepositoryInterface;
use Modules\Item\Application\Repositories\ItemCategoryRepositoryInterface;
use Modules\Item\Application\Repositories\ItemIdentifierRepositoryInterface;
use Modules\Item\Application\Repositories\ItemRepositoryInterface;
use Modules\Item\Application\Repositories\ItemVariantAttributeRepositoryInterface;
use Modules\Item\Application\Repositories\ItemVariantAttributeValueRepositoryInterface;
use Modules\Item\Application\Repositories\ItemVariantRepositoryInterface;

return [
    'precision' => [
        'scale' => 4,
    ],

    'types' => [
        'item' => ['PHYSICAL', 'SERVICE', 'DIGITAL', 'COMBO', 'VARIABLE'],
        'status' => ['DRAFT', 'ACTIVE', 'INACTIVE', 'DISCONTINUED'],
        'attribute' => ['TEXT', 'SELECT', 'NUMBER', 'BOOLEAN'],
        'incentive' => ['fixed', 'percentage'],
        'identifier_technology' => ['barcode_1d', 'barcode_2d', 'qr_code', 'rfid_hf', 'rfid_uhf', 'nfc', 'gs1_epc'],
    ],

    'resources' => [
        'categories' => [
            'repository' => ItemCategoryRepositoryInterface::class,
            'label' => 'Item category',
            'rules' => [
                'organization_unit_id' => ['nullable', 'integer', 'exists:organization_units,id'],
                'parent_id' => ['nullable', 'integer', 'exists:item_categories,id'],
                'name' => ['required', 'string', 'max:255'],
                'code' => ['nullable', 'string', 'max:255'],
                'depth' => ['nullable', 'integer', 'min:0'],
                'path' => ['nullable', 'string', 'max:255'],
                'image_path' => ['nullable', 'string', 'max:255'],
                'is_active' => ['nullable', 'boolean'],
                'description' => ['nullable', 'string'],
                'created_by' => ['nullable', 'integer'],
                'updated_by' => ['nullable', 'integer'],
                'row_version' => ['nullable', 'integer', 'min:1'],
                'metadata' => ['nullable', 'array'],
            ],
        ],
        'brands' => [
            'repository' => ItemBrandRepositoryInterface::class,
            'label' => 'Item brand',
            'rules' => [
                'organization_unit_id' => ['nullable', 'integer', 'exists:organization_units,id'],
                'parent_id' => ['nullable', 'integer', 'exists:item_brands,id'],
                'name' => ['required', 'string', 'max:255'],
                'slug' => ['nullable', 'string', 'max:255'],
                'code' => ['nullable', 'string', 'max:255'],
                'path' => ['nullable', 'string', 'max:255'],
                'image_path' => ['nullable', 'string', 'max:255'],
                'depth' => ['nullable', 'integer', 'min:0'],
                'is_active' => ['nullable', 'boolean'],
                'website' => ['nullable', 'string', 'max:255'],
                'description' => ['nullable', 'string'],
                'row_version' => ['nullable', 'integer', 'min:1'],
                'metadata' => ['nullable', 'array'],
            ],
        ],
        'items' => [
            'repository' => ItemRepositoryInterface::class,
            'label' => 'Item',
            'rules' => [
                'organization_unit_id' => ['nullable', 'integer', 'exists:organization_units,id'],
                'category_id' => ['nullable', 'integer', 'exists:item_categories,id'],
                'brand_id' => ['nullable', 'integer', 'exists:item_brands,id'],
                'type' => ['nullable', 'string'],
                'name' => ['required', 'string', 'max:255'],
                'slug' => ['nullable', 'string', 'max:255'],
                'sku' => ['nullable', 'string', 'max:255'],
                'description' => ['nullable', 'string'],
                'image_path' => ['nullable', 'string', 'max:255'],
                'status' => ['nullable', 'string'],
                'base_uom_id' => ['required', 'integer', 'exists:unit_of_measures,id'],
                'purchase_uom_id' => ['nullable', 'integer', 'exists:unit_of_measures,id'],
                'sales_uom_id' => ['nullable', 'integer', 'exists:unit_of_measures,id'],
                'tax_group_id' => ['nullable', 'integer', 'exists:tax_groups,id'],
                'is_batch_tracked' => ['nullable', 'boolean'],
                'is_lot_tracked' => ['nullable', 'boolean'],
                'is_serial_tracked' => ['nullable', 'boolean'],
                'is_stockable' => ['nullable', 'boolean'],
                'valuation_method' => ['nullable', 'string', 'max:255'],
                'allocation_method' => ['nullable', 'string', 'max:255'],
                'standard_cost' => ['nullable', 'numeric', 'min:0'],
                'income_account_id' => ['nullable', 'integer', 'exists:accounts,id'],
                'cogs_account_id' => ['nullable', 'integer', 'exists:accounts,id'],
                'inventory_account_id' => ['nullable', 'integer', 'exists:accounts,id'],
                'expense_account_id' => ['nullable', 'integer', 'exists:accounts,id'],
                'sales_return_account_id' => ['nullable', 'integer', 'exists:accounts,id'],
                'purchase_return_account_id' => ['nullable', 'integer', 'exists:accounts,id'],
                'inventory_gain_account_id' => ['nullable', 'integer', 'exists:accounts,id'],
                'inventory_loss_account_id' => ['nullable', 'integer', 'exists:accounts,id'],
                'stock_transfer_account_id' => ['nullable', 'integer', 'exists:accounts,id'],
                'wip_account_id' => ['nullable', 'integer', 'exists:accounts,id'],
                'price_variance_account_id' => ['nullable', 'integer', 'exists:accounts,id'],
                'is_active' => ['nullable', 'boolean'],
                'cost_price' => ['nullable', 'numeric', 'min:0'],
                'sales_price' => ['nullable', 'numeric', 'min:0'],
                'estimated_service_time_hours' => ['nullable', 'numeric', 'min:0'],
                'incentive_type' => ['nullable', 'string'],
                'incentive_value' => ['nullable', 'numeric', 'min:0'],
                'minimum_stock' => ['nullable', 'numeric', 'min:0'],
                'maximum_stock' => ['nullable', 'numeric', 'min:0'],
                'reorder_point' => ['nullable', 'numeric', 'min:0'],
                'reorder_quantity' => ['nullable', 'numeric', 'min:0'],
                'safety_stock' => ['nullable', 'numeric', 'min:0'],
                'lead_time_days' => ['nullable', 'integer', 'min:0'],
                'review_period_days' => ['nullable', 'integer', 'min:0'],
                'auto_replenishment_enabled' => ['nullable', 'boolean'],
                'allow_auto_purchase_order' => ['nullable', 'boolean'],
                'row_version' => ['nullable', 'integer', 'min:1'],
                'metadata' => ['nullable', 'array'],
            ],
        ],
        'attribute-groups' => [
            'repository' => ItemAttributeGroupRepositoryInterface::class,
            'label' => 'Item attribute group',
            'rules' => [
                'organization_unit_id' => ['nullable', 'integer', 'exists:organization_units,id'],
                'name' => ['required', 'string', 'max:255'],
                'row_version' => ['nullable', 'integer', 'min:1'],
                'metadata' => ['nullable', 'array'],
            ],
        ],
        'attributes' => [
            'repository' => ItemAttributeRepositoryInterface::class,
            'label' => 'Item attribute',
            'rules' => [
                'organization_unit_id' => ['nullable', 'integer', 'exists:organization_units,id'],
                'group_id' => ['nullable', 'integer', 'exists:item_attribute_groups,id'],
                'name' => ['required', 'string', 'max:255'],
                'type' => ['nullable', 'string'],
                'is_required' => ['nullable', 'boolean'],
                'row_version' => ['nullable', 'integer', 'min:1'],
                'metadata' => ['nullable', 'array'],
            ],
        ],
        'attribute-values' => [
            'repository' => ItemAttributeValueRepositoryInterface::class,
            'label' => 'Item attribute value',
            'rules' => [
                'organization_unit_id' => ['nullable', 'integer', 'exists:organization_units,id'],
                'attribute_id' => ['required', 'integer', 'exists:item_attributes,id'],
                'value' => ['required', 'string', 'max:255'],
                'sort_order' => ['nullable', 'integer', 'min:0'],
                'row_version' => ['nullable', 'integer', 'min:1'],
                'metadata' => ['nullable', 'array'],
            ],
        ],
        'variants' => [
            'repository' => ItemVariantRepositoryInterface::class,
            'label' => 'Item variant',
            'rules' => [
                'organization_unit_id' => ['nullable', 'integer', 'exists:organization_units,id'],
                'item_id' => ['required', 'integer', 'exists:items,id'],
                'sku' => ['nullable', 'string', 'max:255'],
                'name' => ['required', 'string', 'max:255'],
                'is_default' => ['nullable', 'boolean'],
                'is_active' => ['nullable', 'boolean'],
                'cost_price' => ['nullable', 'numeric', 'min:0'],
                'sales_price' => ['nullable', 'numeric', 'min:0'],
                'row_version' => ['nullable', 'integer', 'min:1'],
                'metadata' => ['nullable', 'array'],
            ],
        ],
        'variant-attributes' => [
            'repository' => ItemVariantAttributeRepositoryInterface::class,
            'label' => 'Item variant attribute',
            'rules' => [
                'organization_unit_id' => ['nullable', 'integer', 'exists:organization_units,id'],
                'item_id' => ['required', 'integer', 'exists:items,id'],
                'attribute_id' => ['required', 'integer', 'exists:item_attributes,id'],
                'is_required' => ['nullable', 'boolean'],
                'is_variation_axis' => ['nullable', 'boolean'],
                'display_order' => ['nullable', 'integer', 'min:0'],
                'row_version' => ['nullable', 'integer', 'min:1'],
                'metadata' => ['nullable', 'array'],
            ],
        ],
        'variant-attribute-values' => [
            'repository' => ItemVariantAttributeValueRepositoryInterface::class,
            'label' => 'Item variant attribute value',
            'rules' => [
                'organization_unit_id' => ['nullable', 'integer', 'exists:organization_units,id'],
                'variant_id' => ['required', 'integer', 'exists:item_variants,id'],
                'attribute_value_id' => ['required', 'integer', 'exists:item_attribute_values,id'],
                'row_version' => ['nullable', 'integer', 'min:1'],
                'metadata' => ['nullable', 'array'],
            ],
        ],
        'combo-items' => [
            'repository' => ComboItemRepositoryInterface::class,
            'label' => 'Combo item component',
            'rules' => [
                'organization_unit_id' => ['nullable', 'integer', 'exists:organization_units,id'],
                'combo_item_id' => ['required', 'integer', 'exists:items,id'],
                'component_item_id' => ['required', 'integer', 'exists:items,id'],
                'component_variant_id' => ['nullable', 'integer', 'exists:item_variants,id'],
                'sort_order' => ['nullable', 'integer', 'min:0'],
                'quantity' => ['required', 'numeric', 'gt:0'],
                'uom_id' => ['required', 'integer', 'exists:unit_of_measures,id'],
                'standard_cost' => ['nullable', 'numeric', 'min:0'],
                'cost_price' => ['nullable', 'numeric', 'min:0'],
                'sales_price' => ['nullable', 'numeric', 'min:0'],
                'incentive_type' => ['nullable', 'string'],
                'incentive_value' => ['nullable', 'numeric', 'min:0'],
                'row_version' => ['nullable', 'integer', 'min:1'],
                'metadata' => ['nullable', 'array'],
            ],
        ],
        'identifiers' => [
            'repository' => ItemIdentifierRepositoryInterface::class,
            'label' => 'Item identifier',
            'rules' => [
                'organization_unit_id' => ['nullable', 'integer', 'exists:organization_units,id'],
                'item_id' => ['required', 'integer', 'exists:items,id'],
                'variant_id' => ['nullable', 'integer', 'exists:item_variants,id'],
                'batch_id' => ['nullable', 'integer', 'exists:batches,id'],
                'serial_id' => ['nullable', 'integer', 'exists:serials,id'],
                'technology' => ['nullable', 'string'],
                'format' => ['nullable', 'string', 'max:255'],
                'value' => ['required', 'string', 'max:255'],
                'gs1_company_prefix' => ['nullable', 'string', 'max:255'],
                'gs1_application_identifiers' => ['nullable', 'array'],
                'is_primary' => ['nullable', 'boolean'],
                'is_active' => ['nullable', 'boolean'],
                'row_version' => ['nullable', 'integer', 'min:1'],
                'metadata' => ['nullable', 'array'],
            ],
        ],
    ],
];
