export const PLATFORM_PERMISSION = {
    tenantsView: 'platform.tenants.view',
    tenantsCreate: 'platform.tenants.create',
    tenantsUpdate: 'platform.tenants.update',
    tenantsOnboard: 'platform.tenants.onboard',
    tenantsLifecycle: 'platform.tenants.lifecycle',
    tenantDomainsManage: 'platform.tenant_domains.manage',
    tenantSubscriptionsManage: 'platform.tenant_subscriptions.manage',
    plansView: 'platform.plans.view',
    plansManage: 'platform.plans.manage',
    configurationView: 'platform.configuration.view',
    configurationManage: 'platform.configuration.manage',
    secretsManage: 'platform.secrets.manage',
    auditView: 'platform.audit.view',
    auditSensitiveView: 'platform.audit.sensitive.view',
    operatorsView: 'platform.operators.view',
    operatorsManage: 'platform.operators.manage',
    sessionsView: 'platform.sessions.view',
    sessionsManage: 'platform.sessions.manage',
    mfaManage: 'platform.mfa.manage',
    healthView: 'platform.health.view',
    healthManage: 'platform.health.manage',
} as const;
