<?php

declare(strict_types=1);

namespace Modules\User\Constants;

final class UserErrorCode
{
    public const INVALID_VALUE = 'USER_INVALID_VALUE';

    public const NOT_FOUND = 'USER_NOT_FOUND';

    public const TENANT_REQUIRED = 'USER_TENANT_REQUIRED';

    public const TENANT_MISMATCH = 'USER_TENANT_MISMATCH';

    public const ORGANIZATION_UNIT_NOT_FOUND = 'USER_ORGANIZATION_UNIT_NOT_FOUND';

    public const ASSIGNMENT_NOT_FOUND = 'USER_ASSIGNMENT_NOT_FOUND';

    public const ROLE_NOT_FOUND = 'USER_ROLE_NOT_FOUND';

    public const PERMISSION_NOT_FOUND = 'USER_PERMISSION_NOT_FOUND';

    public const PROTECTED_ACCOUNT = 'USER_PROTECTED_ACCOUNT';

    public const LAST_ADMIN = 'USER_LAST_ADMIN';

    public const STALE_RECORD = 'USER_STALE_RECORD';

    public const IDENTITY_REFERENCE_INVALID = 'USER_IDENTITY_REFERENCE_INVALID';

    public const DUPLICATE_EMAIL = 'USER_DUPLICATE_EMAIL';

    public const DUPLICATE_USERNAME = 'USER_DUPLICATE_USERNAME';

    public const DUPLICATE_ROLE = 'USER_DUPLICATE_ROLE';

    public const DUPLICATE_PERMISSION = 'USER_DUPLICATE_PERMISSION';

    public const DUPLICATE_ROLE_PERMISSION = 'USER_DUPLICATE_ROLE_PERMISSION';

    public const DUPLICATE_USER_ROLE = 'USER_DUPLICATE_USER_ROLE';

    public const DUPLICATE_USER_PERMISSION = 'USER_DUPLICATE_USER_PERMISSION';

    public const DUPLICATE_USER_TENANT = 'USER_DUPLICATE_USER_TENANT';

    public const DUPLICATE_USER_DOCUMENT = 'USER_DUPLICATE_USER_DOCUMENT';

    public const DUPLICATE_USER_DEVICE = 'USER_DUPLICATE_USER_DEVICE';
}
