<?php

namespace App\Modules\ReportingManagement\Repositories;

use App\Core\Base\BaseRepository;
use App\Modules\ReportingManagement\Models\Report;

class ReportRepository extends BaseRepository
{
    public function __construct(Report $model)
    {
        parent::__construct($model);
    }

    /**
     * Search reports by various criteria
     */
    public function search(array $criteria)
    {
        $query = $this->model->query();

        if (!empty($criteria['search'])) {
            $search = $criteria['search'];
            $query->where(function ($q) use ($search) {
                $q->where('name', 'like', "%{$search}%")
                    ->orWhere('report_code', 'like', "%{$search}%")
                    ->orWhere('description', 'like', "%{$search}%");
            });
        }

        if (!empty($criteria['report_type'])) {
            $query->where('report_type', $criteria['report_type']);
        }

        if (!empty($criteria['category'])) {
            $query->where('category', $criteria['category']);
        }

        if (!empty($criteria['status'])) {
            $query->where('status', $criteria['status']);
        }

        if (!empty($criteria['is_active'])) {
            $query->where('is_active', $criteria['is_active']);
        }

        if (!empty($criteria['generated_by'])) {
            $query->where('generated_by', $criteria['generated_by']);
        }

        if (!empty($criteria['tenant_id'])) {
            $query->where('tenant_id', $criteria['tenant_id']);
        }

        return $query->with(['generatedBy'])
            ->orderBy('created_at', 'desc')
            ->paginate($criteria['per_page'] ?? 15);
    }

    /**
     * Find report by report code
     */
    public function findByReportCode(string $reportCode): ?Report
    {
        return $this->model->where('report_code', $reportCode)->first();
    }

    /**
     * Get reports by type
     */
    public function getByType(string $type)
    {
        return $this->model->where('report_type', $type)->with(['generatedBy'])->get();
    }

    /**
     * Get reports by category
     */
    public function getByCategory(string $category)
    {
        return $this->model->where('category', $category)->with(['generatedBy'])->get();
    }

    /**
     * Get reports by status
     */
    public function getByStatus(string $status)
    {
        return $this->model->where('status', $status)->with(['generatedBy'])->get();
    }

    /**
     * Get active reports
     */
    public function getActive()
    {
        return $this->model->where('is_active', true)->get();
    }

    /**
     * Get completed reports
     */
    public function getCompleted()
    {
        return $this->model->where('status', 'completed')->with(['generatedBy'])->get();
    }

    /**
     * Get pending reports
     */
    public function getPending()
    {
        return $this->model->where('status', 'pending')->with(['generatedBy'])->get();
    }

    /**
     * Get reports generated by user
     */
    public function getByUser(int $userId)
    {
        return $this->model->where('generated_by', $userId)
            ->orderBy('created_at', 'desc')
            ->get();
    }

    /**
     * Get reports by date range
     */
    public function getByDateRange($startDate, $endDate)
    {
        return $this->model->whereBetween('created_at', [$startDate, $endDate])
            ->with(['generatedBy'])
            ->orderBy('created_at', 'desc')
            ->get();
    }

    /**
     * Get scheduled reports
     */
    public function getScheduled()
    {
        return $this->model->where('is_scheduled', true)
            ->where('is_active', true)
            ->get();
    }

    /**
     * Get favorite reports
     */
    public function getFavorites()
    {
        return $this->model->where('is_favorite', true)
            ->where('is_active', true)
            ->get();
    }
}
