<?php

declare(strict_types=1);

return [
    'file_storage' => [
        'default_disk' => env('CORE_FILE_STORAGE_DISK', env('FILESYSTEM_DISK', 'local')),
    ],
    'slug' => [
        'fallback' => env('CORE_SLUG_FALLBACK', 'n-a'),
    ],
    'current_user' => [
        'middleware_alias' => env('CORE_CURRENT_USER_MIDDLEWARE_ALIAS', 'current.user'),
        'required' => (bool) env('CORE_CURRENT_USER_REQUIRED', true),
        'request_attribute' => env('CORE_CURRENT_USER_REQUEST_ATTRIBUTE', 'current_user'),
        'id_attribute' => env('CORE_CURRENT_USER_ID_ATTRIBUTE', 'current_user_id'),
        'guard_attribute' => env('CORE_CURRENT_USER_GUARD_ATTRIBUTE', 'current_user_guard'),
        'provider_attribute' => env('CORE_CURRENT_USER_PROVIDER_ATTRIBUTE', 'current_user_provider'),
        'tenant_attribute' => env('CORE_CURRENT_TENANT_ATTRIBUTE', 'current_tenant_id'),
        'organization_unit_attribute' => env('CORE_CURRENT_ORGANIZATION_UNIT_ATTRIBUTE', 'current_organization_unit_id'),
        'application_attribute' => env('CORE_CURRENT_APPLICATION_ATTRIBUTE', 'current_application_id'),
        'token_payload_attribute' => env('CORE_CURRENT_USER_TOKEN_PAYLOAD_ATTRIBUTE', 'auth_access_token'),
        'tenant_input_keys' => ['tenant_id'],
        'tenant_route_keys' => ['tenant_id', 'tenant'],
        'tenant_header_keys' => ['X-Tenant-Id', 'X-Tenant'],
        'application_input_keys' => ['application_id', 'app_id', 'client_id'],
        'application_header_keys' => ['X-Application-Id', 'X-App-Id', 'X-Client-Id'],
    ],
    'current_tenant' => [
        'middleware_alias' => env('CORE_CURRENT_TENANT_MIDDLEWARE_ALIAS', 'current.tenant'),
        'required' => (bool) env('CORE_CURRENT_TENANT_REQUIRED', true),
        'request_attribute' => env('CORE_CURRENT_TENANT_REQUEST_ATTRIBUTE', 'current_tenant'),
        'id_attribute' => env('CORE_CURRENT_TENANT_ID_ATTRIBUTE', 'current_tenant_id'),
        'code_attribute' => env('CORE_CURRENT_TENANT_CODE_ATTRIBUTE', 'current_tenant_code'),
        'uuid_attribute' => env('CORE_CURRENT_TENANT_UUID_ATTRIBUTE', 'current_tenant_uuid'),
        'isolation_key_attribute' => env('CORE_CURRENT_TENANT_ISOLATION_KEY_ATTRIBUTE', 'current_tenant_isolation_key'),
        'domain_attribute' => env('CORE_CURRENT_TENANT_DOMAIN_ATTRIBUTE', 'current_tenant_domain'),
        'status_attribute' => env('CORE_CURRENT_TENANT_STATUS_ATTRIBUTE', 'current_tenant_status'),
        'active_attribute' => env('CORE_CURRENT_TENANT_ACTIVE_ATTRIBUTE', 'current_tenant_is_active'),
        'source_attribute' => env('CORE_CURRENT_TENANT_SOURCE_ATTRIBUTE', 'current_tenant_source'),
        'application_attribute' => env('CORE_CURRENT_APPLICATION_ATTRIBUTE', 'current_application_id'),
        'id_input_keys' => ['tenant_id'],
        'id_route_keys' => ['tenant_id'],
        'id_header_keys' => ['X-Tenant-Id'],
        'code_input_keys' => ['tenant_code'],
        'code_route_keys' => ['tenant', 'tenant_code'],
        'code_header_keys' => ['X-Tenant-Code'],
        'uuid_input_keys' => ['tenant_uuid'],
        'uuid_route_keys' => ['tenant_uuid'],
        'uuid_header_keys' => ['X-Tenant-Uuid'],
        'isolation_key_input_keys' => ['tenant_isolation_key'],
        'isolation_key_route_keys' => ['tenant_isolation_key'],
        'isolation_key_header_keys' => ['X-Tenant-Isolation-Key'],
        'domain_input_keys' => ['tenant_domain'],
        'domain_header_keys' => ['X-Tenant-Domain'],
        'application_input_keys' => ['application_id', 'app_id', 'client_id'],
        'application_header_keys' => ['X-Application-Id', 'X-App-Id', 'X-Client-Id'],
    ],
];
