<?php

declare(strict_types=1);

use Modules\Sales\Application\Repositories\GdnHeaderRepositoryInterface;
use Modules\Sales\Application\Repositories\GdnLineRepositoryInterface;
use Modules\Sales\Application\Repositories\SalesOrderLineRepositoryInterface;
use Modules\Sales\Application\Repositories\SalesOrderRepositoryInterface;
use Modules\Sales\Application\Repositories\SalesReturnLineRepositoryInterface;
use Modules\Sales\Application\Repositories\SalesReturnRepositoryInterface;

return [
    'precision' => [
        'scale' => 4,
    ],

    'order_statuses' => ['draft', 'confirmed', 'partially_delivered', 'delivered', 'cancelled'],
    'gdn_statuses' => ['draft', 'confirmed', 'cancelled'],
    'return_statuses' => ['draft', 'approved', 'closed', 'cancelled'],
    'invoice_statuses' => ['not_invoiced', 'partially_invoiced', 'closed'],
    'discount_types' => ['fixed', 'percentage'],
    'return_conditions' => ['good', 'damaged', 'expired', 'defective'],
    'return_dispositions' => ['restock', 'scrap', 'return_to_vendor'],

    'calculation' => [
        'header_discount_base' => 'net_after_line_discount',
    ],

    'calculated_columns' => [
        'row_version',
        'subtotal',
        'line_tax_total',
        'line_discount_total',
        'line_restocking_total',
        'header_discount_amount',
        'discount_total',
        'tax_total',
        'grand_total',
        'paid_amount',
        'balance',
        'discount_amount',
        'gross_amount',
        'line_total',
        'line_total_with_tax',
    ],

    'decimal_columns' => [
        'exchange_rate',
        'header_discount_value',
        'header_discount_amount',
        'header_tax_amount',
        'debit_note_total',
        'credit_note_total',
        'ordered_qty',
        'delivered_qty',
        'rejected_qty',
        'invoiced_qty',
        'return_qty',
        'unit_price',
        'unit_cost',
        'discount_value',
        'discount_amount',
        'tax_amount',
        'restocking_fee',
    ],

    'immutable' => [
        'sales_orders' => [
            'status_column' => 'status',
            'statuses' => ['delivered', 'cancelled'],
        ],
        'gdn_headers' => [
            'status_column' => 'status',
            'statuses' => ['confirmed', 'cancelled'],
        ],
        'sales_returns' => [
            'status_column' => 'status',
            'statuses' => ['closed', 'cancelled'],
        ],
    ],

    'resources' => [
        'sales_orders' => [
            'repository' => SalesOrderRepositoryInterface::class,
            'label' => 'Sales order',
            'rules' => [
                'row_version' => ['nullable', 'integer', 'min:1'],
                'organization_unit_id' => ['nullable', 'integer', 'exists:organization_units,id'],
                'reference' => ['nullable', 'string', 'max:255'],
                'customer_id' => ['required', 'integer', 'exists:customers,id'],
                'warehouse_id' => ['required', 'integer', 'exists:warehouses,id'],
                'so_number' => ['required', 'string', 'max:255'],
                'status' => ['nullable', 'string'],
                'invoice_status' => ['nullable', 'string'],
                'currency_id' => ['nullable', 'integer', 'exists:currencies,id'],
                'exchange_rate' => ['nullable', 'numeric', 'min:0'],
                'order_date' => ['required', 'date'],
                'requested_delivery_date' => ['nullable', 'date', 'after_or_equal:order_date'],
                'price_list_id' => ['nullable', 'integer', 'exists:price_lists,id'],
                'header_discount_type' => ['nullable', 'string'],
                'header_discount_value' => ['nullable', 'numeric', 'min:0'],
                'header_tax_group_id' => ['nullable', 'integer', 'exists:tax_groups,id'],
                'header_tax_amount' => ['nullable', 'numeric', 'min:0'],
                'debit_note_total' => ['nullable', 'numeric', 'min:0'],
                'credit_note_total' => ['nullable', 'numeric', 'min:0'],
                'notes' => ['nullable', 'string'],
                'created_by' => ['nullable', 'integer'],
                'metadata' => ['nullable', 'array'],
            ],
        ],
        'sales_order_lines' => [
            'repository' => SalesOrderLineRepositoryInterface::class,
            'label' => 'Sales order line',
            'rules' => [
                'row_version' => ['nullable', 'integer', 'min:1'],
                'organization_unit_id' => ['nullable', 'integer', 'exists:organization_units,id'],
                'reference' => ['nullable', 'string', 'max:255'],
                'sales_order_id' => ['required', 'integer', 'exists:sales_orders,id'],
                'item_id' => ['required', 'integer', 'exists:items,id'],
                'variant_id' => ['nullable', 'integer', 'exists:item_variants,id'],
                'description' => ['nullable', 'string'],
                'uom_id' => ['required', 'integer', 'exists:unit_of_measures,id'],
                'ordered_qty' => ['required', 'numeric', 'min:0'],
                'delivered_qty' => ['nullable', 'numeric', 'min:0'],
                'rejected_qty' => ['nullable', 'numeric', 'min:0'],
                'invoiced_qty' => ['nullable', 'numeric', 'min:0'],
                'unit_price' => ['required', 'numeric', 'min:0'],
                'discount_type' => ['nullable', 'string'],
                'discount_value' => ['nullable', 'numeric', 'min:0'],
                'tax_group_id' => ['nullable', 'integer', 'exists:tax_groups,id'],
                'tax_amount' => ['nullable', 'numeric', 'min:0'],
                'account_id' => ['nullable', 'integer', 'exists:accounts,id'],
                'metadata' => ['nullable', 'array'],
            ],
        ],
        'gdn_headers' => [
            'repository' => GdnHeaderRepositoryInterface::class,
            'label' => 'GDN header',
            'rules' => [
                'row_version' => ['nullable', 'integer', 'min:1'],
                'organization_unit_id' => ['nullable', 'integer', 'exists:organization_units,id'],
                'reference' => ['nullable', 'string', 'max:255'],
                'customer_id' => ['required', 'integer', 'exists:customers,id'],
                'warehouse_id' => ['required', 'integer', 'exists:warehouses,id'],
                'sales_order_id' => ['nullable', 'integer', 'exists:sales_orders,id'],
                'gdn_number' => ['required', 'string', 'max:255'],
                'status' => ['nullable', 'string'],
                'invoice_status' => ['nullable', 'string'],
                'currency_id' => ['nullable', 'integer', 'exists:currencies,id'],
                'exchange_rate' => ['nullable', 'numeric', 'min:0'],
                'delivered_date' => ['required', 'date'],
                'price_list_id' => ['nullable', 'integer', 'exists:price_lists,id'],
                'header_discount_type' => ['nullable', 'string'],
                'header_discount_value' => ['nullable', 'numeric', 'min:0'],
                'header_tax_group_id' => ['nullable', 'integer', 'exists:tax_groups,id'],
                'header_tax_amount' => ['nullable', 'numeric', 'min:0'],
                'debit_note_total' => ['nullable', 'numeric', 'min:0'],
                'credit_note_total' => ['nullable', 'numeric', 'min:0'],
                'notes' => ['nullable', 'string'],
                'created_by' => ['nullable', 'integer'],
                'metadata' => ['nullable', 'array'],
            ],
        ],
        'gdn_lines' => [
            'repository' => GdnLineRepositoryInterface::class,
            'label' => 'GDN line',
            'rules' => [
                'row_version' => ['nullable', 'integer', 'min:1'],
                'organization_unit_id' => ['nullable', 'integer', 'exists:organization_units,id'],
                'reference' => ['nullable', 'string', 'max:255'],
                'gdn_header_id' => ['required', 'integer', 'exists:gdn_headers,id'],
                'sales_order_line_id' => ['nullable', 'integer', 'exists:sales_order_lines,id'],
                'item_id' => ['required', 'integer', 'exists:items,id'],
                'variant_id' => ['nullable', 'integer', 'exists:item_variants,id'],
                'batch_id' => ['nullable', 'integer', 'exists:batches,id'],
                'serial_id' => ['nullable', 'integer', 'exists:serials,id'],
                'warehouse_id' => ['nullable', 'integer', 'exists:warehouses,id'],
                'location_id' => ['nullable', 'integer', 'exists:warehouse_locations,id'],
                'description' => ['nullable', 'string'],
                'uom_id' => ['required', 'integer', 'exists:unit_of_measures,id'],
                'delivered_qty' => ['required', 'numeric', 'min:0'],
                'rejected_qty' => ['nullable', 'numeric', 'min:0'],
                'invoiced_qty' => ['nullable', 'numeric', 'min:0'],
                'unit_price' => ['required', 'numeric', 'min:0'],
                'discount_type' => ['nullable', 'string'],
                'discount_value' => ['nullable', 'numeric', 'min:0'],
                'tax_group_id' => ['nullable', 'integer', 'exists:tax_groups,id'],
                'tax_amount' => ['nullable', 'numeric', 'min:0'],
                'account_id' => ['nullable', 'integer', 'exists:accounts,id'],
                'metadata' => ['nullable', 'array'],
            ],
        ],
        'sales_returns' => [
            'repository' => SalesReturnRepositoryInterface::class,
            'label' => 'Sales return',
            'rules' => [
                'row_version' => ['nullable', 'integer', 'min:1'],
                'organization_unit_id' => ['nullable', 'integer', 'exists:organization_units,id'],
                'reference' => ['nullable', 'string', 'max:255'],
                'customer_id' => ['required', 'integer', 'exists:customers,id'],
                'original_sales_order_id' => ['nullable', 'integer', 'exists:sales_orders,id'],
                'original_gdn_id' => ['nullable', 'integer', 'exists:gdn_headers,id'],
                'original_invoice_id' => ['nullable', 'integer', 'exists:invoices,id'],
                'return_number' => ['required', 'string', 'max:255'],
                'status' => ['nullable', 'string'],
                'currency_id' => ['nullable', 'integer', 'exists:currencies,id'],
                'exchange_rate' => ['nullable', 'numeric', 'min:0'],
                'return_date' => ['required', 'date'],
                'return_reason' => ['nullable', 'string', 'max:255'],
                'header_discount_type' => ['nullable', 'string'],
                'header_discount_value' => ['nullable', 'numeric', 'min:0'],
                'header_tax_group_id' => ['nullable', 'integer', 'exists:tax_groups,id'],
                'header_tax_amount' => ['nullable', 'numeric', 'min:0'],
                'debit_note_total' => ['nullable', 'numeric', 'min:0'],
                'credit_note_total' => ['nullable', 'numeric', 'min:0'],
                'notes' => ['nullable', 'string'],
                'created_by' => ['nullable', 'integer'],
                'metadata' => ['nullable', 'array'],
            ],
        ],
        'sales_return_lines' => [
            'repository' => SalesReturnLineRepositoryInterface::class,
            'label' => 'Sales return line',
            'rules' => [
                'row_version' => ['nullable', 'integer', 'min:1'],
                'organization_unit_id' => ['nullable', 'integer', 'exists:organization_units,id'],
                'reference' => ['nullable', 'string', 'max:255'],
                'sales_return_id' => ['required', 'integer', 'exists:sales_returns,id'],
                'original_gdn_line_id' => ['nullable', 'integer', 'exists:gdn_lines,id'],
                'original_sales_order_line_id' => ['nullable', 'integer', 'exists:sales_order_lines,id'],
                'item_id' => ['required', 'integer', 'exists:items,id'],
                'variant_id' => ['nullable', 'integer', 'exists:item_variants,id'],
                'batch_id' => ['nullable', 'integer', 'exists:batches,id'],
                'serial_id' => ['nullable', 'integer', 'exists:serials,id'],
                'warehouse_id' => ['nullable', 'integer', 'exists:warehouses,id'],
                'location_id' => ['nullable', 'integer', 'exists:warehouse_locations,id'],
                'description' => ['nullable', 'string'],
                'uom_id' => ['required', 'integer', 'exists:unit_of_measures,id'],
                'return_qty' => ['required', 'numeric', 'min:0'],
                'unit_price' => ['required', 'numeric', 'min:0'],
                'restocking_fee' => ['nullable', 'numeric', 'min:0'],
                'condition' => ['nullable', 'string'],
                'disposition' => ['nullable', 'string'],
                'quality_check_notes' => ['nullable', 'string'],
                'discount_type' => ['nullable', 'string'],
                'discount_value' => ['nullable', 'numeric', 'min:0'],
                'tax_group_id' => ['nullable', 'integer', 'exists:tax_groups,id'],
                'tax_amount' => ['nullable', 'numeric', 'min:0'],
                'account_id' => ['nullable', 'integer', 'exists:accounts,id'],
                'metadata' => ['nullable', 'array'],
            ],
        ],
    ],
];
