<?php

declare(strict_types=1);

use Modules\VehicleService\Application\Repositories\VehicleServiceDiagnosticLineRepositoryInterface;
use Modules\VehicleService\Application\Repositories\VehicleServiceDiagnosticRepositoryInterface;
use Modules\VehicleService\Application\Repositories\VehicleServiceInspectionLineRepositoryInterface;
use Modules\VehicleService\Application\Repositories\VehicleServiceInspectionRepositoryInterface;
use Modules\VehicleService\Application\Repositories\VehicleServiceJobCardLineRepositoryInterface;
use Modules\VehicleService\Application\Repositories\VehicleServiceJobCardRepositoryInterface;
use Modules\VehicleService\Application\Repositories\VehicleServiceLaborAssignmentRepositoryInterface;
use Modules\VehicleService\Application\Repositories\VehicleServiceLaborItemRepositoryInterface;
use Modules\VehicleService\Application\Repositories\VehicleServiceNonInventoryItemRepositoryInterface;
use Modules\VehicleService\Application\Repositories\VehicleServiceTypeRepositoryInterface;

return [
    'precision' => [
        'scale' => 4,
    ],

    'priorities' => ['low', 'medium', 'high', 'critical'],
    'job_card_statuses' => ['open', 'in_progress', 'waiting_parts', 'completed', 'invoiced', 'cancelled'],
    'discount_types' => ['fixed', 'percentage'],
    'incentive_types' => ['fixed', 'percentage'],
    'assignment_roles' => ['lead', 'assistant', 'supervisor'],
    'service_phases' => ['pre', 'post'],
    'overall_results' => ['pass', 'fail', 'warning', 'not_applicable'],
    'inspection_line_results' => ['pass', 'fail', 'flag', 'not_tested'],
    'severities' => ['info', 'warning', 'critical'],

    'calculation' => [
        'header_discount_base' => 'net_after_line_discount',
    ],

    'calculated_columns' => [
        'row_version',
        'subtotal',
        'line_tax_total',
        'line_discount_total',
        'non_inventory_item_subtotal',
        'non_inventory_item_tax_total',
        'non_inventory_item_discount_total',
        'labor_item_subtotal',
        'labor_item_tax_total',
        'labor_item_discount_total',
        'header_discount_amount',
        'discount_total',
        'tax_total',
        'grand_total',
        'paid_amount',
        'balance',
        'discount_amount',
        'gross_amount',
        'line_total',
        'line_total_with_tax',
        'incentive_amount',
    ],

    'decimal_columns' => [
        'standard_hours',
        'exchange_rate',
        'estimated_hours',
        'actual_hours',
        'header_discount_value',
        'header_discount_amount',
        'header_tax_amount',
        'debit_note_total',
        'credit_note_total',
        'quantity',
        'unit_price',
        'unit_cost',
        'discount_value',
        'discount_amount',
        'tax_amount',
        'incentive_value',
        'incentive_amount',
        'hours_worked',
        'hourly_rate',
    ],

    'immutable' => [
        'job_cards' => [
            'status_column' => 'status',
            'statuses' => ['invoiced', 'cancelled'],
        ],
        'diagnostics' => [
            'after_create' => false,
        ],
        'inspections' => [
            'after_create' => false,
        ],
    ],

    'resources' => [
        'service_types' => [
            'repository' => VehicleServiceTypeRepositoryInterface::class,
            'label' => 'Vehicle service type',
            'rules' => [
                'row_version' => ['nullable', 'integer', 'min:1'],
                'organization_unit_id' => ['nullable', 'integer', 'exists:organization_units,id'],
                'parent_id' => ['nullable', 'integer', 'exists:vehicle_service_types,id'],
                'name' => ['required', 'string', 'max:255'],
                'code' => ['nullable', 'string', 'max:255'],
                'path' => ['nullable', 'string', 'max:255'],
                'depth' => ['nullable', 'integer', 'min:0'],
                'description' => ['nullable', 'string'],
                'standard_hours' => ['nullable', 'numeric', 'min:0'],
                'is_active' => ['nullable', 'boolean'],
                'created_by' => ['nullable', 'integer'],
                'updated_by' => ['nullable', 'integer'],
                'metadata' => ['nullable', 'array'],
            ],
        ],
        'job_cards' => [
            'repository' => VehicleServiceJobCardRepositoryInterface::class,
            'label' => 'Vehicle service job card',
            'rules' => [
                'row_version' => ['nullable', 'integer', 'min:1'],
                'organization_unit_id' => ['nullable', 'integer', 'exists:organization_units,id'],
                'job_card_number' => ['required', 'string', 'max:255'],
                'reference' => ['nullable', 'string', 'max:255'],
                'service_type_id' => ['nullable', 'integer', 'exists:vehicle_service_types,id'],
                'customer_id' => ['nullable', 'integer', 'exists:customers,id'],
                'vehicle_id' => ['nullable', 'integer', 'exists:vehicles,id'],
                'warehouse_id' => ['nullable', 'integer', 'exists:warehouses,id'],
                'priority' => ['nullable', 'string'],
                'status' => ['nullable', 'string'],
                'currency_id' => ['nullable', 'integer', 'exists:currencies,id'],
                'exchange_rate' => ['nullable', 'numeric', 'min:0'],
                'reported_issue' => ['nullable', 'string'],
                'resolution_notes' => ['nullable', 'string'],
                'start_datetime' => ['nullable', 'date'],
                'completed_datetime' => ['nullable', 'date'],
                'estimated_hours' => ['nullable', 'numeric', 'min:0'],
                'actual_hours' => ['nullable', 'numeric', 'min:0'],
                'promised_delivery_date_time' => ['nullable', 'date'],
                'warranty_eligible' => ['nullable', 'boolean'],
                'created_by' => ['nullable', 'integer'],
                'updated_by' => ['nullable', 'integer'],
                'price_list_id' => ['nullable', 'integer', 'exists:price_lists,id'],
                'start_odometer' => ['nullable', 'integer', 'min:0'],
                'end_odometer' => ['nullable', 'integer', 'min:0'],
                'next_service_odometer' => ['nullable', 'integer', 'min:0'],
                'next_service_date' => ['nullable', 'date'],
                'assigned_to' => ['nullable', 'integer', 'exists:employees,id'],
                'header_discount_type' => ['nullable', 'string'],
                'header_discount_value' => ['nullable', 'numeric', 'min:0'],
                'header_tax_group_id' => ['nullable', 'integer', 'exists:tax_groups,id'],
                'header_tax_amount' => ['nullable', 'numeric', 'min:0'],
                'debit_note_total' => ['nullable', 'numeric', 'min:0'],
                'credit_note_total' => ['nullable', 'numeric', 'min:0'],
                'notes' => ['nullable', 'string'],
                'metadata' => ['nullable', 'array'],
            ],
        ],
        'job_card_lines' => [
            'repository' => VehicleServiceJobCardLineRepositoryInterface::class,
            'label' => 'Vehicle service job card line',
            'rules' => [
                'row_version' => ['nullable', 'integer', 'min:1'],
                'organization_unit_id' => ['nullable', 'integer', 'exists:organization_units,id'],
                'reference' => ['nullable', 'string', 'max:255'],
                'job_card_id' => ['required', 'integer', 'exists:vehicle_service_job_cards,id'],
                'item_id' => ['required', 'integer', 'exists:items,id'],
                'variant_id' => ['nullable', 'integer', 'exists:item_variants,id'],
                'batch_id' => ['nullable', 'integer', 'exists:batches,id'],
                'serial_id' => ['nullable', 'integer', 'exists:serials,id'],
                'warehouse_id' => ['nullable', 'integer', 'exists:warehouses,id'],
                'location_id' => ['nullable', 'integer', 'exists:warehouse_locations,id'],
                'description' => ['nullable', 'string'],
                'uom_id' => ['required', 'integer', 'exists:unit_of_measures,id'],
                'quantity' => ['required', 'numeric', 'min:0'],
                'unit_price' => ['required', 'numeric', 'min:0'],
                'unit_cost' => ['nullable', 'numeric', 'min:0'],
                'discount_type' => ['nullable', 'string'],
                'discount_value' => ['nullable', 'numeric', 'min:0'],
                'tax_group_id' => ['nullable', 'integer', 'exists:tax_groups,id'],
                'tax_amount' => ['nullable', 'numeric', 'min:0'],
                'account_id' => ['nullable', 'integer', 'exists:accounts,id'],
                'metadata' => ['nullable', 'array'],
            ],
        ],
        'labor_items' => [
            'repository' => VehicleServiceLaborItemRepositoryInterface::class,
            'label' => 'Vehicle service labor item',
            'rules' => [
                'row_version' => ['nullable', 'integer', 'min:1'],
                'organization_unit_id' => ['nullable', 'integer', 'exists:organization_units,id'],
                'reference' => ['nullable', 'string', 'max:255'],
                'job_card_id' => ['required', 'integer', 'exists:vehicle_service_job_cards,id'],
                'item_id' => ['required', 'integer', 'exists:items,id'],
                'combo_item_id' => ['nullable', 'integer', 'exists:combo_items,id'],
                'description' => ['nullable', 'string'],
                'uom_id' => ['required', 'integer', 'exists:unit_of_measures,id'],
                'quantity' => ['required', 'numeric', 'min:0'],
                'unit_price' => ['required', 'numeric', 'min:0'],
                'unit_cost' => ['nullable', 'numeric', 'min:0'],
                'discount_type' => ['nullable', 'string'],
                'discount_value' => ['nullable', 'numeric', 'min:0'],
                'tax_group_id' => ['nullable', 'integer', 'exists:tax_groups,id'],
                'tax_amount' => ['nullable', 'numeric', 'min:0'],
                'incentive_type' => ['nullable', 'string'],
                'incentive_value' => ['nullable', 'numeric', 'min:0'],
                'account_id' => ['nullable', 'integer', 'exists:accounts,id'],
                'metadata' => ['nullable', 'array'],
            ],
        ],
        'non_inventory_items' => [
            'repository' => VehicleServiceNonInventoryItemRepositoryInterface::class,
            'label' => 'Vehicle service non-inventory item',
            'rules' => [
                'row_version' => ['nullable', 'integer', 'min:1'],
                'organization_unit_id' => ['nullable', 'integer', 'exists:organization_units,id'],
                'reference' => ['nullable', 'string', 'max:255'],
                'job_card_id' => ['required', 'integer', 'exists:vehicle_service_job_cards,id'],
                'name' => ['required', 'string', 'max:255'],
                'description' => ['nullable', 'string'],
                'uom_id' => ['required', 'integer', 'exists:unit_of_measures,id'],
                'quantity' => ['required', 'numeric', 'min:0'],
                'unit_price' => ['required', 'numeric', 'min:0'],
                'unit_cost' => ['nullable', 'numeric', 'min:0'],
                'discount_type' => ['nullable', 'string'],
                'discount_value' => ['nullable', 'numeric', 'min:0'],
                'tax_group_id' => ['nullable', 'integer', 'exists:tax_groups,id'],
                'tax_amount' => ['nullable', 'numeric', 'min:0'],
                'account_id' => ['nullable', 'integer', 'exists:accounts,id'],
                'metadata' => ['nullable', 'array'],
            ],
        ],
        'labor_assignments' => [
            'repository' => VehicleServiceLaborAssignmentRepositoryInterface::class,
            'label' => 'Vehicle service labor assignment',
            'rules' => [
                'row_version' => ['nullable', 'integer', 'min:1'],
                'organization_unit_id' => ['nullable', 'integer', 'exists:organization_units,id'],
                'reference' => ['nullable', 'string', 'max:255'],
                'job_card_id' => ['required', 'integer', 'exists:vehicle_service_job_cards,id'],
                'labor_item_id' => ['required', 'integer', 'exists:vehicle_service_labor_items,id'],
                'employee_id' => ['required', 'integer', 'exists:employees,id'],
                'hours_worked' => ['nullable', 'numeric', 'min:0'],
                'hourly_rate' => ['nullable', 'numeric', 'min:0'],
                'incentive_type' => ['nullable', 'string'],
                'incentive_value' => ['nullable', 'numeric', 'min:0'],
                'role' => ['nullable', 'string'],
                'notes' => ['nullable', 'string'],
                'metadata' => ['nullable', 'array'],
            ],
        ],
        'diagnostics' => [
            'repository' => VehicleServiceDiagnosticRepositoryInterface::class,
            'label' => 'Vehicle service diagnostic',
            'rules' => [
                'row_version' => ['nullable', 'integer', 'min:1'],
                'organization_unit_id' => ['nullable', 'integer', 'exists:organization_units,id'],
                'job_card_id' => ['required', 'integer', 'exists:vehicle_service_job_cards,id'],
                'diagnostic_number' => ['required', 'string', 'max:255'],
                'diagnostic_phase' => ['nullable', 'string'],
                'diagnostic_type' => ['required', 'string', 'max:255'],
                'overall_result' => ['nullable', 'string'],
                'notes' => ['nullable', 'string'],
                'performed_by' => ['nullable', 'integer', 'exists:users,id'],
                'performed_at' => ['nullable', 'date'],
                'metadata' => ['nullable', 'array'],
            ],
        ],
        'diagnostic_lines' => [
            'repository' => VehicleServiceDiagnosticLineRepositoryInterface::class,
            'label' => 'Vehicle service diagnostic line',
            'rules' => [
                'row_version' => ['nullable', 'integer', 'min:1'],
                'organization_unit_id' => ['nullable', 'integer', 'exists:organization_units,id'],
                'diagnostic_id' => ['required', 'integer', 'exists:vehicle_service_diagnostics,id'],
                'diagnostic_code' => ['nullable', 'string', 'max:255'],
                'diagnostic_type' => ['required', 'string', 'max:255'],
                'findings' => ['nullable', 'string'],
                'recommendations' => ['nullable', 'string'],
                'severity' => ['nullable', 'string'],
                'comment' => ['nullable', 'string'],
                'metadata' => ['nullable', 'array'],
            ],
        ],
        'inspections' => [
            'repository' => VehicleServiceInspectionRepositoryInterface::class,
            'label' => 'Vehicle service inspection',
            'rules' => [
                'row_version' => ['nullable', 'integer', 'min:1'],
                'organization_unit_id' => ['nullable', 'integer', 'exists:organization_units,id'],
                'job_card_id' => ['required', 'integer', 'exists:vehicle_service_job_cards,id'],
                'inspection_number' => ['required', 'string', 'max:255'],
                'inspection_phase' => ['nullable', 'string'],
                'inspection_type' => ['required', 'string', 'max:255'],
                'overall_result' => ['nullable', 'string'],
                'notes' => ['nullable', 'string'],
                'performed_by' => ['nullable', 'integer', 'exists:users,id'],
                'performed_at' => ['nullable', 'date'],
                'metadata' => ['nullable', 'array'],
            ],
        ],
        'inspection_lines' => [
            'repository' => VehicleServiceInspectionLineRepositoryInterface::class,
            'label' => 'Vehicle service inspection line',
            'rules' => [
                'row_version' => ['nullable', 'integer', 'min:1'],
                'organization_unit_id' => ['nullable', 'integer', 'exists:organization_units,id'],
                'inspection_id' => ['required', 'integer', 'exists:vehicle_service_inspections,id'],
                'inspection_item' => ['required', 'string', 'max:255'],
                'expected_value' => ['nullable', 'string', 'max:255'],
                'actual_value' => ['nullable', 'string', 'max:255'],
                'result' => ['nullable', 'string'],
                'comment' => ['nullable', 'string'],
                'metadata' => ['nullable', 'array'],
            ],
        ],
    ],
];
