<?php

declare(strict_types=1);

return [
    'pagination' => [
        'default_per_page' => 20,
        'max_per_page' => 200,
    ],
    'attachments' => [
        'max_upload_kilobytes' => (int) env('ATTACHMENT_MAX_UPLOAD_KB', 51200),
        'disk' => env('ATTACHMENT_STORAGE_DISK', env('CORE_FILE_STORAGE_DISK', 'local')),
        'categories' => [
            'general',
            'contract',
            'identity',
            'compliance',
            'invoice',
            'receipt',
            'tax',
            'finance',
            'hr',
            'vehicle',
            'inspection',
            'warranty',
            'image',
            'other',
        ],
        'preview_mime_types' => [
            'application/pdf',
            'image/gif',
            'image/jpeg',
            'image/png',
            'image/webp',
            'text/plain',
        ],
        'allowed_mime_types' => [
            'application/json',
            'application/msword',
            'application/pdf',
            'application/rtf',
            'application/vnd.ms-excel',
            'application/vnd.ms-powerpoint',
            'application/vnd.oasis.opendocument.spreadsheet',
            'application/vnd.oasis.opendocument.text',
            'application/vnd.openxmlformats-officedocument.presentationml.presentation',
            'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
            'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
            'application/zip',
            'image/gif',
            'image/jpeg',
            'image/png',
            'image/webp',
            'text/csv',
            'text/plain',
        ],
        'attachables' => [
            'tenant' => ['model' => \Modules\Tenant\Models\TenantModel::class, 'module' => 'tenant', 'reference' => 'code'],
            'organization_unit' => ['model' => \Modules\OrganizationUnit\Models\OrganizationUnitModel::class, 'module' => 'organization_unit', 'reference' => 'code'],
            'user' => ['model' => \Modules\User\Models\UserModel::class, 'module' => 'user', 'reference' => 'email'],
            'customer' => ['model' => \Modules\Customer\Models\Customer::class, 'module' => 'customer', 'reference' => 'customer_number'],
            'customer_document' => ['model' => \Modules\Customer\Models\CustomerDocument::class, 'module' => 'customer', 'reference' => 'document_number'],
            'supplier' => ['model' => \Modules\Supplier\Models\Supplier::class, 'module' => 'supplier', 'reference' => 'supplier_number'],
            'supplier_document' => ['model' => \Modules\Supplier\Models\SupplierDocument::class, 'module' => 'supplier', 'reference' => 'document_number'],
            'employee' => ['model' => \Modules\Hr\Models\HrEmployee::class, 'module' => 'hr', 'reference' => 'employee_number'],
            'employee_document' => ['model' => \Modules\Hr\Models\HrEmployeeDocument::class, 'module' => 'hr', 'reference' => 'document_number'],
            'vehicle' => ['model' => \Modules\Vehicle\Models\Vehicle::class, 'module' => 'vehicle', 'reference' => 'vehicle_number'],
            'vehicle_document' => ['model' => \Modules\Vehicle\Models\VehicleDocument::class, 'module' => 'vehicle', 'reference' => 'document_number'],
            'vehicle_service_job' => ['model' => \Modules\VehicleService\Models\VehicleServiceJob::class, 'module' => 'vehicle_service', 'reference' => 'job_number'],
            'item' => ['model' => \Modules\Item\Models\Item::class, 'module' => 'item', 'reference' => 'item_code'],
            'purchase_order' => ['model' => \Modules\Purchase\Models\PurchaseOrder::class, 'module' => 'purchase', 'reference' => 'purchase_order_number'],
            'goods_receipt_note' => ['model' => \Modules\Purchase\Models\GoodsReceiptNote::class, 'module' => 'purchase', 'reference' => 'grn_number'],
            'purchase_return' => ['model' => \Modules\Purchase\Models\PurchaseReturn::class, 'module' => 'purchase', 'reference' => 'return_number'],
            'purchase_debit_note' => ['model' => \Modules\Purchase\Models\PurchaseDebitNote::class, 'module' => 'purchase', 'reference' => 'debit_note_number'],
            'sales_quotation' => ['model' => \Modules\Sales\Models\SalesQuotation::class, 'module' => 'sales', 'reference' => 'quotation_number'],
            'sales_order' => ['model' => \Modules\Sales\Models\SalesOrder::class, 'module' => 'sales', 'reference' => 'sales_order_number'],
            'sales_delivery' => ['model' => \Modules\Sales\Models\SalesDelivery::class, 'module' => 'sales', 'reference' => 'delivery_number'],
            'sales_return' => ['model' => \Modules\Sales\Models\SalesReturn::class, 'module' => 'sales', 'reference' => 'return_number'],
            'sales_credit_note' => ['model' => \Modules\Sales\Models\SalesCreditNote::class, 'module' => 'sales', 'reference' => 'credit_note_number'],
            'inventory_adjustment' => ['model' => \Modules\Inventory\Models\InventoryAdjustment::class, 'module' => 'inventory', 'reference' => 'adjustment_number'],
            'inventory_transfer' => ['model' => \Modules\Inventory\Models\InventoryTransfer::class, 'module' => 'inventory', 'reference' => 'transfer_number'],
            'inventory_stock_count' => ['model' => \Modules\Inventory\Models\InventoryStockCount::class, 'module' => 'inventory', 'reference' => 'count_number'],
            'inventory_movement' => ['model' => \Modules\Inventory\Models\InventoryMovement::class, 'module' => 'inventory', 'reference' => 'reference_number'],
            'invoice' => ['model' => \Modules\Invoice\Models\Invoice::class, 'module' => 'invoice', 'reference' => 'invoice_number'],
            'payment' => ['model' => \Modules\Payment\Models\Payment::class, 'module' => 'payment', 'reference' => 'payment_number'],
            'finance_account' => ['model' => \Modules\Finance\Models\FinanceAccount::class, 'module' => 'finance', 'reference' => 'account_code'],
            'finance_journal_entry' => ['model' => \Modules\Finance\Models\FinanceJournalEntry::class, 'module' => 'finance', 'reference' => 'journal_number'],
            'finance_budget' => ['model' => \Modules\Finance\Models\FinanceBudget::class, 'module' => 'finance', 'reference' => 'budget_number'],
            'finance_bank_reconciliation' => ['model' => \Modules\Finance\Models\FinanceBankReconciliation::class, 'module' => 'finance', 'reference' => 'reconciliation_number'],
            'tax' => ['model' => \Modules\Tax\Models\Tax::class, 'module' => 'tax', 'reference' => 'code'],
            'tax_transaction' => ['model' => \Modules\Tax\Models\TaxTransaction::class, 'module' => 'tax', 'reference' => 'source_reference'],
            'tax_document_snapshot' => ['model' => \Modules\Tax\Models\TaxDocumentSnapshot::class, 'module' => 'tax', 'reference' => 'document_number'],
        ],
    ],
];
