<?php

declare(strict_types=1);

namespace Modules\Auth\Constants;

final class AuthErrorCode
{
    public const INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS';

    public const RATE_LIMITED = 'AUTH_RATE_LIMITED';

    public const INFRASTRUCTURE_FAILURE = 'AUTH_INFRASTRUCTURE_FAILURE';

    public const PROVIDER_NOT_FOUND = 'AUTH_PROVIDER_NOT_FOUND';

    public const USER_INACTIVE = 'AUTH_USER_INACTIVE';

    public const CLIENT_NOT_ALLOWED = 'AUTH_CLIENT_NOT_ALLOWED';

    public const INVALID_CLIENT_SECRET = 'AUTH_INVALID_CLIENT_SECRET';

    public const TOKEN_INVALID = 'AUTH_TOKEN_INVALID';

    public const TOKEN_EXPIRED = 'AUTH_TOKEN_EXPIRED';

    public const TOKEN_REVOKED = 'AUTH_TOKEN_REVOKED';

    public const UNAUTHORIZED_ACCESS = 'AUTH_UNAUTHORIZED_ACCESS';

    public const TENANT_MISMATCH = 'AUTH_TENANT_MISMATCH';

    public const ORGANIZATION_UNIT_RESOLUTION_FAILED = 'AUTH_ORGANIZATION_UNIT_RESOLUTION_FAILED';

    public const SESSION_NOT_FOUND = 'AUTH_SESSION_NOT_FOUND';

    public const AUTHORIZATION_CODE_INVALID = 'AUTH_AUTHORIZATION_CODE_INVALID';

    public const REGISTRATION_DISABLED = 'AUTH_REGISTRATION_DISABLED';

    public const INVITATION_INVALID = 'AUTH_INVITATION_INVALID';

    private function __construct() {}
}
