<?php

declare(strict_types=1);

namespace Modules\Auth\Constants;

final class AuthErrorCode
{
    public const INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS';

    public const PROVIDER_NOT_FOUND = 'AUTH_PROVIDER_NOT_FOUND';

    public const PROVIDER_DISABLED = 'AUTH_PROVIDER_DISABLED';

    public const USER_INACTIVE = 'AUTH_USER_INACTIVE';

    public const CLIENT_NOT_FOUND = 'AUTH_CLIENT_NOT_FOUND';

    public const CLIENT_NOT_ALLOWED = 'AUTH_CLIENT_NOT_ALLOWED';

    public const INVALID_CLIENT_SECRET = 'AUTH_INVALID_CLIENT_SECRET';

    public const TOKEN_INVALID = 'AUTH_TOKEN_INVALID';

    public const TOKEN_EXPIRED = 'AUTH_TOKEN_EXPIRED';

    public const TOKEN_REVOKED = 'AUTH_TOKEN_REVOKED';

    public const UNAUTHORIZED_ACCESS = 'AUTH_UNAUTHORIZED_ACCESS';

    public const TENANT_MISMATCH = 'AUTH_TENANT_MISMATCH';

    public const TENANT_RESOLUTION_FAILED = 'AUTH_TENANT_RESOLUTION_FAILED';

    public const ORGANIZATION_UNIT_RESOLUTION_FAILED = 'AUTH_ORGANIZATION_UNIT_RESOLUTION_FAILED';

    public const SSO_FAILURE = 'AUTH_SSO_FAILURE';

    public const SESSION_NOT_FOUND = 'AUTH_SESSION_NOT_FOUND';

    public const VERIFICATION_FAILED = 'AUTH_VERIFICATION_FAILED';

    public const AUTHORIZATION_CODE_INVALID = 'AUTH_AUTHORIZATION_CODE_INVALID';

    public const REGISTRATION_DISABLED = 'AUTH_REGISTRATION_DISABLED';

    public const INVITATION_INVALID = 'AUTH_INVITATION_INVALID';

    public const REGISTRATION_DOMAIN_NOT_ALLOWED = 'AUTH_REGISTRATION_DOMAIN_NOT_ALLOWED';

    public const MFA_ENROLLMENT_REQUIRED = 'AUTH_MFA_ENROLLMENT_REQUIRED';

    public const MFA_ENROLLMENT_FAILED = 'AUTH_MFA_ENROLLMENT_FAILED';

    public const MFA_REQUIRED = 'AUTH_MFA_REQUIRED';

    public const MFA_INVALID_CODE = 'AUTH_MFA_INVALID_CODE';

    public const MFA_ALREADY_ENABLED = 'AUTH_MFA_ALREADY_ENABLED';

    private function __construct() {}
}
