<?php
use Illuminate\Support\Facades\Route;
use Modules\Inventory\Presentation\Controllers\ProductController;
use Modules\Inventory\Presentation\Controllers\ProductCategoryController;
use Modules\Inventory\Presentation\Controllers\ProductVariantController;
use Modules\Inventory\Presentation\Controllers\WarehouseController;
use Modules\Inventory\Presentation\Controllers\LocationController;
use Modules\Inventory\Presentation\Controllers\StockMovementController;
use Modules\Inventory\Presentation\Controllers\StockLevelController;
use Modules\Inventory\Presentation\Controllers\InventoryValuationController;
use Modules\Inventory\Presentation\Controllers\InventoryLotController;
use Modules\Inventory\Presentation\Controllers\CycleCountController;
Route::prefix('api/v1')->middleware(['api', 'auth:sanctum'])->group(function () {
    Route::apiResource('inventory/products', ProductController::class);
    Route::apiResource('inventory/categories', ProductCategoryController::class);
    Route::apiResource('inventory/warehouses', WarehouseController::class);
    Route::apiResource('inventory/locations', LocationController::class);
    Route::apiResource('inventory/movements', StockMovementController::class)->only(['index', 'show', 'store']);
    Route::get('inventory/stock-levels', [StockLevelController::class, 'index']);
    Route::apiResource('inventory/variants', ProductVariantController::class);
    Route::get('inventory/valuation/report', [InventoryValuationController::class, 'report']);
    Route::get('inventory/valuation', [InventoryValuationController::class, 'index']);
    Route::post('inventory/valuation', [InventoryValuationController::class, 'store']);
    Route::get('inventory/lots', [InventoryLotController::class, 'index']);
    Route::post('inventory/lots', [InventoryLotController::class, 'store']);
    Route::get('inventory/lots/{id}', [InventoryLotController::class, 'show']);
    Route::post('inventory/lots/{id}/block', [InventoryLotController::class, 'block']);
    Route::get('inventory/cycle-counts', [CycleCountController::class, 'index']);
    Route::post('inventory/cycle-counts', [CycleCountController::class, 'store']);
    Route::get('inventory/cycle-counts/{id}', [CycleCountController::class, 'show']);
    Route::post('inventory/cycle-counts/{id}/lines', [CycleCountController::class, 'recordLine']);
    Route::post('inventory/cycle-counts/{id}/post', [CycleCountController::class, 'post']);
});
