import { useEffect, useState } from 'react';
import { Input } from '@/shared/components/Input';
import { Select } from '@/shared/components/Select';
import { licenseApi } from '../hrApi';
import type { EmployeeLicensePayload, HrLicense } from '../hrTypes';
import { EmployeeRelationTab } from './EmployeeRelationTab';
import { HrLicenseSelect } from './HrLicenseSelect';
import { useEmployeeRelationCrud } from './useEmployeeRelationCrud';
export function EmployeeLicenseTab({ employeeId }: { employeeId: number }) { const crud = useEmployeeRelationCrud(employeeId, licenseApi); const [master, setMaster] = useState<HrLicense | null>(null); const [draft, setDraft] = useState<EmployeeLicensePayload>({ license_id: 0, license_number: '', issued_date: '', expiry_date: '', status: 'pending' }); useEffect(() => { const r = crud.editing; setMaster(r?.license ?? null); setDraft(r ? { license_id: r.license_id, license_number: r.license_number, issued_date: r.issued_date, expiry_date: r.expiry_date, status: r.status } : { license_id: 0, license_number: '', issued_date: '', expiry_date: '', status: 'pending' }); }, [crud.editing, crud.open]); return <EmployeeRelationTab title="License" fields={['license', 'license_number', 'expiry_date', 'status']} result={crud} open={crud.open} editing={crud.editing} submitting={crud.submitting} actionError={crud.actionError} onCreate={crud.startCreate} onEdit={crud.startEdit} onDelete={crud.destroy} onClose={crud.close} onSubmit={() => void crud.submit({ ...draft, license_id: master?.id ?? 0 })}><HrLicenseSelect value={master} onChange={setMaster} /><Input label="License number" value={draft.license_number ?? ''} onChange={(e) => setDraft({ ...draft, license_number: e.target.value })} /><Input label="Issued date" type="date" value={draft.issued_date ?? ''} onChange={(e) => setDraft({ ...draft, issued_date: e.target.value })} /><Input label="Expiry date" type="date" value={draft.expiry_date ?? ''} onChange={(e) => setDraft({ ...draft, expiry_date: e.target.value })} /><Select label="Status" value={draft.status} options={['active', 'expired', 'revoked', 'pending'].map((v) => ({ value: v, label: v }))} onChange={(e) => setDraft({ ...draft, status: e.target.value })} /></EmployeeRelationTab>; }
