export const financePermissions = {
    accountsView: 'finance.accounts.view',
    accountsManage: 'finance.accounts.manage',
    postingProfilesView: 'finance.posting_profiles.view',
    postingProfilesManage: 'finance.posting_profiles.manage',
    journalsView: 'finance.journals.view',
    journalsCreate: 'finance.journals.create',
    journalsUpdate: 'finance.journals.update',
    journalsCancel: 'finance.journals.cancel',
    journalsPost: 'finance.journals.post',
    journalsReverse: 'finance.journals.reverse',
    reportsView: 'finance.reports.view',
    currencyRevaluationsPost: 'finance.currency_revaluations.post',
    fiscalCalendarView: 'finance.fiscal_calendar.view',
    fiscalCalendarManage: 'finance.fiscal_calendar.manage',
    bankReconciliationsView: 'finance.bank_reconciliations.view',
    bankReconciliationsManage: 'finance.bank_reconciliations.manage',
    budgetsView: 'finance.budgets.view',
    budgetsManage: 'finance.budgets.manage',
} as const;
