import { ModulePlaceholderPage } from '../../../shared/components/business/ModulePlaceholderPage';

export function DocumentPage() {
    return (
        <ModulePlaceholderPage
            description="Document records, definitions, templates, workflows, sequences, previews, attachments, and comments. Backend owns numbering, rendering, versioning, permissions, and status transitions."
            sections={[
                { description: 'Records generated by source modules.', label: 'Document Records', path: '/documents', status: 'Ready' },
                { description: 'Definitions, types, templates, and sequences.', label: 'Definitions and Templates', path: '/documents', status: 'Mocked' },
                { description: 'Workflow steps, transitions, and status history.', label: 'Workflows', path: '/documents', status: 'Mocked' },
                { description: 'Backend-rendered document preview placeholder.', label: 'Preview', path: '/documents', status: 'Mocked' },
            ]}
            title="Documents"
        />
    );
}
