import { useEffect, useState, type ComponentType } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { fieldError, toApiError, type ApiError } from '@/shared/api/apiError';
import { Button, LinkButton } from '@/shared/components/Button';
import { ContentHeader } from '@/shared/components/ContentHeader';
import { ErrorAlert } from '@/shared/components/ErrorAlert';
import { Input } from '@/shared/components/Input';
import { LoadingState } from '@/shared/components/LoadingState';
import { Select } from '@/shared/components/Select';
import { Textarea } from '@/shared/components/Textarea';
import type { PartyVehiclePayload, PartyVehicleRelationship } from '@/shared/types/partyVehicle';

interface LookupProps<T> { value: T | null; onChange: (value: T | null) => void; error?: string }
export function PartyVehicleFormPage<P extends { id: number }, V extends { id: number }>({partyKey,title,listPath,PartyLookup,VehicleLookup,get,create,update}:{partyKey:'customer'|'supplier';title:string;listPath:string;PartyLookup:ComponentType<LookupProps<P>>;VehicleLookup:ComponentType<LookupProps<V>>;get:(id:number,signal?:AbortSignal)=>Promise<PartyVehicleRelationship>;create:(payload:PartyVehiclePayload)=>Promise<PartyVehicleRelationship>;update:(id:number,payload:Partial<PartyVehiclePayload>)=>Promise<PartyVehicleRelationship>}){
    const {id}=useParams();const relationshipId=id?Number(id):null;const navigate=useNavigate();const [party,setParty]=useState<P|null>(null);const [vehicle,setVehicle]=useState<V|null>(null);const [relationshipType,setRelationshipType]=useState(partyKey==='customer'?'customer_owned':'third_party');const [startedAt,setStartedAt]=useState(new Date().toISOString().slice(0,10));const [endedAt,setEndedAt]=useState('');const [isCurrent,setIsCurrent]=useState(true);const [notes,setNotes]=useState('');const [loading,setLoading]=useState(Boolean(relationshipId));const [saving,setSaving]=useState(false);const [error,setError]=useState<ApiError|null>(null);
    useEffect(()=>{if(!relationshipId)return;const controller=new AbortController();get(relationshipId,controller.signal).then((r)=>{setParty((r[partyKey]??null) as P|null);setVehicle(r.vehicle as unknown as V);setRelationshipType(r.relationship_type??(partyKey==='customer'?'customer_owned':'third_party'));setStartedAt(r.started_at.slice(0,10));setEndedAt(r.ended_at?.slice(0,10)??'');setNotes(r.notes??'');}).catch((e)=>setError(toApiError(e))).finally(()=>setLoading(false));return()=>controller.abort();},[get,partyKey,relationshipId]);
    const submit=async()=>{setSaving(true);setError(null);try{const payload:PartyVehiclePayload={vehicle_id:Number(vehicle?.id),[`${partyKey}_id`]:Number(party?.id),relationship_type:relationshipType,started_at:startedAt,ended_at:endedAt||null,notes:notes||null,...(!relationshipId?{is_current:isCurrent}:{})};if(relationshipId){const {vehicle_id:_,customer_id:__,supplier_id:___,is_current:____,...editable}=payload;void _;void __;void ___;void ____;await update(relationshipId,editable);}else await create(payload);navigate(listPath);}catch(e){setError(toApiError(e));}finally{setSaving(false)}};
    if(loading)return <LoadingState/>;return <><ContentHeader title={`${relationshipId?'Edit':'Create'} ${title}`} description="The backend validates scope, duplicates, dates, and current relationship invariants." actions={<LinkButton variant="secondary" to={listPath}>Back to list</LinkButton>}/><ErrorAlert error={error}/><div className="grid gap-5 rounded-xl border border-slate-200 bg-white p-6 shadow-sm md:grid-cols-2"><PartyLookup value={party} onChange={setParty} error={fieldError(error,`${partyKey}_id`)}/><VehicleLookup value={vehicle} onChange={setVehicle} error={fieldError(error,'vehicle_id')}/><Select label="Relationship type" value={relationshipType} onChange={(e)=>setRelationshipType(e.target.value)} options={(partyKey==='customer'?['customer_owned']:['third_party','leased','rented']).map((value)=>({value,label:value.replaceAll('_',' ')}))} error={fieldError(error,'relationship_type')}/><Input type="date" label="Start date" value={startedAt} onChange={(e)=>setStartedAt(e.target.value)} error={fieldError(error,'started_at')}/><Input type="date" label="End date" value={endedAt} onChange={(e)=>setEndedAt(e.target.value)} error={fieldError(error,'ended_at')}/>{!relationshipId&&<label className="flex items-center gap-2 text-sm font-medium text-slate-700"><input type="checkbox" checked={isCurrent} onChange={(e)=>setIsCurrent(e.target.checked)}/> Set as current</label>}<div className="md:col-span-2"><Textarea label="Notes" value={notes} onChange={(e)=>setNotes(e.target.value)} error={fieldError(error,'notes')}/></div><div className="md:col-span-2 flex justify-end gap-2"><LinkButton variant="secondary" to={listPath}>Cancel</LinkButton><Button loading={saving} disabled={!party||!vehicle||!startedAt} onClick={()=>void submit()}>Save relationship</Button></div></div></>;
}
