<?php
declare(strict_types=1);
namespace Modules\Hr\Http\Resources;
use BackedEnum;
use Illuminate\Http\Request;
use Illuminate\Http\Resources\Json\JsonResource;
final class EmployeeResource extends JsonResource
{
    public function toArray(Request $request): array { return [...(new EmployeeSummaryResource($this->resource))->resolve($request), 'department_id' => $this->department_id, 'designation_id' => $this->designation_id, 'employment_type_id' => $this->employment_type_id, 'reporting_manager_id' => $this->reporting_manager_id, 'reporting_manager' => $this->whenLoaded('reportingManager', fn () => $this->reportingManager ? new EmployeeSummaryResource($this->reportingManager) : null), 'joined_date' => $this->joined_date?->toDateString(), 'resigned_date' => $this->resigned_date?->toDateString(), 'date_of_birth' => $this->date_of_birth?->toDateString(), 'gender' => $this->gender instanceof BackedEnum ? $this->gender->value : $this->gender, 'default_hourly_rate' => (string) $this->default_hourly_rate, 'default_daily_rate' => (string) $this->default_daily_rate, 'default_service_rate' => (string) $this->default_service_rate, 'notes' => $this->notes, 'metadata' => $this->metadata, 'approved_at' => $this->approved_at?->toISOString(), 'contacts' => $this->whenLoaded('contacts', fn () => EmployeeContactResource::collection($this->contacts)->resolve($request)), 'addresses' => $this->whenLoaded('addresses', fn () => EmployeeAddressResource::collection($this->addresses)->resolve($request)), 'documents' => $this->whenLoaded('documents', fn () => EmployeeDocumentResource::collection($this->documents)->resolve($request)), 'skills' => $this->whenLoaded('skillAssignments', fn () => EmployeeSkillAssignmentResource::collection($this->skillAssignments)->resolve($request)), 'certifications' => $this->whenLoaded('certificationAssignments', fn () => EmployeeCertificationAssignmentResource::collection($this->certificationAssignments)->resolve($request)), 'licenses' => $this->whenLoaded('licenseAssignments', fn () => EmployeeLicenseAssignmentResource::collection($this->licenseAssignments)->resolve($request)), 'rates' => $this->whenLoaded('rates', fn () => EmployeeRateResource::collection($this->rates)->resolve($request)), 'availability' => $this->whenLoaded('availabilities', fn () => EmployeeAvailabilityResource::collection($this->availabilities)->resolve($request)), 'status_history' => $this->whenLoaded('statusHistories', fn () => EmployeeStatusHistoryResource::collection($this->statusHistories)->resolve($request))]; }
}
