import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { Button } from '../../../shared/components/ui/Button';
import { Input } from '../../../shared/components/ui/Input';
import { purchaseApi } from '../services/purchaseApi';
import type { Grn, PurchasePage } from '../types/purchase.types';
import { Badge, Empty, Loading } from './PurchaseOrderListPage';

export function GrnListPage() {
    const [data, setData] = useState<PurchasePage<Grn> | null>(null);
    const [searchInput, setSearchInput] = useState('');
    const [search, setSearch] = useState('');
    const [status, setStatus] = useState('');
    const [page, setPage] = useState(1);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState('');
    useEffect(() => { const timer = window.setTimeout(() => { setPage(1); setSearch(searchInput.trim()); }, 350); return () => window.clearTimeout(timer); }, [searchInput]);
    useEffect(() => { let active = true; setLoading(true); void purchaseApi.listGrns({ page, perPage: 20, search: search || undefined, status: status || undefined }).then((response) => { if (active) setData(response); }).catch((requestError) => { if (active) setError(requestError instanceof Error ? requestError.message : 'Unable to load GRNs.'); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [page, search, status]);
    return <div className="space-y-5"><header className="flex items-end justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-blue-600">Procurement</p><h1 className="mt-1 text-3xl font-bold text-slate-950">Goods receipt notes</h1></div><div className="flex gap-2"><Link className="inline-flex h-10 items-center justify-center rounded-lg border border-slate-200 bg-white px-4 text-sm font-semibold text-slate-700 hover:bg-slate-50" to="/purchase/orders">POs</Link><Link className="inline-flex h-10 items-center justify-center rounded-lg bg-blue-600 px-4 text-sm font-semibold text-white hover:bg-blue-700" to="/purchase/grns/new">Create GRN</Link></div></header><div className="grid gap-3 rounded-xl border border-slate-200 bg-white p-4 shadow-sm sm:grid-cols-[1fr_180px]"><Input placeholder="Search GRN, PO, or supplier" value={searchInput} onChange={(event) => setSearchInput(event.target.value)} /><select className="h-11 rounded-lg border border-slate-200 bg-slate-50 px-3 text-sm" value={status} onChange={(event) => { setPage(1); setStatus(event.target.value); }}><option value="">All statuses</option><option value="draft">Draft</option><option value="posted">Posted</option></select></div>{error ? <div className="rounded-lg border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div> : null}<div className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm">{loading ? <Loading label="Loading GRNs" /> : data?.items.length ? <table className="w-full text-left text-sm"><thead className="border-b border-slate-200 bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-4 py-3">GRN</th><th className="px-4 py-3">Supplier</th><th className="px-4 py-3">Date</th><th className="px-4 py-3">Total</th><th className="px-4 py-3">Status</th><th className="px-4 py-3 text-right">Actions</th></tr></thead><tbody>{data.items.map((grn) => <tr className="border-b border-slate-100" key={grn.id}><td className="px-4 py-3 font-semibold">{grn.grnNumber}</td><td className="px-4 py-3">{grn.supplierName}</td><td className="px-4 py-3">{grn.receivedDate}</td><td className="px-4 py-3">{Number(grn.grandTotal).toLocaleString()}</td><td className="px-4 py-3"><Badge label={grn.status} /></td><td className="px-4 py-3 text-right"><Link className="font-semibold text-blue-700" to={`/purchase/grns/${grn.id}`}>View</Link></td></tr>)}</tbody></table> : <Empty label="No GRNs found" />}</div>{data ? <div className="flex justify-end gap-2"><Button disabled={page <= 1 || loading} onClick={() => setPage((current) => current - 1)} variant="secondary">Previous</Button><Button disabled={page >= data.meta.lastPage || loading} onClick={() => setPage((current) => current + 1)} variant="secondary">Next</Button></div> : null}</div>;
}
