import { FormEvent, useEffect, useMemo, useState, type ReactNode } from 'react';
import { useNavigate, useParams, useSearchParams } from 'react-router-dom';
import { Button } from '../../../shared/components/ui/Button';
import { Input } from '../../../shared/components/ui/Input';
import { purchaseApi } from '../services/purchaseApi';
import type { PurchaseLineInput, PurchaseLookup, PurchaseReturnInput } from '../types/purchase.types';
import { Alert, Header, HeaderTotalsFields, Lookup, purchasePreview, Section, TotalsPreview } from './PurchaseOrderEditorPage';

export function PurchaseReturnEditorPage({ mode }: { mode: 'create' | 'edit' }) {
    const { id } = useParams();
    const [params] = useSearchParams();
    const navigate = useNavigate();
    const [receivedGrns, setReceivedGrns] = useState<PurchaseLookup[]>([]);
    const [error, setError] = useState('');
    const [saving, setSaving] = useState(false);
    const [value, setValue] = useState<PurchaseReturnInput>({ lines: [], originalGrnId: Number(params.get('grnId')) || 0, returnDate: new Date().toISOString().slice(0, 10) });
    useEffect(() => { void purchaseApi.lookup('received-grns').then(setReceivedGrns); }, []);
    useEffect(() => { const grnId = Number(params.get('grnId')); if (mode === 'create' && grnId) void loadGrn(grnId); }, [mode, params]);
    useEffect(() => { if (mode === 'edit' && id) void purchaseApi.getReturn(Number(id)).then((ret) => setValue({ creditNoteTotal: ret.creditNoteTotal, debitNoteTotal: ret.debitNoteTotal, headerDiscountAmount: ret.headerDiscountAmount, headerDiscountType: ret.headerDiscountType ?? '', headerDiscountValue: ret.headerDiscountValue ?? undefined, headerTaxAmount: ret.headerTaxAmount, lines: (ret.lines ?? []).map((line) => ({ discountAmount: line.discount_amount, itemId: line.item_id, originalGrnLineId: line.original_grn_line_id ?? undefined, returnQty: line.return_qty, taxAmount: line.tax_amount, unitPrice: line.unit_price, uomId: line.uom_id, warehouseId: line.warehouse_id ?? undefined })), notes: ret.notes ?? undefined, originalGrnId: ret.originalGrnId, originalInvoiceId: ret.originalInvoiceId ?? undefined, reference: ret.reference ?? undefined, returnDate: ret.returnDate, returnNumber: ret.returnNumber, returnReason: ret.returnReason ?? undefined })).catch((requestError) => setError(requestError instanceof Error ? requestError.message : 'Unable to load return.')); }, [id, mode]);
    const total = useMemo(() => purchasePreview(value), [value]);
    function updateLine(index: number, next: Partial<PurchaseLineInput>) { setValue((current) => ({ ...current, lines: current.lines.map((line, lineIndex) => lineIndex === index ? { ...line, ...next } : line) })); }
    async function loadGrn(grnId: number) {
        const [grn, lines] = await Promise.all([purchaseApi.getGrn(grnId), purchaseApi.lookup('returnable-grn-lines', { grnId })]);
        setValue((current) => ({ ...current, originalGrnId: grnId, lines: lines.map((line) => ({ discountAmount: line.discount_amount ?? '0', itemCode: line.item_code, itemId: line.item_id ?? 0, itemName: line.name, originalGrnLineId: line.id, remainingQty: line.remaining_qty, returnQty: line.remaining_qty ?? '0', sourceQty: line.source_qty, taxAmount: line.tax_amount ?? '0', unitPrice: line.unit_price ?? '0', uomCode: line.uom_code, uomId: line.uom_id ?? 0, usedQty: line.used_qty ?? '0', warehouseId: line.warehouse_id ?? grn.warehouseId })) }));
    }
    async function submit(event: FormEvent) { event.preventDefault(); setSaving(true); setError(''); try { const saved = mode === 'edit' && id ? await purchaseApi.updateReturn(Number(id), value) : await purchaseApi.createReturn(value); navigate(`/purchase/returns/${saved.id}`); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : 'Unable to save return.'); } finally { setSaving(false); } }
    return <form className="space-y-5" onSubmit={(event) => void submit(event)}><Header title={mode === 'edit' ? 'Edit purchase return' : 'Create purchase return'} />{error ? <Alert message={error} /> : null}<Section title="Basic Information"><div className="grid gap-4 md:grid-cols-4"><Field label="Return number"><Input value={value.returnNumber ?? ''} onChange={(event) => setValue({ ...value, returnNumber: event.target.value })} placeholder="Auto if empty" /></Field>{mode === 'create' ? <Lookup label="GRN" options={receivedGrns} value={value.originalGrnId} onChange={(grnId) => void loadGrn(grnId)} /> : <Field label="GRN ID"><Input readOnly value={value.originalGrnId || ''} /></Field>}<Field label="Original invoice ID"><Input value={value.originalInvoiceId ?? ''} onChange={(event) => setValue({ ...value, originalInvoiceId: event.target.value ? Number(event.target.value) : undefined })} /></Field><Field label="Return date"><Input type="date" value={value.returnDate} onChange={(event) => setValue({ ...value, returnDate: event.target.value })} /></Field></div></Section><Section title="Returnable GRN Lines"><div className="space-y-3">{value.lines.map((line, index) => <div className="grid gap-3 rounded-lg border border-slate-100 bg-slate-50 p-3 md:grid-cols-6" key={index}><Info label="Item" value={`${line.itemCode ?? line.itemId} - ${line.itemName ?? ''}`} /><Info label="UOM" value={line.uomCode ?? line.uomId} /><Info label="Received" value={line.sourceQty ?? '-'} /><Info label="Already returned" value={line.usedQty ?? '0.0000'} /><Field label="Return qty"><Input max={line.remainingQty} min="0" step="0.0001" value={line.returnQty ?? '1'} onChange={(event) => updateLine(index, { returnQty: event.target.value })} /></Field><div className="flex items-end"><Button onClick={() => setValue({ ...value, lines: value.lines.filter((_, lineIndex) => lineIndex !== index) })} variant="secondary">Skip</Button></div><p className="md:col-span-6 text-xs text-slate-500">Remaining returnable: {line.remainingQty ?? '0.0000'}. Source item and UOM are readonly and revalidated by the backend.</p></div>)}{!value.lines.length ? <p className="text-sm text-slate-500">Select a received GRN to load returnable lines.</p> : null}</div></Section><Section title="Header Discount, Tax, Charges & Adjustments"><HeaderTotalsFields value={value} onChange={(next) => setValue({ ...value, ...next })} /></Section><Section title="Totals"><TotalsPreview totals={total} /></Section><Section title="Notes"><textarea className="min-h-24 w-full rounded-lg border border-slate-200 bg-slate-50 p-3 text-sm" value={value.notes ?? ''} onChange={(event) => setValue({ ...value, notes: event.target.value })} /></Section><div className="flex justify-end gap-3"><Button onClick={() => navigate('/purchase/returns')} variant="secondary">Cancel</Button><Button disabled={saving} type="submit" variant="blue">{saving ? 'Saving' : 'Save return'}</Button></div></form>;
}

function Field({ children, label }: { children: ReactNode; label: string }) { return <label className="space-y-2 text-sm font-semibold text-slate-700"><span>{label}</span>{children}</label>; }
function Info({ label, value }: { label: string; value: ReactNode }) { return <div><p className="text-xs font-bold uppercase tracking-wide text-slate-400">{label}</p><div className="mt-1 text-sm font-semibold text-slate-800">{value}</div></div>; }
