import { FormEvent, useEffect, useState, type ReactNode } from 'react';
import { useNavigate, useParams, useSearchParams } from 'react-router-dom';
import { Button } from '../../../shared/components/ui/Button';
import { Input } from '../../../shared/components/ui/Input';
import { purchaseApi } from '../services/purchaseApi';
import type { PurchaseLineInput, PurchaseReturnInput } from '../types/purchase.types';
import { Alert, Header, Section } from './PurchaseOrderEditorPage';

export function PurchaseReturnEditorPage({ mode }: { mode: 'create' | 'edit' }) {
    const { id } = useParams();
    const [params] = useSearchParams();
    const navigate = useNavigate();
    const [error, setError] = useState('');
    const [saving, setSaving] = useState(false);
    const [value, setValue] = useState<PurchaseReturnInput>({ lines: [], originalGrnId: Number(params.get('grnId')) || 0, returnDate: new Date().toISOString().slice(0, 10) });
    useEffect(() => { const grnId = Number(params.get('grnId')); if (mode === 'create' && grnId) void purchaseApi.getGrn(grnId).then((grn) => setValue((current) => ({ ...current, originalGrnId: grnId, lines: (grn.lines ?? []).filter((line) => Number(line.accepted_qty ?? 0) > Number(line.returned_qty ?? 0)).map((line) => ({ itemId: line.item_id, originalGrnLineId: line.id, returnQty: String(Number(line.accepted_qty ?? 0) - Number(line.returned_qty ?? 0)), unitPrice: line.unit_price, uomId: line.uom_id, warehouseId: line.warehouse_id ?? grn.warehouseId })) }))); }, [mode, params]);
    useEffect(() => { if (mode === 'edit' && id) void purchaseApi.getReturn(Number(id)).then((ret) => setValue({ lines: (ret.lines ?? []).map((line) => ({ itemId: line.item_id, originalGrnLineId: line.original_grn_line_id ?? undefined, returnQty: line.return_qty, taxAmount: line.tax_amount, unitPrice: line.unit_price, uomId: line.uom_id, warehouseId: line.warehouse_id ?? undefined })), notes: ret.notes ?? undefined, originalGrnId: ret.originalGrnId, originalInvoiceId: ret.originalInvoiceId ?? undefined, reference: ret.reference ?? undefined, returnDate: ret.returnDate, returnNumber: ret.returnNumber, returnReason: ret.returnReason ?? undefined })).catch((requestError) => setError(requestError instanceof Error ? requestError.message : 'Unable to load return.')); }, [id, mode]);
    function updateLine(index: number, next: Partial<PurchaseLineInput>) { setValue((current) => ({ ...current, lines: current.lines.map((line, lineIndex) => lineIndex === index ? { ...line, ...next } : line) })); }
    async function submit(event: FormEvent) { event.preventDefault(); setSaving(true); setError(''); try { const saved = mode === 'edit' && id ? await purchaseApi.updateReturn(Number(id), value) : await purchaseApi.createReturn(value); navigate(`/purchase/returns/${saved.id}`); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : 'Unable to save return.'); } finally { setSaving(false); } }
    return <form className="space-y-5" onSubmit={(event) => void submit(event)}><Header title={mode === 'edit' ? 'Edit purchase return' : 'Create purchase return'} />{error ? <Alert message={error} /> : null}<Section title="Basic Information"><div className="grid gap-4 md:grid-cols-4"><Field label="Return number"><Input value={value.returnNumber ?? ''} onChange={(event) => setValue({ ...value, returnNumber: event.target.value })} placeholder="Auto if empty" /></Field><Field label="GRN ID"><Input value={value.originalGrnId || ''} onChange={(event) => setValue({ ...value, originalGrnId: Number(event.target.value) })} /></Field><Field label="Original invoice ID"><Input value={value.originalInvoiceId ?? ''} onChange={(event) => setValue({ ...value, originalInvoiceId: event.target.value ? Number(event.target.value) : undefined })} /></Field><Field label="Return date"><Input type="date" value={value.returnDate} onChange={(event) => setValue({ ...value, returnDate: event.target.value })} /></Field></div></Section><Section title="Item Lines"><div className="space-y-3">{value.lines.map((line, index) => <div className="grid gap-3 rounded-lg border border-slate-100 bg-slate-50 p-3 md:grid-cols-5" key={index}><Field label="Item ID"><Input value={line.itemId || ''} onChange={(event) => updateLine(index, { itemId: Number(event.target.value) })} /></Field><Field label="UOM ID"><Input value={line.uomId || ''} onChange={(event) => updateLine(index, { uomId: Number(event.target.value) })} /></Field><Field label="Return qty"><Input value={line.returnQty ?? '1'} onChange={(event) => updateLine(index, { returnQty: event.target.value })} /></Field><Field label="Unit cost"><Input value={line.unitPrice} onChange={(event) => updateLine(index, { unitPrice: event.target.value })} /></Field><Button onClick={() => setValue({ ...value, lines: value.lines.filter((_, lineIndex) => lineIndex !== index) })} variant="secondary">Remove</Button></div>)}<Button onClick={() => setValue({ ...value, lines: [...value.lines, { itemId: 0, returnQty: '1', unitPrice: '0', uomId: 0, warehouseId: 0 }] })} variant="secondary">Add line</Button></div></Section><Section title="Notes"><textarea className="min-h-24 w-full rounded-lg border border-slate-200 bg-slate-50 p-3 text-sm" value={value.notes ?? ''} onChange={(event) => setValue({ ...value, notes: event.target.value })} /></Section><div className="flex justify-end gap-3"><Button onClick={() => navigate('/purchase/returns')} variant="secondary">Cancel</Button><Button disabled={saving} type="submit" variant="blue">{saving ? 'Saving' : 'Save return'}</Button></div></form>;
}

function Field({ children, label }: { children: ReactNode; label: string }) { return <label className="space-y-2 text-sm font-semibold text-slate-700"><span>{label}</span>{children}</label>; }
