<?php

declare(strict_types=1);

namespace Modules\Finance\Domain\Constants;

final class FinanceErrorCode
{
    public const INVALID_VALUE = 'FINANCE_INVALID_VALUE';
    public const NOT_FOUND = 'FINANCE_NOT_FOUND';
    public const CONFLICT = 'FINANCE_CONFLICT';
    public const UNBALANCED_JOURNAL_ENTRY = 'FINANCE_UNBALANCED_JOURNAL_ENTRY';
    public const INVALID_STATUS_TRANSITION = 'FINANCE_INVALID_STATUS_TRANSITION';
    public const FISCAL_PERIOD_NOT_OPEN = 'FINANCE_FISCAL_PERIOD_NOT_OPEN';
    public const ACCOUNT_NOT_POSTABLE = 'FINANCE_ACCOUNT_NOT_POSTABLE';
    public const INVALID_JOURNAL_LINE = 'FINANCE_INVALID_JOURNAL_LINE';
    public const IMMUTABLE_POSTED_JOURNAL = 'FINANCE_IMMUTABLE_POSTED_JOURNAL';
}
