<?php

declare(strict_types=1);

namespace Modules\Finance\Domain\Constants;

final class FinanceErrorCode
{
    public const INVALID_VALUE = 'FINANCE_INVALID_VALUE';
    public const NOT_FOUND = 'FINANCE_NOT_FOUND';
    public const CONFLICT = 'FINANCE_CONFLICT';
    public const UNBALANCED_JOURNAL_ENTRY = 'FINANCE_UNBALANCED_JOURNAL_ENTRY';
    public const INVALID_STATUS_TRANSITION = 'FINANCE_INVALID_STATUS_TRANSITION';
    public const LEDGER_ALREADY_POSTED = 'FINANCE_LEDGER_ALREADY_POSTED';
    public const EVENT_ALREADY_PROCESSED = 'FINANCE_EVENT_ALREADY_PROCESSED';
    public const FISCAL_PERIOD_NOT_OPEN = 'FINANCE_FISCAL_PERIOD_NOT_OPEN';
    public const FISCAL_PERIOD_HAS_DRAFT_ENTRIES = 'FINANCE_FISCAL_PERIOD_HAS_DRAFT_ENTRIES';
}
